---
permalink: sm-storage/access-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access volumes 
summary: 'Un volumen de acceso es un volumen configurado en fábrica de la cabina de almacenamiento que se utiliza para la comunicación con la cabina de almacenamiento y el host mediante la conexión de I/o del host. El volumen de acceso requiere un número de unidad lógica (LUN).' 
---
= Volúmenes de acceso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un volumen de acceso es un volumen configurado en fábrica de la cabina de almacenamiento que se utiliza para la comunicación con la cabina de almacenamiento y el host mediante la conexión de I/o del host. El volumen de acceso requiere un número de unidad lógica (LUN).

El volumen de acceso se utiliza en la siguiente instancia:

* *Administración en banda* -- el volumen de acceso se utiliza para una conexión en banda para administrar la matriz de almacenamiento. Esto solo puede llevarse a cabo si la cabina de almacenamiento se gestiona con la interfaz de línea de comandos (CLI).
+
[NOTE]
====
La gestión en banda con el volumen de acceso no está disponible para los sistemas de almacenamiento E4000, EF600/EF600C o EF300/EF300C.

====


Un volumen de acceso se crea automáticamente la primera vez que se asigna un volumen a un host. Por ejemplo, si asigna Volume_1 y Volume_2 a un host, cuando observe los resultados de esa asignación, notará la existencia de tres volúmenes (Volume_1, Volume_2 y Access).

Si no desea crear hosts automáticamente ni gestionar una cabina de almacenamiento en banda con la CLI, no necesita el volumen de acceso; por lo tanto, puede eliminarlo para liberar el LUN. Esta acción quita la asignación de volumen a LUN y todas las conexiones de gestión en banda al host.
