---
permalink: sm-storage/add-capacity-to-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, capacity, pool, volume, group 
summary: Es posible añadir unidades para expandir la capacidad de un pool o un grupo de volúmenes existente. 
---
= Agregar capacidad a un grupo o grupo de volúmenes en SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible añadir unidades para expandir la capacidad de un pool o un grupo de volúmenes existente.

Con la ampliación, se incluye capacidad libre adicional al pool o grupo de volúmenes. Se puede utilizar esta capacidad libre para crear volúmenes adicionales. Es posible acceder a los datos de los volúmenes durante esta operación.

.Antes de empezar
* Las unidades deben estar en el estado óptima.
* Las unidades deben ser del mismo tipo (unidad de disco duro o unidad de estado sólido).
* El pool o el grupo de volúmenes deben estar en el estado óptima.
* La cantidad máxima de volúmenes permitidos en un grupo de volúmenes es de 256.
* La cantidad máxima de volúmenes permitidos en un pool depende del modelo del sistema de almacenamiento:
+
** 2,048 volúmenes (EF80, EF600 y E5700 series)
** 1,024 volúmenes (EF50 y EF300)
** 512 volúmenes (series E4000 y E2800)


* Si todas las unidades del pool o grupo de volúmenes son compatibles con la función de seguridad, añada únicamente unidades compatibles con la función de seguridad para continuar usando las habilidades de cifrado de ese tipo de unidades.
+
Las unidades compatibles con la función de seguridad pueden ser unidades de cifrado de disco completo (FDE) o de estándar de procesamiento de información federal (FIPS).



.Acerca de esta tarea
En los pools, es posible añadir 60 unidades al mismo tiempo como máximo. En los grupos de volúmenes, es posible añadir 2 unidades al mismo tiempo como máximo. Si necesita añadir más unidades que la cantidad máxima, repita el procedimiento. (Un pool no puede contener más unidades que el límite máximo de un sistema de almacenamiento.)

[NOTE]
====
Al añadir unidades, es posible que sea necesario aumentar la capacidad de conservación. Se recomienda aumentar la capacidad reservada después de una operación de ampliación.

====
[NOTE]
====
Evita usar unidades que sean compatibles con Data Assurance (DA) para agregar capacidad a un pool o grupo de volúmenes que no sea compatible con DA. El pool o grupo de volúmenes no puede aprovechar las capacidades de la unidad compatible con DA. Considera usar unidades que no sean compatibles con DA en esta situación.

====
.Pasos
. En el panel izquierdo, selecciona menú:Storage[Pools y grupos de volúmenes].
. Selecciona el pool o grupo de volúmenes al que quieres añadir unidades y luego haz clic en el menú:ellipsis icon[Añadir capacidad].
+
Aparece el cuadro de diálogo Add capacity. Solo aparecen las unidades no asignadas que son compatibles con el pool o volume group.

. En *Select drives to Add capacity...*, selecciona una o varias unidades que quieras añadir al pool o grupo de volúmenes existente.
+
El firmware de la controladora ordena las unidades sin asignar de modo que las mejores opciones se enumeren primero. La capacidad libre total añadida al pool o grupo de volúmenes se muestra debajo de la lista en *capacidad total seleccionada*.

+
.Detalles del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Campo | Descripción 


 a| 
Bandeja
 a| 
Indica la ubicación de la bandeja de la unidad.



 a| 
Bahía
 a| 
Indica la ubicación de la bahía de la unidad.



 a| 
Capacidad (GIB)
 a| 
Indica la capacidad de la unidad.

** Siempre que sea posible, seleccione unidades con una capacidad igual a la de las unidades actuales en el pool o el grupo de volúmenes.
** Si debe añadir unidades sin asignar con una capacidad menor, tenga en cuenta que se reducirá la capacidad utilizable de cada unidad actual en el pool o el grupo de volúmenes. Por lo tanto, la capacidad de las unidades es la misma en todo el pool o grupo de volúmenes.
** Si debe añadir unidades sin asignar con una capacidad mayor, tenga en cuenta que se reducirá la capacidad utilizable de las unidades sin asignar que añada para que coincida con las capacidades actuales de las unidades en el pool o el grupo de volúmenes.




 a| 
Compatible con la función de seguridad
 a| 
Indica si la unidad es compatible con la función de seguridad.

** Para proteger el pool o el grupo de volúmenes con la función Drive Security, todas las unidades deben ser compatibles con la función de seguridad.
** Es posible crear un pool o un grupo de volúmenes con una combinación de unidades compatibles y no compatibles con la función de seguridad, pero la función Drive Security no puede estar habilitada.
** Un pool o un grupo de volúmenes con todas unidades compatibles con la función de seguridad no pueden aceptar una unidad no compatible con la función de seguridad para realizar reservas o expansión, aunque no esté en uso la funcionalidad de cifrado.
** Las unidades que se notifican como compatibles con la función de seguridad pueden ser unidades de cifrado de disco completo (FDE) o unidades de estándar de procesamiento de información federal (FIPS).
** Una unidad FIPS puede ser de nivel 140-2 o 140-3, con el nivel 140-3 como mayor nivel de seguridad. Si se selecciona una combinación de unidades de 140-2 y 140-3 niveles, el pool o el grupo de volúmenes luego se operará al nivel de seguridad menor (140-2).




 a| 
Compatible con DA
 a| 
Indica si la unidad es compatible con la función Data Assurance (DA).

** No se recomienda usar unidades que no sean compatibles con Data Assurance (DA) para Add capacity to a DA-capable pool or volume group. El pool o grupo de volúmenes ya no tiene capacidades DA y ya no tienes la opción de habilitar DA en los volúmenes recién creados dentro del pool o grupo de volúmenes.
** No se recomienda usar unidades que sean aptas para Data Assurance (DA) para agregar capacidad a un pool o grupo de volúmenes que no sea apto para DA, porque ese pool o grupo de volúmenes no puede aprovechar las capacidades de la unidad apta para DA (los atributos de la unidad no coinciden). Considera usar unidades que no sean aptas para DA en esta situación.




 a| 
Compatible con DULBE
 a| 
Indica si la unidad tiene la opción de Deallocated or Unwritten Logical Block Error (DULBE). DULBE es una opción en las unidades NVMe que permite que la matriz de almacenamiento EF80, EF50, EF300 o EF600 admita volúmenes aprovisionados de recursos.

|===
====
. Haga clic en *Agregar*.
+
Si desea añadir unidades a un pool o grupo de volúmenes, se muestra un cuadro de diálogo de confirmación al seleccionar una unidad por la que el pool o el grupo de volúmenes ya no tendrá uno o varios de los siguientes atributos:

+
** Protección contra pérdida de bandeja ^*^
** Protección contra pérdida de cajón ^*^
** Funcionalidad de cifrado de disco completo
** Funcionalidad de garantía de datos
** Funcionalidad DULBE





NOTE: ^*^ En este momento, el cuadro de diálogo de confirmación no se muestra al añadir unidades a un pool con protección contra pérdida de bandeja o protección contra pérdida de cajón.

. Para continuar, haga clic en *Sí*; de lo contrario, haga clic en *Cancelar*.


.Resultados
Después de añadir las unidades sin asignar a un pool o grupo de volúmenes, se redistribuyen los datos de cada volumen del pool o del grupo de volúmenes para incluir las unidades adicionales.
