---
permalink: sm-storage/automatic-versus-manual-host-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, manual, host, 
summary: La creación de un host es uno de los pasos necesarios para indicar a la cabina de almacenamiento qué hosts están conectados a ella y para permitir el acceso de I/o a los volúmenes. Es posible crear un host de manera automática o manual. 
---
= Creación de hosts automática versus manual
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La creación de un host es uno de los pasos necesarios para indicar a la cabina de almacenamiento qué hosts están conectados a ella y para permitir el acceso de I/o a los volúmenes. Es posible crear un host de manera automática o manual.



== Creación automática

La creación automática de hosts para hosts basados en SCSI (no NVMe-of) se inicia desde el agente de contexto de host (HCA). HCA es una utilidad que puede instalar en cada host conectado a la cabina de almacenamiento. Cada host que posee HCA instalado inserta su información de configuración en la cabina de almacenamiento a través de la ruta de I/O. Según la información del host, las controladoras crean automáticamente el host y los puertos de host asociados para establecer el tipo de host. Si es necesario, puede realizar cualquier cambio adicional en la configuración del host con System Manager.

Después de que HCA realiza la detección automática, el host aparece automáticamente en la página hosts con los siguientes atributos:

* El nombre de host derivado del nombre de sistema del host.
* Los puertos identificadores del host que están asociados con el host.
* El tipo de sistema operativo del host.


Los hosts se crean como hosts independientes; HCA no los crea ni los añade automáticamente a clústeres de hosts.



== Creación manual

Quizás sea conveniente crear manualmente un host por uno de los siguientes motivos:

. Decide no instalar la utilidad HCA en los hosts.
. Quiere asegurarse de que los identificadores de puerto de host que detectaron las controladoras de la cabina de almacenamiento están asociados correctamente con los hosts.


Durante la creación manual de hosts, debe seleccionar manualmente los identificadores de puerto de host o introducirlos manualmente para asociarlos. Después de crear un host, puede asignar volúmenes a él o añadirlo a un clúster de hosts si el objetivo es compartir el acceso a los volúmenes.
