---
permalink: sm-storage/change-host-port-identifiers-for-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host port, identifiers, host 
summary: Los identificadores de puerto de host se cambian cuando se desea cambiar la etiqueta de usuario en un identificador de puerto de host, agregar un nuevo identificador de puerto de host al host o eliminar un identificador de puerto de host del host. 
---
= Cambiar los identificadores del puerto de host para un host en SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los identificadores de puerto de host se cambian cuando se desea cambiar la etiqueta de usuario en un identificador de puerto de host, agregar un nuevo identificador de puerto de host al host o eliminar un identificador de puerto de host del host.

.Acerca de esta tarea
Cuando se cambian identificadores de puerto de host, se deben tener en cuenta las siguientes directrices:

* *Add* -- cuando se agrega un puerto de host, se asocia el identificador de puerto de host al host creado para conectarse a la matriz de almacenamiento. Es posible introducir información manualmente mediante una utilidad de adaptador de bus de host (HBA).
* *Editar* -- puede editar los puertos de host para mover (asociar) un puerto de host a otro host. Es posible que se haya movido el adaptador de bus de host o iniciador de iSCSI a otro host, de modo que se debe mover (asociar) el puerto de host al nuevo host.
* *Eliminar* -- puede eliminar puertos de host para eliminar (desasociar) puertos de host de un host.


.Pasos
. En el panel izquierdo, selecciona el menú:Storage[Hosts].
. Selecciona el host al que se asociarán los puertos y luego haz clic en el icono del menú:ellipsis icon[Edit Settings].
+
Si quieres añadir puertos a un host en un clúster de hosts, selecciona el host que quieras. No puedes añadir puertos a nivel de clúster de hosts.

+
Aparece una pantalla Edit host settings que muestra la configuración actual del host.

. Cambie la configuración del identificador de puerto de host, según corresponda.
+
[cols="25h,~"]
|===
| Ajuste | Descripción 


 a| 
Puerto de host
 a| 
Es posible elegir una de las siguientes opciones:

** *Add host port* -- Haz clic en *Add host port* para asociar un nuevo identificador de puerto de host al host. La longitud del nombre del identificador de puerto de host está determinada por la tecnología de interfaz del host. Los nombres de identificador de puerto de host Fibre Channel e Infiniband deben tener 16 caracteres. Los nombres de identificador de puerto de host iSCSI tienen un máximo de 223 caracteres. El puerto debe ser único. No se permite un número de puerto que ya haya sido configurado.
** *Eliminar (icono X)* -- Haz clic en el icono *X* para eliminar (desasociar) un identificador de puerto de host. La opción eliminar no elimina físicamente el puerto de host. Esta opción elimina la asociación entre el puerto de host y el host. A menos que elimines el adaptador de bus de host o el iniciador iSCSI, el puerto de host sigue siendo reconocido por el controlador.
+
[NOTE]
====
Si se elimina el identificador de puerto de host, el identificador ya no sigue asociado a este host. Además, el host pierde acceso a cualquiera de los volúmenes asignados a través de este identificador de puerto de host.

====




 a| 
Nombre
 a| 
Si es necesario, puedes cambiar el nombre de la etiqueta del puerto. El nombre de la etiqueta del puerto debe ser único. No se permite un nombre de etiqueta que ya se haya configurado.



 a| 
Secreto CHAP
 a| 
Solo se muestra para los hosts iSCSI. Es posible configurar o cambiar el secreto CHAP para los iniciadores (hosts iSCSI).

System Manager usa el método de protocolo de autenticación por desafío mutuo (CHAP), que valida la identidad de los destinos e iniciadores durante el enlace inicial. La autenticación se basa en una clave de seguridad compartida denominada secreto CHAP.

|===
. Haga clic en *Guardar*.

