---
permalink: sm-storage/change-settings-for-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, volume 
summary: Es posible cambiar la configuración de un volumen, como el nombre, la asignación de host, el tamaño de segmento, la prioridad de modificación, el almacenamiento en caché y así sucesivamente. 
---
= Cambiar la configuración de un volumen en SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar la configuración de un volumen, como el nombre, la asignación de host, el tamaño de segmento, la prioridad de modificación, el almacenamiento en caché y así sucesivamente.

.Antes de empezar
El volumen que desea cambiar debe estar en estado óptimo.


NOTE: Es posible que algunas operaciones no estén disponibles mientras haya cambios en la configuración del volumen en curso

.Pasos
. En el panel izquierdo, selecciona menú:Storage[Volumes].
. Selecciona el volumen que quieres cambiar y luego haz clic en el menú:ellipsis icon[Edit Settings].
+
Aparece la ventana Edit Volume Settings, que muestra los ajustes de configuración para el volumen seleccionado.

. Configura los ajustes de volumen según sea necesario:
+
.Detalles del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Ajuste | Descripción 


 a| 
Nombre
 a| 
Muestra el nombre del volumen. Cambie el nombre de un volumen cuando el actual ya no sea significativo o no corresponda.



 a| 
Host
 a| 
Muestra la asignación del volumen. Es posible asignar un volumen a un host o clúster de hosts para poder acceder a él como parte de operaciones de I/O. Esta asignación otorga acceso a un host o un clúster de hosts a un volumen determinado o a una cantidad de volúmenes en una cabina de almacenamiento.

** *Asignado a* -- identifica el host o clúster de hosts que tiene acceso al volumen seleccionado.
** *LUN* -- un número de unidad lógica (LUN) es el número asignado al espacio de dirección que un host utiliza para acceder a un volumen. El volumen se presenta al host como capacidad en forma de LUN. Cada host tiene su propio espacio de dirección de LUN. Por lo tanto, distintos hosts pueden utilizar el mismo LUN para acceder a diferentes volúmenes.
+

NOTE: En las interfaces NVMe, esta columna muestra Namespace ID. Un espacio de nombres es almacenamiento NVM que se formateó para el acceso en bloque. Es análogo a una unidad lógica en SCSI, que se relaciona con un volumen en la cabina de almacenamiento. El ID del espacio de nombres es el identificador único de la controladora NVMe para el espacio de nombres y se puede configurar con un valor entre 1 y 255. Es análogo a un número de unidad lógica (LUN) en SCSI.





 a| 
Ajuste de tamaño del segmento
 a| 
Muestra la configuración de ajuste de tamaño, que solo aparece para los volúmenes de un grupo de volúmenes. Se puede cambiar el tamaño del segmento para optimizar el rendimiento.

*Transiciones de tamaño de segmento permitidas* -- System Manager determina las transiciones de tamaño de segmento permitidas. Los tamaños de segmento que no son transiciones adecuadas para el tamaño de segmento actual no están disponibles en la lista desplegable. Las transiciones permitidas, por lo general, son el doble o la mitad del tamaño de segmento actual. Por ejemplo, si el tamaño de segmento del volumen actual es 32 KiB, se permite un tamaño de segmento de volumen nuevo de 16 KiB o 64 KiB.

*Volúmenes con caché SSD* habilitada -- se puede especificar un tamaño de segmento de 4 KiB para volúmenes con caché SSD habilitada. Asegúrese de seleccionar el tamaño de segmento 4 KiB solo para los volúmenes con la función SSD Cache habilitada que controlan operaciones de I/o en bloques pequeños (por ejemplo, tamaños de bloques de I/o de 16 KiB o menos). El rendimiento podría verse afectado si selecciona 4 KiB para el tamaño de segmento en los volúmenes con la función SSD Cache habilitada que controlan operaciones secuenciales de bloques grandes.

*Cantidad de tiempo para cambiar el tamaño del segmento* -- la cantidad de tiempo para cambiar el tamaño del segmento de un volumen depende de estas variables:

** La carga de I/o desde el host
** La prioridad de modificación del volumen
** La cantidad de unidades del grupo de volúmenes
** La cantidad de canales de unidades
** La potencia de procesamiento de las controladoras de la cabina de almacenamiento cuando se cambia el tamaño de segmento de un volumen, el rendimiento de I/o se ve afectado, pero los datos siguen disponibles.




 a| 
Prioridad de modificación
 a| 
Muestra la configuración de prioridad de modificación, que solo aparece para los volúmenes en un grupo de volúmenes.

La prioridad de modificación define la cantidad de tiempo de procesamiento que se asigna a las operaciones de modificación del volumen en relación con el rendimiento del sistema. Es posible aumentar la prioridad de modificación del volumen, pero esto puede afectar al rendimiento del sistema.

Mueva las barras del control deslizante para seleccionar un nivel de prioridad.

*Tasas de prioridad de modificación* -- la tasa de prioridad más baja beneficia el rendimiento del sistema, pero la operación de modificación lleva más tiempo. La tasa de prioridad más alta beneficia a la operación de modificación, pero el rendimiento del sistema puede verse afectado.

|===
====
. Haga clic en *Guardar*.
+
System Manager cambia la configuración del volumen según sus preferencias.



.Después de terminar
Selecciona menu:Storage[Operations in Progress] para ver el progreso de las operaciones de cambio que se están ejecutando actualmente para el volumen seleccionado.
