---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-snapshot-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, snapshot, group 
summary: Es posible modificar la configuración de un grupo Snapshot y cambiarle el nombre, la configuración de eliminación automática, la cantidad máxima de imágenes Snapshot permitidas, el punto de porcentaje en el que System Manager envía una alerta de capacidad reservada, o bien la política que debe utilizarse cuando la capacidad reservada alcanza el porcentaje máximo definido. 
---
= Cambiar la configuración de capacidad reservada para un grupo Snapshot
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible modificar la configuración de un grupo Snapshot y cambiarle el nombre, la configuración de eliminación automática, la cantidad máxima de imágenes Snapshot permitidas, el punto de porcentaje en el que System Manager envía una alerta de capacidad reservada, o bien la política que debe utilizarse cuando la capacidad reservada alcanza el porcentaje máximo definido.

Durante la creación de un grupo Snapshot, se crea capacidad reservada para almacenar los datos de todas las imágenes Snapshot que contiene el grupo.

.Pasos
. Seleccione MENU:almacenamiento[Pools y grupos de volúmenes].
. Haga clic en la pestaña *capacidad reservada*.
. Seleccione el grupo de instantáneas que desea editar y, a continuación, haga clic en *Ver/editar configuración*.
+
Se muestra el cuadro de diálogo Configuración del grupo Snapshot.

. Cambie la configuración del grupo Snapshot según sea necesario.
+
.Detalles del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Ajuste | Descripción 


 a| 
*Ajustes del grupo Snapshot*



 a| 
Nombre
 a| 
El nombre del grupo Snapshot. Es necesario indicar un nombre para el grupo Snapshot.



 a| 
Eliminación automática
 a| 
Un ajuste para mantener la cantidad total de imágenes Snapshot del grupo en un valor igual o inferior al máximo establecido por el usuario. Cuando esta opción está habilitada, System Manager elimina automáticamente la imagen Snapshot más antigua del grupo cada vez que se crea una imagen Snapshot nueva, a fin de poder cumplir con la cantidad máxima de imágenes Snapshot permitidas en el grupo.



 a| 
Límite de la imagen Snapshot
 a| 
Un valor configurable para especificar la cantidad máxima de imágenes Snapshot permitidas en un grupo.



 a| 
Programación Snapshot
 a| 
En caso afirmativo, se establece una programación para crear Snapshot automáticamente.



 a| 
*Ajustes de capacidad reservada*



 a| 
Enviarme una alerta cuando...
 a| 
Use el cuadro de desplazamiento para ajustar el punto de porcentaje en el que System Manager envía una notificación de alerta cuando la capacidad reservada de un grupo Snapshot está casi completa.

Cuando la capacidad reservada del grupo Snapshot supera el umbral especificado, System Manager envía una alerta que otorga tiempo para aumentar la capacidad reservada o eliminar los objetos innecesarios.



 a| 
Política para capacidad reservada completa
 a| 
Se puede seleccionar una de las siguientes políticas:

** *Purgar la imagen Snapshot más antigua* -- System Manager purga automáticamente la imagen Snapshot más antigua del grupo Snapshot, lo que libera la capacidad reservada de la imagen Snapshot para su reutilización dentro del grupo.
** *Rechazar escrituras en volumen base*: Cuando la capacidad reservada alcanza el porcentaje máximo definido, System Manager rechaza toda solicitud de escritura de I/o en el volumen base que activó el acceso a la capacidad reservada.




 a| 
*Objetos asociados*



 a| 
Volumen base
 a| 
El nombre del volumen base utilizado para el grupo. Un volumen base es el origen desde el cual se crea una imagen Snapshot. Puede ser un volumen grueso o fino y, por lo general, se asigna a un host. El volumen base puede residir en un grupo de volúmenes o un pool de discos.



 a| 
Imágenes Snapshot
 a| 
La cantidad de imágenes creadas a partir de este grupo. Una imagen Snapshot es una copia lógica de datos de volúmenes capturados en un momento específico. Al igual que un punto de restauración, las imágenes Snapshot permiten revertir a un conjunto de datos bien conocidos. Si bien el host puede acceder a la imagen Snapshot, no puede leer ni escribir allí directamente.

|===
====
. Haga clic en *Guardar* para aplicar los cambios a la configuración del grupo de instantáneas.

