---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-snapshot-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, snapshot, group 
summary: Es posible modificar la configuración de un grupo Snapshot y cambiarle el nombre, la configuración de eliminación automática, la cantidad máxima de imágenes Snapshot permitidas, el punto de porcentaje en el que System Manager envía una alerta de capacidad reservada, o bien la política que debe utilizarse cuando la capacidad reservada alcanza el porcentaje máximo definido. 
---
= Cambiar la configuración de capacidad reservada para un grupo de instantáneas en SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible modificar la configuración de un grupo Snapshot y cambiarle el nombre, la configuración de eliminación automática, la cantidad máxima de imágenes Snapshot permitidas, el punto de porcentaje en el que SANtricity System Manager envía una alerta de capacidad reservada, o bien la política que debe utilizarse cuando la capacidad reservada alcanza el porcentaje máximo definido.

Durante la creación de un grupo Snapshot, se crea capacidad reservada para almacenar los datos de todas las imágenes Snapshot que contiene el grupo.

.Pasos
. En el panel izquierdo, selecciona menú:Storage[Pools y grupos de volúmenes].
. Haga clic en la pestaña *capacidad reservada*.
. Selecciona el grupo de instantáneas que quieres editar y luego haz clic en el icono menu:ellipsis[Edit Settings].
+
Aparece la ventana Edit snapshot group settings.

. Cambie la configuración del grupo Snapshot según sea necesario.
+
.Detalles del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Ajuste | Descripción 


 a| 
*Ajustes del grupo Snapshot*



 a| 
Nombre
 a| 
El nombre del grupo Snapshot. Es necesario indicar un nombre para el grupo Snapshot.



 a| 
Eliminación automática de imágenes snapshot
 a| 
Un ajuste para mantener la cantidad total de imágenes Snapshot del grupo en un valor igual o inferior al máximo establecido por el usuario. Cuando esta opción está habilitada, System Manager elimina automáticamente la imagen Snapshot más antigua del grupo cada vez que se crea una imagen Snapshot nueva, a fin de poder cumplir con la cantidad máxima de imágenes Snapshot permitidas en el grupo.



 a| 
Límite de la imagen Snapshot
 a| 
Un valor configurable para especificar la cantidad máxima de imágenes Snapshot permitidas en un grupo.



 a| 
*Ajustes de capacidad reservada*



 a| 
Enviarme una alerta cuando...
 a| 
Use el cuadro de desplazamiento para ajustar el punto de porcentaje en el que System Manager envía una notificación de alerta cuando la capacidad reservada de un grupo Snapshot está casi completa.

Cuando la capacidad reservada del grupo Snapshot supera el umbral especificado, System Manager envía una alerta que otorga tiempo para aumentar la capacidad reservada o eliminar los objetos innecesarios.



 a| 
Política para capacidad reservada completa
 a| 
Se puede seleccionar una de las siguientes políticas:

** *Purgar la imagen Snapshot más antigua* -- System Manager purga automáticamente la imagen Snapshot más antigua del grupo Snapshot, lo que libera la capacidad reservada de la imagen Snapshot para su reutilización dentro del grupo.
** *Rechazar escrituras en volumen base*: Cuando la capacidad reservada alcanza el porcentaje máximo definido, System Manager rechaza toda solicitud de escritura de I/o en el volumen base que activó el acceso a la capacidad reservada.


|===
====
. Haga clic en *Guardar* para aplicar los cambios a la configuración del grupo de instantáneas.

