---
permalink: sm-storage/change-the-settings-for-a-host-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, host, cluster 
summary: Es posible cambiar el nombre del clúster de hosts, o bien añadir o eliminar hosts de un clúster. 
---
= Cambiar la configuración de un clúster de host en SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar el nombre del clúster de hosts, o bien añadir o eliminar hosts de un clúster.

.Pasos
. En el panel izquierdo, selecciona el menú:Storage[Hosts].
. Selecciona el clúster de host que quieres editar y luego haz clic en el icono del menú:ellipsis icon[Edit Settings].
+
Aparece una ventana que muestra la configuración actual del host cluster.

. Cambie la configuración del clúster de hosts según sea necesario.
+
.Detalles del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Ajuste | Descripción 


 a| 
Nombre
 a| 
Es posible especificar el nombre provisto por el usuario del clúster de hosts. Es necesario especificar el nombre de un clúster.



 a| 
Hosts asociados
 a| 
Para agregar un host, haga clic en el cuadro *hosts asociados* y, a continuación, seleccione un nombre de host en la lista desplegable. El nombre de host no se puede introducir manualmente.

Para eliminar un host, haga clic en *X* junto al nombre de host.

|===
====
. Haga clic en *Guardar*.

