---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, mirrored pair volume 
summary: Puede cambiar la configuración del volumen de una pareja reflejada a fin de ajustar el punto de porcentaje en el que System Manager envía una notificación de alerta cuando la capacidad reservada para una pareja reflejada está casi completa. 
---
= Cambie la configuración de capacidad reservada para un volumen de parejas reflejadas
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar la configuración del volumen de una pareja reflejada a fin de ajustar el punto de porcentaje en el que SANtricity System Manager envía una notificación de alerta cuando la capacidad reservada para una pareja reflejada está casi completa.

.Pasos
. Seleccione MENU:almacenamiento[Pools y grupos de volúmenes].
. Seleccione la pestaña *capacidad reservada*.
. Seleccione el volumen de la pareja reflejada que desea editar y, a continuación, haga clic en *Ver/editar configuración*.
+
Se muestra el cuadro de diálogo Configuración de capacidad reservada de volumen de pareja reflejada.

. Cambie la configuración de la capacidad reservada para el volumen de la pareja reflejada, según sea necesario.
+
.Detalles del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Ajuste | Descripción 


 a| 
Enviarme una alerta cuando...
 a| 
Use el cuadro de desplazamiento para ajustar el punto de porcentaje en el que System Manager envía una notificación de alerta cuando la capacidad reservada de una pareja reflejada está casi completa.

Cuando la capacidad reservada de la pareja reflejada supera el umbral especificado, System Manager envía una alerta que otorga tiempo para aumentar la capacidad reservada.


NOTE: Si se cambia la configuración de alertas de una pareja reflejada, se modifica la configuración de alertas de todas las parejas reflejadas que pertenecen al mismo grupo de coherencia reflejado.

|===
====
. Haga clic en *Guardar* para aplicar los cambios.

