---
permalink: sm-storage/create-ssd-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, ssd, cache 
summary: 'Para acelerar de manera dinámica el rendimiento del sistema, se puede usar la función SSD Cache para almacenar en caché los datos a los que se accede con mayor frecuencia (datos "activos") en unidades de estado sólido (SSD) de menor latencia. La caché SSD se usa exclusivamente para las lecturas del host.' 
---
= Cree una caché SSD
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para acelerar de manera dinámica el rendimiento del sistema, se puede usar la función SSD Cache para almacenar en caché los datos a los que se accede con mayor frecuencia (datos "activos") en unidades de estado sólido (SSD) de menor latencia. La caché SSD se usa exclusivamente para las lecturas del host.

.Antes de empezar
La cabina de almacenamiento debe tener algunas unidades SSD.

[NOTE]
====
Caché SSD no está disponible en los sistemas de almacenamiento EF600 o EF300.

====
.Acerca de esta tarea
Para la creación de una caché SSD, es posible usar una unidad única o varias unidades. Debido a que la caché de lectura se encuentra en la cabina de almacenamiento, todas las aplicaciones que utilizan la cabina de almacenamiento comparten el almacenamiento en caché. Una vez seleccionados los volúmenes que se desean almacenar en caché, el almacenamiento en caché se realiza de forma automática y dinámica.

Siga las siguientes directrices al crear una caché SSD.

* Puede habilitar la función de seguridad en la caché SSD solo en el momento de la creación, no después.
* Solo se admite una caché SSD por cabina de almacenamiento.
* La capacidad máxima de la caché SSD utilizable de una cabina de almacenamiento depende de la capacidad de la caché primaria de la controladora.
* Las imágenes Snapshot no admiten la función SSD Cache.
* Si importa o exporta volúmenes que tienen habilitada o deshabilitada la función SSD Cache, los datos en caché no se importan ni se exportan.
* Cualquier volumen asignado para utilizar una caché SSD de una controladora no es elegible para una transferencia de equilibrio de carga automática.
* Si los volúmenes asociados tienen la función de seguridad habilitada, cree una caché SSD con la función de seguridad habilitada.


.Pasos
. Seleccione MENU:almacenamiento[Pools y grupos de volúmenes].
. Haga clic en menú:Crear[caché SSD].
+
Se muestra el cuadro de diálogo Crear caché SSD.

. Escriba un nombre para la caché SSD.
. Seleccione el candidato de caché SSD que desea usar según las siguientes características.
+
[cols="25h,~"]
|===
| Característica | Uso 


 a| 
Capacidad
 a| 
Muestra la capacidad disponible en GIB. Seleccione la capacidad que necesita el almacenamiento de la aplicación.

La capacidad máxima de la caché SSD depende de la capacidad de caché primaria de la controladora. Si se asigna más de la cantidad máxima a la caché SSD, no se podrá utilizar la capacidad excedente.

La capacidad de la caché SSD se debe incluir en la capacidad total asignada.



 a| 
Unidades totales
 a| 
Indica la cantidad de unidades disponibles en esta caché SSD. Seleccione el candidato de SSD que tenga la cantidad de unidades que desea.



 a| 
Compatible con la función de seguridad
 a| 
Indica si este candidato de caché SSD se compone íntegramente de unidades compatibles con la función de seguridad, que pueden ser de cifrado de disco completo (FDE) o de estándar de procesamiento de información federal (FIPS).

Si desea crear una caché SSD con la función de seguridad habilitada, busque *Sí - FDE* o *Sí - FIPS* en la columna compatible con la función de seguridad.



 a| 
Habilitar seguridad?
 a| 
Ofrece la opción de habilitar la función Drive Security con unidades que sean compatibles con la función de seguridad. Si desea crear una caché SSD con la función de seguridad habilitada, marque la casilla de comprobación Habilitar seguridad.

[NOTE]
====
Una vez que habilitada, la seguridad no se puede deshabilitar. Puede habilitar la función de seguridad en la caché SSD solo en el momento de la creación, no después.

====


 a| 
Compatible con DA
 a| 
Indica si está disponible la función Data Assurance (DA) para este candidato de caché SSD. La garantía de datos (DA) comprueba y corrige los errores que se pueden producir durante la transferencia de datos a través de las controladoras hasta las unidades.

Si desea usar DA, seleccione un candidato de caché SSD que sea compatible con ESTA función. Esta opción solo está disponible si está habilitada la función DA.

Una caché SSD puede contener unidades que son compatibles con DA o que no lo son, pero todas las unidades deben ser compatibles con DA para poder usar ESTA función.

|===
. Asocie la caché SSD con los volúmenes para los que desea implementar el almacenamiento en caché de lectura de SSD. Para activar caché SSD en volúmenes compatibles de inmediato, active la casilla de verificación *Activar caché SSD en volúmenes compatibles existentes asignados a hosts*.
+
Los volúmenes son compatibles si comparten las mismas funcionalidades Drive Security y DA.

. Haga clic en *Crear*.

