---
permalink: sm-storage/create-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, volumes 
summary: Se crean volúmenes para añadir capacidad de almacenamiento a una carga de trabajo específica de la aplicación y para que los volúmenes creados sean visibles para un host o clúster de hosts específicos. Además, la secuencia de creación de volúmenes ofrece las opciones de asignar cantidades específicas de capacidad a cada volumen que desea crear. 
---
= Cree volúmenes
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se crean volúmenes para añadir capacidad de almacenamiento a una carga de trabajo específica de la aplicación y para que los volúmenes creados sean visibles para un host o clúster de hosts específicos. Además, la secuencia de creación de volúmenes ofrece las opciones de asignar cantidades específicas de capacidad a cada volumen que desea crear.

.Acerca de esta tarea
La mayoría de los tipos de aplicaciones adoptan la configuración de volúmenes definida por el usuario en forma predeterminada. Algunos tipos de aplicaciones tienen una configuración inteligente aplicada al crear el volumen. Por ejemplo, si se crean volúmenes para la aplicación Microsoft Exchange, se consultará cuántos buzones se necesitan, cuáles son los requisitos de capacidad promedio del buzón y cuántas copias de la base de datos se desean. System Manager utiliza esta información para crear una configuración de volumen óptima para el usuario, que se puede editar en caso de ser necesario.

El proceso para crear un volumen es un procedimiento de varios pasos.



== Paso 1: Seleccionar el host para un volumen

Se crean volúmenes para añadir capacidad de almacenamiento a una carga de trabajo específica de la aplicación y para que los volúmenes creados sean visibles para un host o clúster de hosts específicos. Además, la secuencia de creación de volúmenes ofrece las opciones de asignar cantidades específicas de capacidad a cada volumen que desea crear.

.Antes de empezar
* Existen hosts o clústeres de hosts válidos en el icono hosts.
* Se definieron identificadores de puertos de host para el host.
* Para poder crear un volumen con la función DA habilitada, la conexión de host que se planea usar debe admitir DA. Si alguna de las conexiones de host de las controladoras de la cabina de almacenamiento no admite DA, los hosts asociados no podrán acceder a los datos de los volúmenes con la función DA habilitada.


.Acerca de esta tarea
Tenga en cuenta estas directrices al asignar volúmenes:

* El sistema operativo de un host puede tener límites específicos acerca de la cantidad de volúmenes a los que puede acceder el host. Tenga presente este límite cuando cree volúmenes que utilizará un host en particular.
* Puede definir una asignación para cada volumen de la cabina de almacenamiento.
* Los volúmenes asignados se comparten entre controladoras de la cabina de almacenamiento.
* El host o un clúster de hosts no pueden usar el mismo número de unidad lógica (LUN) dos veces para acceder a un volumen. Se debe usar un LUN único.
* Si desea acelerar el proceso para crear volúmenes, puede omitir el paso de asignación de host para que los volúmenes recién creados se inicialicen sin conexión.


[NOTE]
====
Se producirá un error al asignar un volumen a un host si se intenta asignar un volumen a un clúster de hosts que produce un conflicto con una asignación establecida para un host en los clústeres de hosts.

====
.Pasos
. Seleccione MENU:Storage[Volumes].
. Seleccione MENU:Create[Volume].
+
Se muestra el cuadro de diálogo Crear volúmenes.

. De la lista desplegable, seleccione el host o el clúster de hosts específicos a los que desea asignar volúmenes o elija asignar el host o el clúster de hosts más adelante.
. Para continuar con la secuencia de creación de volúmenes para el host o clúster de hosts seleccionados, haga clic en *Siguiente*, y vaya a. <<Paso 2: Seleccionar una carga de trabajo para un volumen>>.
+
Se muestra el cuadro de diálogo Seleccionar carga de trabajo.





== Paso 2: Seleccionar una carga de trabajo para un volumen

Seleccione una carga de trabajo a fin de personalizar la configuración de la cabina de almacenamiento para una aplicación específica, por ejemplo, Microsoft SQL Server, Microsoft Exchange, aplicaciones de videovigilancia o VMware. Puede seleccionar "otra aplicación" si la aplicación que pretende usar de esta cabina de almacenamiento no aparece en la lista.

.Acerca de esta tarea
En esta tarea, se describe cómo crear volúmenes para una carga de trabajo existente.

* _Cuando se crean volúmenes con una carga de trabajo específica de la aplicación_, el sistema puede recomendar una configuración de volumen optimizada para minimizar la contención entre las operaciones de I/o de la carga de trabajo de la aplicación y demás tráfico de la instancia de la aplicación. Se puede revisar la configuración de volumen recomendada y editar, añadir o eliminar volúmenes y características recomendados por el sistema mediante el cuadro de diálogo Añadir/editar volúmenes.
* _Cuando se crean volúmenes mediante "Other"_ aplicaciones (o aplicaciones que no admiten la creación de un volumen específico), se debe especificar manualmente la configuración del volumen con el cuadro de diálogo Añadir/editar volúmenes.


.Pasos
. Debe realizar una de las siguientes acciones:
+
** Seleccione la opción *Crear volúmenes para una carga de trabajo existente* para crear volúmenes para una carga de trabajo existente.
** Seleccione la opción *Crear una carga de trabajo nueva* para definir una carga de trabajo nueva para una aplicación compatible o para "otras" aplicaciones.
+
*** De la lista desplegable, seleccione el nombre de la aplicación para la cual desea crear la carga de trabajo nueva.
+
Seleccione una de las entradas que figuran como "Other", si la aplicación que pretende usar en esta cabina de almacenamiento no aparece en la lista.

*** Introduzca el nombre de la carga de trabajo que desea crear.




. Haga clic en *Siguiente*.
. Si la carga de trabajo está asociada con un tipo de aplicación admitida, introduzca la información solicitada, de lo contrario, vaya a. <<Paso 3: Añadir o editar volúmenes>>.




== Paso 3: Añadir o editar volúmenes

System Manager puede sugerir una configuración de volumen según la aplicación o la carga de trabajo seleccionadas. Esta configuración de volumen se optimiza según el tipo de aplicación que admite la carga de trabajo. Se puede aceptar la configuración de volumen recomendada o se puede editar, según sea necesario. Si seleccionó la opción "Other" para aplicaciones, debe especificar manualmente los volúmenes y las características que desea crear.

.Antes de empezar
* Los pools o los grupos de volúmenes deben tener suficiente capacidad libre.
* La cantidad máxima de volúmenes permitidos en un grupo de volúmenes es de 256.
* La cantidad máxima de volúmenes permitidos en un pool depende del modelo del sistema de almacenamiento:
+
** 2.048 volúmenes (serie EF600, EF600C y E5700)
** 1.024 volúmenes (EF300 y EF300C TB)
** 512 volúmenes (series E4000 y E2800)


* Para crear un volumen que tenga habilitada la función Garantía de datos (DA), la conexión de host que se planea usar debe admitir DA.
+
.Seleccionar un pool o un grupo de volúmenes que sea compatible con la función de seguridad
[%collapsible]
====
Si desea crear un volumen con la función DA habilitada, seleccione un pool o un grupo de volúmenes que sea compatible con DA (asegúrese de *Sí* junto a "DA" en la tabla de candidatos de pools y grupos de volúmenes).

Las funcionalidades DE DA se presentan a nivel del pool y grupo de volúmenes de System Manager. La protección DE DA comprueba y corrige los errores que se pueden producir durante la transferencia de datos a través de las controladoras hasta las unidades. Al seleccionar un pool o un grupo de volúmenes compatibles con DA para el volumen nuevo, se garantizan la detección y la corrección de cualquier error.

Si alguna de las conexiones de host de las controladoras de la cabina de almacenamiento no admite DA, los hosts asociados no podrán acceder a los datos de los volúmenes con la función DA habilitada.

====
* Para crear un volumen con la función de seguridad habilitada, se debe crear una clave de seguridad para la cabina de almacenamiento.
+
.Seleccionar un pool o un grupo de volúmenes que sea compatible con la función de seguridad
[%collapsible]
====
Si desea crear un volumen con la función de seguridad habilitada, seleccione un pool o un grupo de volúmenes que sean compatibles con la función de seguridad (asegúrese de que *Sí* junto a "compatible con la función de seguridad" en la tabla de candidatos de pools y grupos de volúmenes).

Las funcionalidades de seguridad de la unidad se presentan a nivel del pool y grupo de volúmenes de System Manager. Las unidades que son compatibles con la función de seguridad evitan el acceso no autorizado a los datos de una unidad que se quita físicamente de la cabina de almacenamiento. Una unidad con la función de seguridad habilitada cifra los datos durante la escritura y descifra los datos durante las lecturas mediante una _clave de cifrado_ única.

Un pool o un grupo de volúmenes pueden contener tanto una unidad compatible con la función de seguridad como una que no lo sea, pero todas las unidades deben ser compatibles con la función de seguridad para usar la funcionalidad de cifrado.

====
* Para crear un volumen aprovisionado por recursos, todas las unidades deben ser unidades NVMe con la opción error de bloque lógico no escrito o desasignado (DULBE).


.Acerca de esta tarea
Se crean volúmenes desde los pools o los grupos de volúmenes. El cuadro de diálogo Añadir/editar volúmenes muestra todos los pools y grupos de volúmenes elegibles de la cabina de almacenamiento. Para cada pool o grupo de volúmenes elegible, se muestran la cantidad de unidades y la capacidad libre total disponibles.

Para algunas cargas de trabajo específicas de la aplicación, cada pool o grupo de volúmenes elegible muestra la capacidad propuesta según la configuración de volumen sugerido y muestra también la capacidad libre restante en GIB. Para otras cargas de trabajo, la capacidad propuesta aparece a medida que se añaden volúmenes a un pool o un grupo de volúmenes y se especifica la cantidad informada.

.Pasos
. Elija una de estas acciones según si seleccionó otra carga de trabajo específica de la aplicación o la siguiente:
+
** *Otros* -- haga clic en *Añadir nuevo volumen* en cada pool o grupo de volúmenes que desee utilizar para crear uno o más volúmenes.
+
.Detalles del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Campo | Descripción 


 a| 
Nombre del volumen
 a| 
System Manager asigna un nombre predeterminado a un volumen durante la secuencia de creación de volúmenes. Se puede aceptar el nombre predeterminado o se puede proporcionar un nombre más descriptivo que indique el tipo de datos almacenados en el volumen.



 a| 
Capacidad notificada
 a| 
Defina la capacidad del volumen nuevo y las unidades de capacidad que desea usar (MIB, GIB o TIB). Para los volúmenes gruesos, la capacidad mínima es 1 MIB y la capacidad máxima se determina mediante la cantidad y la capacidad de las unidades del pool o del grupo de volúmenes.

Recuerde que la capacidad de almacenamiento también es necesaria para los servicios de copia (imágenes Snapshot, volúmenes Snapshot, copias de volúmenes y reflejos remotos), por lo tanto, no asigne toda la capacidad a los volúmenes estándar.

La capacidad de un pool se asigna en incrementos de 4 GIB o 8 GIB, según el tipo de unidad. Se asigna cualquier capacidad que no sea múltiplo de 4 o 8 GIB, pero no se puede usar. Para asegurarse de que toda la capacidad se pueda usar, especifique la capacidad en incrementos de 4 GIB o 8 GIB. Si hubiese capacidad que no puede usar, la única manera de recuperarla es aumentar la capacidad del volumen.



 a| 
Tamaño de bloque de volumen (solo EF300 y EF600)
 a| 
Muestra los tamaños de bloque que se pueden crear para el volumen:

*** 512 -- 512 bytes
*** 4K -- 4,096 bytes




 a| 
Tamaño del segmento
 a| 
Muestra la configuración del ajuste de tamaño de segmentos, que solo aparece para los volúmenes de un grupo de volúmenes. Se puede cambiar el tamaño del segmento para optimizar el rendimiento.

*Transiciones de tamaño de segmento permitidas* -- System Manager determina las transiciones de tamaño de segmento permitidas. Los tamaños de segmento que no son transiciones adecuadas para el tamaño de segmento actual no están disponibles en la lista desplegable. Las transiciones permitidas, por lo general, son el doble o la mitad del tamaño de segmento actual. Por ejemplo, si el tamaño de segmento del volumen actual es 32 KiB, se permite un tamaño de segmento de volumen nuevo de 16 KiB o 64 KiB.

*Volúmenes con caché SSD* habilitada -- se puede especificar un tamaño de segmento de 4 KiB para volúmenes con caché SSD habilitada. Asegúrese de seleccionar el tamaño de segmento 4 KiB solo para los volúmenes con la función SSD Cache habilitada que controlan operaciones de I/o en bloques pequeños (por ejemplo, tamaños de bloques de I/o de 16 KiB o menos). El rendimiento podría verse afectado si selecciona 4 KiB para el tamaño de segmento en los volúmenes con la función SSD Cache habilitada que controlan operaciones secuenciales de bloques grandes.

*Cantidad de tiempo para cambiar el tamaño del segmento* -- la cantidad de tiempo para cambiar el tamaño del segmento de un volumen depende de estas variables:

*** La carga de I/o desde el host
*** La prioridad de modificación del volumen
*** La cantidad de unidades del grupo de volúmenes
*** La cantidad de canales de unidades
*** La potencia de procesamiento de las controladoras de la cabina de almacenamiento


Si cambia el tamaño de segmento de un volumen, el rendimiento de I/o se ve afectado, pero los datos siguen disponibles.



 a| 
Compatible con la función de seguridad
 a| 
*Sí* aparece junto a "compatible con la función de seguridad" solo si las unidades del pool o grupo de volúmenes son compatibles con la función de seguridad.

Drive Security evita el acceso no autorizado a los datos de una unidad que se quita físicamente de la cabina de almacenamiento. Esta opción solo está disponible si la función Drive Security está habilitada y hay una clave de seguridad configurada para la cabina de almacenamiento.

Un pool o un grupo de volúmenes pueden contener tanto una unidad compatible con la función de seguridad como una que no lo sea, pero todas las unidades deben ser compatibles con la función de seguridad para usar la funcionalidad de cifrado.



 a| 
DA
 a| 
*Sí* aparece junto a "DA" solo si las unidades del pool o grupo de volúmenes admiten Data Assurance (DA).

DA mejora la integridad de los datos en todo el sistema de almacenamiento. DA permite que la cabina de almacenamiento compruebe y corrija los errores que se pueden producir durante la transferencia de datos a través de las controladoras hasta las unidades. El uso DE DA en el volumen nuevo garantiza la detección de cualquier error.



 a| 
Recurso aprovisionado (solo EF300 y EF600)
 a| 
*Sí* aparece junto a "recurso aprovisionado" sólo si las unidades admiten esta opción. El aprovisionamiento de recursos es una función disponible en las cabinas de almacenamiento EF300 y EF600, lo que permite poner en uso los volúmenes de inmediato sin proceso de inicialización en segundo plano.

|===
====
** *Carga de trabajo específica de la aplicación* -- haga clic en *Siguiente* para aceptar los volúmenes y las características recomendados por el sistema para la carga de trabajo seleccionada, o haga clic en *Editar volúmenes* para cambiar, añadir o eliminar los volúmenes y las características recomendados por el sistema para la carga de trabajo seleccionada.
+
.Detalles del campo
[%collapsible]
====
[cols="1a,1a"]
|===
| Campo | Descripción 


 a| 
Nombre del volumen
 a| 
System Manager asigna un nombre predeterminado a un volumen durante la secuencia de creación de volúmenes. Se puede aceptar el nombre predeterminado o se puede proporcionar un nombre más descriptivo que indique el tipo de datos almacenados en el volumen.



 a| 
Capacidad notificada
 a| 
Defina la capacidad del volumen nuevo y las unidades de capacidad que desea usar (MIB, GIB o TIB). Para los volúmenes gruesos, la capacidad mínima es 1 MIB y la capacidad máxima se determina mediante la cantidad y la capacidad de las unidades del pool o del grupo de volúmenes.

Recuerde que la capacidad de almacenamiento también es necesaria para los servicios de copia (imágenes Snapshot, volúmenes Snapshot, copias de volúmenes y reflejos remotos), por lo tanto, no asigne toda la capacidad a los volúmenes estándar.

La capacidad de un pool se asigna en incrementos de 4 GIB o 8 GIB, según el tipo de unidad. Se asigna cualquier capacidad que no sea múltiplo de 4 o 8 GIB, pero no se puede usar. Para asegurarse de que toda la capacidad se pueda usar, especifique la capacidad en incrementos de 4 GIB o 8 GIB. Si hubiese capacidad que no puede usar, la única manera de recuperarla es aumentar la capacidad del volumen.



 a| 
Tipo de volumen
 a| 
Tipo de volumen indica el tipo de volumen que se creó para una carga de trabajo específica de la aplicación.



 a| 
Tamaño de bloque de volumen (solo EF300 y EF600)
 a| 
Muestra los tamaños de bloque que se pueden crear para el volumen:

*** 512 -- 512 bytes
*** 4K -- 4,096 bytes




 a| 
Tamaño del segmento
 a| 
Muestra la configuración del ajuste de tamaño de segmentos, que solo aparece para los volúmenes de un grupo de volúmenes. Se puede cambiar el tamaño del segmento para optimizar el rendimiento.

*Transiciones de tamaño de segmento permitidas* -- System Manager determina las transiciones de tamaño de segmento permitidas. Los tamaños de segmento que no son transiciones adecuadas para el tamaño de segmento actual no están disponibles en la lista desplegable. Las transiciones permitidas, por lo general, son el doble o la mitad del tamaño de segmento actual. Por ejemplo, si el tamaño de segmento del volumen actual es 32 KiB, se permite un tamaño de segmento de volumen nuevo de 16 KiB o 64 KiB.

*Volúmenes con caché SSD* habilitada -- se puede especificar un tamaño de segmento de 4 KiB para volúmenes con caché SSD habilitada. Asegúrese de seleccionar el tamaño de segmento 4 KiB solo para los volúmenes con la función SSD Cache habilitada que controlan operaciones de I/o en bloques pequeños (por ejemplo, tamaños de bloques de I/o de 16 KiB o menos). El rendimiento podría verse afectado si selecciona 4 KiB para el tamaño de segmento en los volúmenes con la función SSD Cache habilitada que controlan operaciones secuenciales de bloques grandes.

*Cantidad de tiempo para cambiar el tamaño del segmento* -- la cantidad de tiempo para cambiar el tamaño del segmento de un volumen depende de estas variables:

*** La carga de I/o desde el host
*** La prioridad de modificación del volumen
*** La cantidad de unidades del grupo de volúmenes
*** La cantidad de canales de unidades
*** La potencia de procesamiento de las controladoras de la cabina de almacenamiento cuando se cambia el tamaño de segmento de un volumen, el rendimiento de I/o se ve afectado, pero los datos siguen disponibles.




 a| 
Compatible con la función de seguridad
 a| 
*Sí* aparece junto a "compatible con la función de seguridad" solo si las unidades del pool o grupo de volúmenes son compatibles con la función de seguridad.

Drive Security evita el acceso no autorizado a los datos de una unidad que se quita físicamente de la cabina de almacenamiento. Esta opción solo está disponible si la función Drive Security está habilitada y hay una clave de seguridad configurada para la cabina de almacenamiento.

Un pool o un grupo de volúmenes pueden contener tanto una unidad compatible con la función de seguridad como una que no lo sea, pero todas las unidades deben ser compatibles con la función de seguridad para usar la funcionalidad de cifrado.



 a| 
DA
 a| 
*Sí* aparece junto a "DA" solo si las unidades del pool o grupo de volúmenes admiten Data Assurance (DA).

DA mejora la integridad de los datos en todo el sistema de almacenamiento. DA permite que la cabina de almacenamiento compruebe y corrija los errores que se pueden producir durante la transferencia de datos a través de las controladoras hasta las unidades. El uso DE DA en el volumen nuevo garantiza la detección de cualquier error.



 a| 
Recurso aprovisionado (solo EF300 y EF600)
 a| 
*Sí* aparece junto a "recurso aprovisionado" sólo si las unidades admiten esta opción. El aprovisionamiento de recursos es una función disponible en las cabinas de almacenamiento EF300 y EF600, lo que permite poner en uso los volúmenes de inmediato sin proceso de inicialización en segundo plano.

|===
====


. Para continuar la secuencia de creación de volúmenes para la aplicación seleccionada, haga clic en *Siguiente* y vaya a. <<Paso 4: Revisar la configuración de volumen>>.




== Paso 4: Revisar la configuración de volumen

Revise un resumen de los volúmenes que pretende crear y realizar los cambios necesarios.

.Pasos
. Revise los volúmenes que desea crear. Haga clic en *Atrás* para realizar cualquier cambio.
. Cuando esté satisfecho con la configuración del volumen, haga clic en *Finalizar*.


.Resultados
System Manager crea los volúmenes nuevos en los pools y grupos de volúmenes seleccionados y, a continuación, muestra los volúmenes nuevos en la tabla todos los volúmenes.

.Después de terminar
* Realice cualquier modificación necesaria del sistema operativo en el host de la aplicación para que las aplicaciones puedan usar el volumen.
* Ejecute la utilidad específica del sistema operativo (disponible de un proveedor de terceros) y, a continuación, ejecute el comando SMcli `-identifyDevices` para correlacionar los nombres de los volúmenes con los nombres de las cabinas de almacenamiento host.
+
SMcli está disponible directamente a través de SANtricity System Manager. Esta versión descargable de SMcli está disponible en las controladoras E4000, EF600, EF600C, EF300, EF300C, E5700, EF570, E2800 y EF280. Para descargar la SMcli dentro del Administrador del sistema SANtricity, seleccione *Configuración* > *sistema* y *Complementos* > *interfaz de línea de comandos* .


