---
permalink: sm-storage/delete-snapshot-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, snapshot, group 
summary: El grupo Snapshot se elimina cuando desea eliminar de forma permanente los datos y quitarlos del sistema. Si se elimina un grupo Snapshot, se reclama la capacidad reservada para volver a utilizarla en el pool o el grupo de volúmenes. 
---
= Eliminar un grupo de instantáneas en SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El grupo Snapshot se elimina cuando desea eliminar de forma permanente los datos y quitarlos del sistema. Si se elimina un grupo Snapshot, se reclama la capacidad reservada para volver a utilizarla en el pool o el grupo de volúmenes.

.Acerca de esta tarea
Cuando se elimina un grupo Snapshot, también se eliminan todas las imágenes Snapshot en el grupo.

.Pasos
. En el panel izquierdo, selecciona menú:Storage[Pools y grupos de volúmenes].
. Haga clic en la pestaña *capacidad reservada*.
. Selecciona el grupo de instantáneas que quieres eliminar y luego haz clic en el icono menu:ellipsis[Delete].
+
Se muestra el cuadro de diálogo Confirmar eliminación de grupo Snapshot.

. Tipo `delete` para confirmar.


.Resultados
System Manager realiza lo siguiente:

* Elimina todas las imágenes Snapshot asociadas con el grupo Snapshot.
* Deshabilita cualquier volumen Snapshot asociado con las imágenes del grupo Snapshot.
* Elimina la capacidad reservada que existe en el grupo Snapshot.

