---
permalink: sm-storage/delete-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, volume 
summary: Por lo general, debe eliminar volúmenes si se crearon con los parámetros o la capacidad equivocados, ya no satisfacen las necesidades de configuración del almacenamiento o son imágenes Snapshot que ya no se necesitan para backup o prueba de aplicaciones. 
---
= Elimine el volumen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Por lo general, debe eliminar volúmenes si se crearon con los parámetros o la capacidad equivocados, ya no satisfacen las necesidades de configuración del almacenamiento o son imágenes Snapshot que ya no se necesitan para backup o prueba de aplicaciones.

Al eliminar un volumen, aumenta la capacidad libre en el pool o el grupo de volúmenes. Puede seleccionar uno o varios volúmenes para eliminarlos.

.Antes de empezar
Asegúrese de que se cumplan las siguientes condiciones en los volúmenes que desea eliminar:

* Existen backups de todos los datos.
* Todas las entradas y las salidas (I/o) están detenidas.
* Todos los dispositivos y los sistemas de archivos están desmontados.


.Acerca de esta tarea
No es posible eliminar un volumen que tenga una de las siguientes condiciones:

* El volumen se está inicializando.
* El volumen se está reconstruyendo.
* El volumen forma parte de un grupo de volúmenes que contiene una unidad que está realizando una operación de copyback.
* El volumen está sometido a una operación de modificación, como un cambio de tamaño de segmento, a menos que el volumen esté ahora en estado con errores.
* El volumen mantiene cualquier tipo de reserva persistente.
* El volumen es un volumen de origen o un volumen objetivo en una operación Copiar volumen con estado Pending, In Progress o con errores.


[CAUTION]
====
Al eliminar un volumen, se produce la pérdida de todos los datos en estos volúmenes.

====
[NOTE]
====
Cuando un volumen supera un tamaño determinado (actualmente 128 TB), la eliminación se lleva a cabo en segundo plano y es posible que el espacio liberado no esté disponible inmediatamente.

====
.Pasos
. Seleccione MENU:Storage[Volumes].
. Haga clic en *Eliminar*.
+
Se muestra el cuadro de diálogo Eliminar volúmenes.

. Seleccione uno o varios volúmenes para eliminar y confirme que desea realizar la operación.
. Haga clic en *Eliminar*.


.Resultados
System Manager realiza lo siguiente:

* Elimina todas las imágenes Snapshot, las programaciones y las Snapshot asociadas.
* Elimina todas las relaciones de mirroring.
* Aumenta la capacidad libre en el pool o el grupo de volúmenes.

