---
permalink: sm-storage/delete-pool-or-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, pool, volume, group 
summary: Es posible eliminar un pool o un grupo de volúmenes para crear más capacidad sin asignar, que puede volver a configurarse para satisfacer necesidades de almacenamiento de aplicaciones. 
---
= Elimine un pool o grupo de volúmenes
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible eliminar un pool o un grupo de volúmenes para crear más capacidad sin asignar, que puede volver a configurarse para satisfacer necesidades de almacenamiento de aplicaciones.

.Antes de empezar
* Previamente, es necesario realizar backup de los datos en todos los volúmenes del pool o grupo de volúmenes.
* Detuvo todas las operaciones de entrada/salida (I/o).
* Desmontó todos los sistemas de archivos de los volúmenes.
* Previamente, deben haberse eliminado todas las relaciones de reflejo en el pool o el grupo de volúmenes.
* Detuvo todas las operaciones de copia de volumen en curso para el pool o el grupo de volúmenes.
* El pool o el grupo de volúmenes no participan en una operación de mirroring asíncrono.
* Las unidades en el grupo de volúmenes no tienen una reserva persistente.


.Pasos
. Seleccione MENU:almacenamiento[Pools y grupos de volúmenes].
. Seleccione un pool o un grupo de volúmenes de la lista.
+
Solo puede seleccionar un pool o un grupo de volúmenes a la vez. Desplácese hacia abajo por la lista para ver pools o grupos de volúmenes adicionales.

. Seleccione menú:tareas no comunes[Eliminar] y confirme.


.Resultados
System Manager realiza lo siguiente:

* Elimina todos los datos en el pool o grupo de volúmenes.
* Elimina todas las unidades en el pool o grupo de volúmenes.
* Desasigna las unidades asociadas, lo que permite reutilizarlas en pools o grupos de volúmenes nuevos o existentes.

