---
permalink: sm-storage/disable-resource-provisioning-on-existing-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, resource provisioning, 
summary: Es posible habilitar o deshabilitar el aprovisionamiento de recursos en un pool o un grupo de volúmenes existente. 
---
= Habilitar o deshabilitar el aprovisionamiento de recursos en grupos de volúmenes y pools existentes en SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para cualquier unidad compatible con DULBE, puede habilitar o deshabilitar el aprovisionamiento de recursos en los volúmenes existentes en un pool o grupo de volúmenes.

El aprovisionamiento de recursos es una función disponible en las matrices de almacenamiento EF80, EF50, EF300/EF300C y EF600/EF600C, que permite que los volúmenes se pongan en uso inmediatamente sin ningún proceso de inicialización en segundo plano. Todos los bloques de unidad asignados al volumen se desasignan (sin mapear), lo que puede mejorar la vida útil del SSD y aumentar el rendimiento máximo de escritura.

De forma predeterminada, el aprovisionamiento de recursos está habilitado en sistemas donde las unidades admiten DULBE. No es necesario habilitar el aprovisionamiento de recursos a menos que se haya deshabilitado anteriormente.

.Antes de empezar
* Debes tener una matriz de almacenamiento EF80, EF50, EF300 o EF600.
* Debe tener grupos de volúmenes SSD o pools, donde todas las unidades admiten la funcionalidad de recuperación de error de bloque lógico no escrito o desasignado (DULBE). De lo contrario, la opción de aprovisionamiento de recursos no está disponible.


.Acerca de esta tarea
Cuando se habilita el aprovisionamiento de recursos para los grupos de volúmenes y pools existentes, se cambian todos los volúmenes en el pool o grupo de volúmenes seleccionado para permitir que se reasignen los bloques. Este proceso podría implicar una operación en segundo plano para garantizar una asignación consistente con la granularidad UNMAP. Esta operación no desasignar ningún espacio. Una vez que se completa la operación en segundo plano, el sistema operativo necesita desasignar los bloques no utilizados para crear espacio libre.

Cuando se deshabilita el aprovisionamiento de recursos para los grupos de volúmenes o pools existentes, una operación en segundo plano reescribe todos los bloques lógicos en cada volumen. Los datos existentes no se modifican. Las escrituras asignarán o aprovisionarán los bloques en las unidades asociadas con el grupo de volúmenes o pool.


NOTE: Para los nuevos grupos de volúmenes y pools, puede habilitar o deshabilitar el aprovisionamiento de recursos en el menú:Configuración[sistema > Configuración adicional > Habilitar/deshabilitar volúmenes aprovisionados con recursos].

.Pasos
. En el panel izquierdo, selecciona menú:Storage[Pools y grupos de volúmenes].
. Haz clic en el icono *elipsis* y selecciona *Habilitar aprovisionamiento de recursos* o *Deshabilitar aprovisionamiento de recursos* para el pool o grupo de volúmenes seleccionado.
. Confirme la operación en el cuadro de diálogo.



NOTE: *Si vuelve a habilitar DULBE* -- después de que finalice la operación en segundo plano, es posible que deba reiniciar el host para que detecte los cambios de configuración DULBE y, a continuación, volver a montar todos los sistemas de archivos.
