---
permalink: sm-storage/faq-pools-volume-groups.html 
sidebar: sidebar 
keywords:  
summary: Estas preguntas frecuentes pueden ser de ayuda si solo está buscando una respuesta rápida a una pregunta. 
---
= Preguntas frecuentes sobre grupos de volúmenes y pools para SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Estas preguntas frecuentes pueden ser de ayuda si solo está buscando una respuesta rápida a una pregunta.



== ¿Qué es un grupo de volúmenes?

Un grupo de volúmenes es un contenedor para volúmenes con características compartidas. Un grupo de volúmenes tiene una capacidad definida y un nivel de RAID. Se puede usar un grupo de volúmenes para crear uno o más volúmenes a los que se pueda acceder mediante un host. (Los volúmenes se crean a partir de un pool o un grupo de volúmenes).



== ¿Qué es un pool?

Un pool es un conjunto de unidades que se agrupan en forma lógica. Se puede usar un pool para crear uno o más volúmenes accesibles para un host. (Se crean volúmenes desde un pool o un grupo de volúmenes).

Los pools pueden eliminar la necesidad de que los administradores supervisen el uso de cada host para determinar cuándo es posible que se queden sin espacio de almacenamiento y evitar la interrupción del servicio convencional para ajustar el tamaño del disco. Cuando un pool se está por agotar, se pueden añadir unidades adicionales al pool sin producir interrupciones, y el aumento de la capacidad es transparente para el host.

Con los pools, los datos se redistribuyen automáticamente para mantener el equilibrio. Al distribuir la información de paridad y la capacidad de reserva en el pool, cada unidad del pool se puede usar para recompilar una unidad con error. Este enfoque no utiliza unidades de repuesto dedicadas, sino que reserva capacidad de conservación (repuesto) en el pool. En caso de que falle una unidad, los segmentos de otras unidades se leen para volver a crear los datos. Posteriormente, se selecciona una unidad nueva para escribir cada segmento que estaba en la unidad con error con el fin de mantener la distribución de los datos en las unidades.



== ¿Qué es la capacidad reservada?

La capacidad reservada es la capacidad físicamente asignada para almacenar datos de objetos de servicio de copia, como imágenes Snapshot volúmenes miembro del grupo de coherencia y volúmenes de parejas reflejadas.

El volumen de capacidad reservada asociado con una operación de servicio de copia reside en un pool o grupo de volúmenes. Se crea la capacidad reservada ya sea desde un pool o grupo de volúmenes.



== ¿Qué es la seguridad FDE/FIPS?

La seguridad FDE/FIPS hace referencia a unidades compatibles con la función de seguridad que cifran datos durante las escrituras y los descifran durante las lecturas mediante una clave de cifrado única. Estas unidades compatibles con la función de seguridad evitan el acceso no autorizado a los datos en una unidad que se quita físicamente de la cabina de almacenamiento.

Las unidades compatibles con la función de seguridad pueden ser unidades de cifrado de disco completo (FDE) o de estándar de procesamiento de información federal (FIPS). Las unidades FIPS se sometieron a pruebas de certificación.

[NOTE]
====
Para los volúmenes que requieren compatibilidad FIPS, se deben utilizar solo unidades FIPS. Si se mezclan unidades FIPS y FDE en un grupo de volúmenes o un pool, todas las unidades se tratarán como unidades FDE. Además, no se puede agregar una unidad FDE ni utilizarse como reserva en un pool o grupo de volúmenes FIPS.

====


== ¿Qué es una comprobación de redundancia?

Una comprobación de redundancia determina si los datos de un volumen en un pool o grupo de volúmenes son consistentes. Los datos de redundancia se utilizan para reconstruir información rápidamente en una unidad de reemplazo si falla una de las unidades de un pool o grupo de volúmenes.

Es posible realizar esta comprobación solo en un pool o grupo de volúmenes a la vez. Una comprobación de redundancia de un volumen realiza las acciones siguientes:

* Escanea los bloques de datos en un volumen RAID 3, un volumen RAID 5 o un volumen RAID 6 y, a continuación, comprueba la información de redundancia de cada bloque. (RAID 3 solo puede asignarse a grupos de volúmenes con interfaz de línea de comandos.)
* Compara los bloques de datos en unidades reflejadas RAID 1.
* Devuelve errores de redundancia si el firmware de la controladora determina que los datos no son consistentes.


[NOTE]
====
Si se ejecuta de inmediato una comprobación de redundancia en el mismo pool o grupo de volúmenes, se puede generar un error. Para evitar este problema, espere de uno a dos minutos antes de ejecutar otra comprobación de redundancia en el mismo pool o grupo de volúmenes.

====


== ¿Cuáles son las diferencias entre los pools y los grupos de volúmenes?

Un pool es similar a un grupo de volúmenes, con las siguientes diferencias.

* Los datos de un pool se almacenan al azar en todas las unidades del pool, a diferencia de los datos de un grupo de volúmenes, que se almacenan en el mismo conjunto de unidades.
* Un pool tiene menos degradación del rendimiento cuando falla una unidad, y demora menos tiempo para reconstruirse.
* Un pool tiene capacidad de conservación incorporada; por consiguiente, no requiere unidades de repuesto dedicadas.
* Un pool permite agrupar un gran número de unidades.
* Un pool no necesita un nivel de RAID específico.




== ¿Por qué debería configurar manualmente un pool?

Los ejemplos siguientes describen por qué se configuraría un pool de forma manual.

* Si tiene varias aplicaciones en la cabina de almacenamiento y no quiere que compitan por los mismos recursos de la unidad, puede considerar la creación manual de un pool más pequeño para una o varias de las aplicaciones.
+
Puede asignar solo uno o dos volúmenes en lugar de asignar la carga de trabajo a un pool más grande que tiene varios volúmenes en los cuales se pueden distribuir los datos. La creación manual de un pool individual dedicado a la carga de trabajo de una aplicación específica puede permitir que las operaciones de cabina de almacenamiento sean más rápidas y con menos contención.

+
Para crear manualmente un pool: Seleccione *almacenamiento* y, a continuación, seleccione *Pools y grupos de volúmenes*. En la pestaña toda la capacidad, haga clic en menu:Create[Pool].

* Si hay varios pools del mismo tipo de unidad, se muestra un mensaje que indica que System Manager no puede recomendar automáticamente las unidades para un pool. Sin embargo, es posible añadir manualmente las unidades a un pool existente.
+
Para añadir unidades manualmente a un pool existente: En la página Pools y grupos de volúmenes, seleccione el pool y haga clic en *Añadir capacidad*.





== ¿Por qué son importantes las alertas de capacidad?

Las alertas de capacidad indican cuándo añadir unidades a un pool. Un pool necesita capacidad libre suficiente para realizar correctamente las operaciones de la cabina de almacenamiento. Es posible evitar interrupciones en estas operaciones si se configura SANtricity System Manager para que envíe alertas cuando la capacidad libre de un pool alcanza o supera un porcentaje especificado.

Este porcentaje se establece cuando se crea un pool mediante la opción *Configuración automática del pool* o la opción *Crear pool*. Si elige la opción automática, la configuración predeterminada determina automáticamente cuándo recibirá notificaciones de alerta. Si elige la opción de creación manual del pool, puede determinar la configuración de notificaciones de alerta, o bien, si lo prefiere, puede aceptar los ajustes predeterminados. Puede modificar esta configuración posteriormente en MENU:Settings[Alerts].

[NOTE]
====
Cuando la capacidad libre en el pool alcance el porcentaje especificado, se enviará una notificación de alerta con el método especificado en la configuración de alertas.

====


== ¿Por qué no se puede aumentar la capacidad de conservación?

Si se crearon volúmenes en toda la capacidad utilizable disponible, es posible que no se pueda aumentar la capacidad de conservación.

La capacidad de conservación es la cantidad de capacidad (número de unidades) reservada en un pool para dar soporte a fallos de unidad potenciales. Cuando se crea un pool, el sistema reserva automáticamente una cantidad predeterminada de capacidad de conservación según el número de unidades del pool. Si creó volúmenes en toda la capacidad utilizable disponible, no puede aumentar la capacidad de conservación sin agregar capacidad al pool, ya sea sumando unidades o eliminando volúmenes.

Puede cambiar la capacidad de conservación de *Pools y grupos de volúmenes*. Seleccione el pool que desea editar. Haga clic en *Ver/editar configuración* y, a continuación, seleccione la ficha *Configuración*.

[NOTE]
====
La capacidad de conservación se especifica como el número de unidades, a pesar de que la capacidad de conservación real se distribuya en las unidades del pool.

====


== ¿Existe un límite para la cantidad de unidades que pueden eliminarse de un pool?

SANtricity System Manager establece límites en cuanto a la cantidad de unidades que pueden eliminarse de un pool.

* No se puede reducir la cantidad de unidades en un pool a menos de 11.
* No se pueden eliminar unidades si no hay suficiente capacidad libre en el pool para contener los datos de las unidades eliminadas cuando esos datos se redistribuyen a las unidades restantes del pool.
* Es posible eliminar un máximo de 60 unidades al mismo tiempo. Si selecciona más de 60, se deshabilitará la opción Quitar unidades. Si necesita eliminar más de 60 unidades, repita la operación Quitar unidades.




== ¿Qué tipos de medios son compatibles para una unidad?

Los siguientes tipos de medios son compatibles: Unidad de disco duro (HDD) y disco de estado sólido (SSD).



== ¿Por qué no se muestran algunas unidades?

En el cuadro de diálogo Añadir capacidad, no todas las unidades se encuentran disponibles para añadir capacidad a un pool o grupo de volúmenes existente.

Las unidades no serán elegibles por cualquiera de los motivos siguientes:

* Una unidad debe estar sin asignar y no debe tener la función de seguridad habilitada. Las unidades que son parte de otro pool, de otro grupo de volúmenes o que están configuradas como pieza de repuesto no son elegibles. Si una unidad está sin asignar, pero tiene la función de seguridad habilitada, se debe eliminar manualmente esa unidad para que sea elegible.
* Una unidad que se encuentra en un estado distinto a Optimal no es elegible.
* Si una unidad tiene muy poca capacidad, no es elegible.
* El tipo de medios de la unidad debe coincidir dentro de un pool o grupo de volúmenes. No puede mezclar lo siguiente:
+
** Unidades de disco duro (HDD) con discos de estado sólido (SSD)
** NVMe con unidades SAS
** Unidades con tamaños de bloques de volúmenes de 512 bytes y 4 KiB


* Si todas las unidades de un pool o un grupo de volúmenes son compatibles con la función de seguridad, las unidades no compatibles con la función de seguridad no se enumeran.
* Si un pool o grupo de volúmenes contiene todas unidades compatibles con el estándar de procesamiento de información federal (FIPS), las unidades no compatibles con FIPS no se enumeran.
* Si un pool o grupo de volúmenes contiene todas unidades compatibles con la función Garantía de datos (DA) y al menos un volumen del pool o grupo de volúmenes tiene habilitada la función DA, una unidad que no sea compatible con DA no es elegible, por lo que no puede añadirse a ese pool o grupo de volúmenes. Sin embargo, si ningún volumen tiene la función DA habilitada en el pool o grupo de volúmenes, una unidad que no sea compatible con LA función DA puede añadirse a ese pool o grupo de volúmenes. Si decide combinar estas unidades, tenga en cuenta que no podrá crear ningún volumen con la función DA habilitada.


[NOTE]
====
Es posible aumentar la capacidad de la cabina de almacenamiento con la adición de unidades nuevas o la eliminación de pools o grupos de volúmenes.

====


== ¿Cómo se mantiene la protección contra pérdida de bandeja/cajón?

Para mantener la protección contra pérdida de bandeja/cajón para un pool o un grupo de volúmenes, use los criterios especificados en la siguiente tabla.

[cols="1a,1a,1a"]
|===
| Nivel | Criterios para la protección contra pérdida de bandeja/cajón | Cantidad mínima de bandejas/cajones requeridos 


 a| 
Piscina
 a| 
Para las bandejas, el pool no debe contener más de dos unidades en una sola bandeja.

Para los cajones, el pool debe incluir la misma cantidad de unidades en cada uno de ellos.
 a| 
6 para bandejas

5 para cajones



 a| 
RAID 6
 a| 
El grupo de volúmenes no contiene más de dos unidades por bandeja o cajón.
 a| 
3



 a| 
RAID 3 o RAID 5
 a| 
Cada unidad del grupo de volúmenes está ubicada en una bandeja o un cajón por separado.
 a| 
3



 a| 
RAID 1
 a| 
Cada unidad de una pareja reflejada debe ubicarse en una bandeja o un cajón por separado.
 a| 
2



 a| 
RAID 0
 a| 
No se puede lograr la protección contra pérdida de bandeja/cajón.
 a| 
No aplicable

|===
[NOTE]
====
La protección contra pérdida de bandeja/cajón no se mantiene si una unidad ya tuvo fallos en el pool o el grupo de volúmenes. En este caso, la pérdida de acceso a la bandeja o el cajón de unidades y, en consecuencia, a otra unidad en el pool o el grupo de volúmenes provoca la pérdida de datos.

====


== ¿Cuál es el posicionamiento de unidad óptimo para pools y grupos de volúmenes?

Al crear pools y grupos de volúmenes, asegúrese de equilibrar la selección de unidades entre las ranuras de unidades superior e inferior.

Para las controladoras EF600 y EF300, las ranuras de unidad 0-11 están conectadas a un puente PCI, mientras que las ranuras 12-23 están conectadas a un puente PCI diferente. Para obtener un rendimiento óptimo, se debe equilibrar la selección de unidades para incluir una cantidad prácticamente igual de unidades en las ranuras superior e inferior. Este posicionamiento garantiza que sus volúmenes no alcanzan el límite de ancho de banda antes de lo necesario.



== ¿Cuál es el nivel de RAID óptimo para cada aplicación?

Para maximizar el rendimiento de un grupo de volúmenes, se debe seleccionar el nivel de RAID adecuado. Es posible determinar el nivel de RAID apropiado si se conocen los porcentajes de escritura y lectura de las aplicaciones que acceden al grupo de volúmenes. Utilice la página rendimiento para obtener estos porcentajes.



=== Niveles de RAID y rendimiento de la aplicación

RAID se basa en una serie de configuraciones, denominadas _niveles_, para determinar cómo los datos de redundancia y usuario se escriben en las unidades y se recuperan de ellas. Cada nivel de RAID proporciona diferentes funciones de rendimiento. Las aplicaciones con un porcentaje alto de lectura tendrán un buen rendimiento con volúmenes RAID 5 o RAID 6 debido al rendimiento de lectura destacado de las configuraciones RAID 5 y RAID 6.

Las aplicaciones con un porcentaje bajo de lectura (de escritura intensiva) no rinden tan bien con volúmenes RAID 5 o RAID 6. El rendimiento degradado resulta de la forma en que una controladora escribe los datos y los datos de redundancia en las unidades de un grupo de volúmenes RAID 5 o RAID 6.

Seleccione un nivel de RAID según la información siguiente.

*RAID 0*

* *Descripción*
+
** No redundante, modo de segmentación.


* *Cómo funciona*
+
** RAID 0 segmenta los datos en todas las unidades del grupo de volúmenes.


* *Funciones de protección de datos*
+
** RAID 0 no se recomienda para necesidades de alta disponibilidad. RAID 0 es más adecuado para datos no cruciales.
** Si una unidad única falla en el grupo de volúmenes, todos los volúmenes asociados fallarán y se perderán todos los datos.


* *Requisitos del número de la unidad*
+
** Se requiere un mínimo de una unidad para el nivel de RAID 0.
** Los grupos de volúmenes de RAID 0 pueden tener más de 30 unidades.
** Es posible crear un grupo de volúmenes que incluya todas las unidades en la cabina de almacenamiento.




*RAID 1 o RAID 10*

* *Descripción*
+
** Modo de segmentación/reflejo.


* *Cómo funciona*
+
** RAID 1 utiliza las operaciones de mirroring de discos para escribir datos en dos discos duplicados en simultáneo.
** RAID 10 utiliza la segmentación de unidades para segmentar los datos de un conjunto de parejas de unidades reflejadas.


* *Funciones de protección de datos*
+
** RAID 1 y RAID 10 ofrecen alto rendimiento y la mejor disponibilidad de datos.
** RAID 1 y RAID 10 utilizan las operaciones de mirroring de unidades para realizar una copia exacta de una unidad en otra.
** Si una de las unidades de una pareja de unidades falla, la cabina de almacenamiento puede cambiar instantáneamente a la otra sin perder datos o servicios.
** Un fallo de unidad única provoca el estado degradado de los volúmenes asociados. La unidad reflejo permite acceder a los datos.
** Un fallo de la pareja de unidades en un grupo de volúmenes provoca el fallo de todos los volúmenes asociados, y podría ocurrir una pérdida de datos.


* *Requisitos del número de la unidad*
+
** Se requiere un mínimo de dos unidades para RAID 1: Una unidad para los datos de usuario y una unidad para los datos reflejados.
** Si se seleccionan cuatro o más unidades, RAID 10 se configura automáticamente en el grupo de volúmenes: Dos unidades para los datos de usuario y dos unidades para los datos reflejados.
** El grupo de volúmenes debe tener un número par de unidades. Si no se cuenta con un número par de unidades y quedan algunas sin asignar, vaya a *Pools y grupos de volúmenes* para añadir unidades adicionales al grupo de volúmenes y vuelva a intentar la operación.
** Los grupos de volúmenes de RAID 1 y RAID 10 pueden tener más de 30 unidades. Se puede crear un grupo de volúmenes que incluya todas las unidades de la cabina de almacenamiento.




*RAID 5*

* *Descripción*
+
** Modo de I/o elevado.


* *Cómo funciona*
+
** Los datos de usuario y la información redundante (paridad) se segmentan en las unidades.
** Se utiliza la capacidad equivalente de una unidad para la información redundante.


* *Funciones de protección de datos*
+
** Si una unidad única falla en un grupo de volúmenes RAID 5, todos los volúmenes asociados se degradan. La información redundante permite que aún pueda accederse a los datos.
** Si dos o más unidades fallan en un grupo de volúmenes RAID 5, todos los volúmenes asociados fallarán y se perderán todos los datos.


* *Requisitos del número de la unidad*
+
** Se debe contar con un mínimo de tres unidades en el grupo de volúmenes.
** Por lo general, el grupo de volúmenes tiene un límite máximo de 30 unidades.




*RAID 6*

* *Descripción*
+
** Modo de I/o elevado.


* *Cómo funciona*
+
** Los datos de usuario y la información redundante (doble paridad) se segmentan en las unidades.
** Se utiliza la capacidad equivalente de dos unidades para la información redundante.


* *Funciones de protección de datos*
+
** Si una o dos unidades fallan en un grupo de volúmenes RAID 6, todos los volúmenes asociados se degradarán, pero la información redundante permitirá que aún pueda accederse a los datos.
** Si tres o más unidades fallan en un grupo de volúmenes RAID 6, todos los volúmenes asociados fallarán y se perderán todos los datos.


* *Requisitos del número de la unidad*
+
** Se debe contar con un mínimo de cinco unidades en el grupo de volúmenes.
** Por lo general, el grupo de volúmenes tiene un límite máximo de 30 unidades.




[NOTE]
====
No es posible cambiar el nivel de RAID de un pool. La interfaz de usuario configura automáticamente los pools como RAID 6.

====


=== Niveles de RAID y protección de datos

RAID 1, RAID 5 y RAID 6 escriben los datos de redundancia en los medios de la unidad para la tolerancia a fallos. Los datos de redundancia pueden ser una copia de los datos (reflejados) o un código de corrección de error derivado de los datos. Es posible utilizar los datos de redundancia para reconstruir información rápidamente en una unidad de reemplazo si se produce un error en una unidad.

Se configura un nivel de RAID único en un grupo de volúmenes único. Todos los datos de redundancia de ese grupo de volúmenes se almacenan en el grupo de volúmenes. La capacidad del grupo de volúmenes es la capacidad agregada de las unidades miembro menos la capacidad reservada para los datos de redundancia. La cantidad de capacidad necesaria para la redundancia depende del nivel de RAID utilizado.



== ¿Qué es la garantía de datos?

La garantía de datos (DA) implementa el estándar de información de protección (PI) T10, con el cual se comprueban y corrigen los errores que se pueden producir durante la transferencia de datos a través de la ruta de I/o con el fin de aumentar la integridad de los datos.

El uso típico de la función Garantía de datos es revisar la porción de la ruta de I/o entre las controladoras y las unidades. Las funcionalidades DE DA se presentan a nivel del pool y grupo de volúmenes.

Si esta función está habilitada, la cabina de almacenamiento añade códigos de comprobación de errores (también conocidos como comprobaciones de redundancia cíclicas o CRC) a cada bloque de datos del volumen. Una vez movido un bloque de datos, la cabina de almacenamiento utiliza estos códigos de CRC para determinar si se produjeron errores durante la transmisión. Los datos posiblemente dañados no se escriben en el disco ni se vuelven a transferir al host. Si desea usar la función DA, seleccione un pool o grupo de volúmenes compatible con DA al crear un volumen nuevo (busque la opción "Sí" junto a "DA" en la tabla de candidatos de pools y grupos de volúmenes).

Asegúrese de asignar estos volúmenes con la función DA habilitada a un host que utilice una interfaz de I/o compatible con DA. Las interfaces de I/o compatibles con DA son Fibre Channel, SAS, iSCSI over TCP/IP, NVMe/FC, NVMe/IB, NVME/roce e Iser over InfiniBand (extensiones iSCSI para RDMA/IB). SRP over InfiniBand no es compatible con DA.



== ¿Qué significa ser compatible con la función de seguridad (Drive Security)?

Drive Security es una función que evita el acceso no autorizado a datos almacenados en unidades con la función de seguridad habilitada cuando la unidad se quita de la cabina de almacenamiento. Estas unidades pueden ser unidades de cifrado de disco completo (FDE) o de estándar de procesamiento de información federal (FIPS).



== ¿Qué debo saber acerca del aumento de la capacidad reservada?

Por lo general, se debe aumentar la capacidad cuando se recibe una advertencia que indica que la capacidad reservada corre el peligro de completarse. Es posible aumentar la capacidad reservada únicamente en incrementos de 8 GIB.

* Debe tener suficiente capacidad libre en el pool o el grupo de volúmenes para poder realizar una expansión si es necesario.
+
Si no hay capacidad libre en ningún pool o grupo de volúmenes, es posible añadir capacidad sin asignar en forma de unidades no utilizadas a un pool o un grupo de volúmenes.

* El volumen en el pool o el grupo de volúmenes debe tener el estado óptima y no debe estar en ningún estado de modificación.
* Debe existir capacidad libre en el pool o grupo de volúmenes que desea usar para aumentar la capacidad.
* No es posible aumentar la capacidad reservada para un volumen Snapshot de solo lectura. Solo los volúmenes Snapshot que son de lectura y escritura requieren capacidad reservada.


Para las operaciones Snapshot, la capacidad reservada generalmente es el 40 % del volumen base. Para las operaciones de mirroring asíncrono, generalmente es el 20 % del volumen base. Use un porcentaje más alto si cree que el volumen base se someterá a muchos cambios, o si la expectativa de duración estimada de una operación de servicio de copia de un objeto de almacenamiento será muy larga.



== ¿Por qué no puedo elegir otra cantidad para disminuir?

Es posible reducir la capacidad reservada solo en la cantidad que se utilizó para aumentarla. La capacidad reservada de los volúmenes miembro puede quitarse solo en el orden inverso al que se añadió.

No es posible reducir la capacidad reservada de un objeto de almacenamiento si se da alguna de las condiciones siguientes:

* Si el objeto de almacenamiento es un volumen de pareja reflejada.
* Si el objeto de almacenamiento contiene solo un volumen para la capacidad reservada. El objeto de almacenamiento debe contener al menos dos volúmenes para la capacidad reservada.
* Si el objeto de almacenamiento es un volumen Snapshot deshabilitado.
* Si el objeto de almacenamiento contiene una o más imágenes Snapshot asociadas.


Solo se pueden quitar volúmenes de capacidad reservada en el orden inverso al que se añadieron.

No es posible reducir la capacidad reservada de un volumen Snapshot de solo lectura, ya que no tiene ninguna capacidad reservada asociada. Solo los volúmenes Snapshot que son de lectura y escritura requieren capacidad reservada.



== ¿Por qué necesito capacidad reservada para cada volumen miembro?

Cada volumen miembro de un grupo de coherencia Snapshot debe tener su propia capacidad reservada para guardar cualquier modificación que realice la aplicación host en el volumen base sin afectar a la imagen Snapshot de referencia del grupo de coherencia. La capacidad reservada proporciona a la aplicación host el acceso de escritura a una copia de los datos contenidos en el volumen miembro designado como de lectura/escritura.

Los hosts no tienen acceso de lectura o escritura de forma directa a una imagen Snapshot del grupo de coherencia. En cambio, la imagen Snapshot se utiliza para guardar solo los datos capturados desde el volumen base.

Durante la creación de un volumen Snapshot de grupo de coherencia designado como de lectura/escritura, System Manager crea una capacidad reservada para cada volumen miembro del grupo de coherencia. Esta capacidad reservada proporciona a la aplicación host el acceso de escritura a una copia de los datos contenidos en la imagen Snapshot del grupo de coherencia.



== ¿Cómo se visualizan y se interpretan todas las estadísticas de caché SSD?

Es posible visualizar estadísticas nominales y detalladas para la caché SSD. Las estadísticas nominales son un subconjunto de las estadísticas detalladas.

Las estadísticas detalladas se pueden visualizar solo cuando se exportan todas las estadísticas de SSD a un `.csv` archivo. Al revisar e interpretar las estadísticas, tenga en cuenta que algunas interpretaciones provienen del análisis de una combinación de estadísticas.



=== Estadísticas nominales

Para ver las estadísticas de caché SSD, seleccione MENU:almacenamiento[Pools y grupos de volúmenes]. Seleccione la caché SSD sobre la cual desea ver estadísticas y, a continuación, seleccione MENU:más[Ver estadísticas]. Las estadísticas nominales se muestran en el cuadro de diálogo Ver estadísticas de la caché SSD.

En la siguiente lista, se incluyen estadísticas nominales, que son un subconjunto de las estadísticas detalladas.

[cols="25h,~"]
|===
| Estadística nominal | Descripción 


 a| 
Lecturas/escrituras
 a| 
La cantidad total de lecturas de host o escrituras de host en los volúmenes con la función de caché SSD habilitada. Compare las lecturas en relación con las escrituras. Las lecturas deben ser mayores que las escrituras para un funcionamiento eficaz de la caché SSD. Cuando mayor sea la proporción de lecturas con respecto a las escrituras, mejor será el funcionamiento de la caché.



 a| 
Aciertos en caché
 a| 
El número de aciertos en caché.



 a| 
Aciertos en caché (%)
 a| 
Se deriva de los aciertos en caché/(lecturas + escrituras). El porcentaje de aciertos en caché debe ser mayor que 50 % para un funcionamiento eficaz de la caché SSD. Una cifra pequeña puede indicar varias cuestiones:

* El ratio de lecturas respecto de escrituras es demasiado pequeño
* Las lecturas no se repiten
* La capacidad de la caché es demasiado baja




 a| 
Asignación en caché (%)
 a| 
La cantidad de almacenamiento de la caché SSD que se asigna, expresada como un porcentaje del almacenamiento de la caché SSD que está disponible para esta controladora. Derivado de bytes asignados/bytes disponibles. El porcentaje de asignación de la caché normalmente se muestra como 100 %. Si este número es menor que 100 %, significa que la caché no se preparó o que la capacidad de la caché SSD es mayor que la de todos los datos a los que se intenta acceder. En el último caso, una menor capacidad de caché SSD podría ofrecer el mismo nivel de rendimiento. Es preciso tener en cuenta que esto no indica que los datos en caché se colocaron en la caché SSD; simplemente es un paso de preparación antes de que los datos puedan colocarse en la caché SSD.



 a| 
Uso de caché (%)
 a| 
La cantidad de almacenamiento en la caché SSD que contiene datos de volúmenes habilitados, expresado como un porcentaje del almacenamiento de la caché SSD que se asigna. Este valor representa la utilización o la densidad de la caché SSD derivada de los bytes de datos de usuario/bytes asignados. El porcentaje de utilización de la caché normalmente es inferior al 100 %, puede que sea mucho menor. Esta cifra muestra el porcentaje de capacidad de la caché SSD que se llena con datos de caché. Esta cifra es menor que 100 %, ya que cada unidad de asignación de caché SSD, el bloque de caché SSD, se divide en unidades más pequeñas denominadas subbloques, que se llenan de manera bastante independiente. Por lo general, una cifra más alta es mejor, pero las mejoras de rendimiento pueden ser significativas incluso con una cifra menor.

|===


=== Estadística detallada

Las estadísticas detalladas consisten en las estadísticas normales más las estadísticas adicionales. Estas estadísticas adicionales se guardan junto con las estadísticas nominales; pero, a diferencia de las estadísticas nominales, no se muestran en el cuadro de diálogo Ver estadísticas de la caché SSD. Es posible ver las estadísticas detalladas solo después de exportar las estadísticas a `.csv` archivo.

Al ver la `.csv` file, tenga en cuenta que las estadísticas detalladas se enumeran después de las estadísticas nominales:

[cols="25h,~"]
|===
| Estadística detallada | Descripción 


 a| 
Bloques de lectura
 a| 
La cantidad de bloques en lecturas de host.



 a| 
Bloques de escritura
 a| 
La cantidad de bloques en escrituras de host.



 a| 
Bloques de acierto completo
 a| 
La cantidad de bloques en aciertos en caché. Los bloques de acierto completo indican la cantidad de bloques que se leyeron completamente de la caché SSD. La caché SSD solo ofrece beneficios en cuanto al rendimiento de las operaciones que son aciertos en caché completos.



 a| 
Aciertos parciales
 a| 
La cantidad de lecturas de host, donde al menos un bloque, pero no todos los bloques, se encontraban en la caché SSD. Un acierto parcial es una caché SSD *omisión* donde las lecturas se satisficieron desde el volumen base.



 a| 
Aciertos parciales - bloques
 a| 
La cantidad de bloques en aciertos parciales. Los aciertos en caché parciales y los bloques de acierto en caché resultan de una operación que solo tiene una porción de sus datos en la caché SSD. En este caso, la operación debe obtener los datos del volumen de la unidad de disco duro (HDD) almacenado en caché. La caché SSD no ofrece beneficios de rendimiento para este tipo de acierto. Si el número de bloques de acierto en caché parcial es mayor que los bloques de acierto en caché completo, se podría mejorar el rendimiento con un tipo de característica de I/o diferente (sistema de archivos, base de datos o servidor web). Se espera que haya una cifra mayor de aciertos y omisiones en caché en una comparación con los aciertos en caché cuando se está preparando la caché SSD.



 a| 
Pérdidas
 a| 
La cantidad de lecturas de host, donde ninguno de los bloques se encontraba en la caché SSD. Una omisión de caché SSD se produce cuando las lecturas se satisficieron desde el volumen base. Se espera que haya una cifra mayor de aciertos y omisiones en caché en una comparación con los aciertos en caché cuando se está preparando la caché SSD.



 a| 
Pérdidas - bloques
 a| 
La cantidad de bloques en omisiones.



 a| 
Completar acciones (Lecturas de host)
 a| 
La cantidad de lecturas de host donde se copiaron datos desde el volumen base hacia la caché SSD.



 a| 
Completar acciones(Lecturas de host) - bloques
 a| 
La cantidad de bloques en acciones de llenado (lecturas de host).



 a| 
Completar acciones (Escrituras de host)
 a| 
La cantidad de escrituras de host donde se copiaron datos desde el volumen base hacia la caché SSD. El número de completar acciones (Escrituras de host) puede ser cero para la opción de la configuración de caché que no llena la caché debido a una operación de I/o de escritura.



 a| 
Completar acciones(Escrituras de host) - bloques
 a| 
La cantidad de bloques en acciones de llenado (escrituras de host).



 a| 
Invalidar acciones
 a| 
La cantidad de veces que se invalidaron o se eliminaron datos de la caché SSD. Se realiza una operación de invalidación de caché para cada solicitud de escritura de host, cada solicitud de lectura de host con acceso forzado a la unidad (FUA), cada solicitud de verificación, y también en otras circunstancias.



 a| 
Reciclar acciones
 a| 
La cantidad de veces que el bloque de caché SSD se reutilizó para otro volumen base y/u otro rango de direcciones de bloque lógico (LBA). Para una operación efectiva de la caché, la cantidad de reciclados debe ser reducida comparada con la cifra sumada de operaciones de lectura y escritura. Si la cantidad de acciones de reciclado está cerca de la cifra sumada de lecturas y escrituras, se está produciendo una hiperpaginación de la caché SSD. Es necesario aumentar la capacidad de caché o la carga de trabajo no es favorable para usar con la caché SSD.



 a| 
Bytes disponibles
 a| 
La cantidad de bytes disponibles en la caché SSD que puede utilizar esta controladora.



 a| 
Bytes asignados
 a| 
La cantidad de bytes que asignó esta controladora desde la caché SSD. Los bytes asignados de la caché SSD pueden estar vacíos o contener datos de volúmenes base.



 a| 
Bytes de datos de usuario
 a| 
La cantidad de bytes asignados en la caché SSD que contienen datos de volúmenes base. Los bytes disponibles, los bytes asignados y los bytes de datos de usuario se usan para computar el porcentaje de asignación de caché y el porcentaje de utilización de caché.

|===


== ¿Qué es la capacidad de optimización para pools?

Las unidades SSD tendrán una mayor vida útil y mejor rendimiento de escritura máximo cuando una parte de su capacidad no está asignada.

Para las unidades asociadas con un pool, la capacidad sin asignar consta de la capacidad de conservación de un pool, la capacidad libre (capacidad que no utilizan los volúmenes) y una parte de la capacidad utilizable se diferencia como capacidad de optimización adicional. La capacidad de optimización adicional garantiza un nivel mínimo de capacidad de optimización mediante la reducción de la capacidad utilizable, y, como tal, no está disponible para la creación de volúmenes.

Cuando se crea un pool, se genera una capacidad de optimización recomendada que ofrece un equilibrio del rendimiento, la vida útil de la unidad y la capacidad disponible. El control deslizante capacidad de optimización adicional ubicado en el cuadro de diálogo Configuración del pool permite ajustar la capacidad de optimización del pool. El ajuste del control deslizante proporciona un mejor rendimiento y una mayor vida útil de la unidad cuando se descuenta la capacidad disponible, o bien capacidad disponible adicional, costa del rendimiento y la vida útil de la unidad.

[NOTE]
====
El control deslizante de capacidad de optimización adicional solo está disponible para los sistemas de almacenamiento EF600 y EF300.

====


== ¿Qué es la capacidad de optimización de los grupos de volúmenes?

Las unidades SSD tendrán una mayor vida útil y mejor rendimiento de escritura máximo cuando una parte de su capacidad no está asignada.

Para las unidades asociadas con un grupo de volúmenes, la capacidad sin asignar consta de la capacidad libre de un grupo de volúmenes (capacidad que no usan los volúmenes) y una parte del conjunto de capacidad utilizable como capacidad de optimización. La capacidad de optimización adicional garantiza un nivel mínimo de capacidad de optimización mediante la reducción de la capacidad utilizable, y, como tal, no está disponible para la creación de volúmenes.

Cuando se crea un grupo de volúmenes, se genera una capacidad de optimización recomendada que ofrece un equilibrio entre rendimiento, vida útil de la unidad y capacidad disponible. El control deslizante capacidad de optimización adicional en el cuadro de diálogo Configuración del grupo de volúmenes permite ajustar la capacidad de optimización de un grupo de volúmenes. El ajuste del control deslizante proporciona un mejor rendimiento y una mayor vida útil de la unidad cuando se descuenta la capacidad disponible, o bien capacidad disponible adicional, costa del rendimiento y la vida útil de la unidad.

[NOTE]
====
El control deslizante de capacidad de optimización adicional solo está disponible para los sistemas de almacenamiento EF600 y EF300.

====


== ¿Qué permite el aprovisionamiento de recursos?

El aprovisionamiento de recursos es una función disponible en las cabinas de almacenamiento EF300 y EF600, lo que permite poner en uso los volúmenes de inmediato sin proceso de inicialización en segundo plano.

Un volumen aprovisionado por recursos es un volumen grueso de un grupo de volúmenes SSD o pool, donde se asigna capacidad de la unidad (asignada al volumen) cuando se crea el volumen, pero los bloques de unidades no se asignan (anula la asignación). En comparación, en un volumen grueso tradicional, todos los bloques de unidades se asignan o se asignan durante una operación de inicialización de volúmenes en segundo plano para inicializar los campos de información de protección de Data Assurance y para hacer que la paridad de datos y RAID sea coherente en cada franja de RAID. Con un volumen aprovisionado, no existe una inicialización en segundo plano vinculada al tiempo. En su lugar, cada franja RAID se inicializa con la primera escritura en un bloque de volumen en la franja.

Los volúmenes aprovisionados mediante recursos solo se admiten en los grupos de volúmenes SSD y pools, donde todas las unidades del grupo o pool admiten la funcionalidad de recuperación de error de bloque lógico no escrito o desasignado (DULBE). Cuando se crea un volumen aprovisionado por recursos, todos los bloques de unidades asignados al volumen se desasignan (desasignan). Asimismo, los hosts pueden desasignar bloques lógicos del volumen mediante el comando Gestión de conjuntos de datos de NVMe o el comando SCSI Unmap. Si se desasignan bloques, es posible mejorar la vida útil de las unidades de estado sólido y aumentar el rendimiento de escritura máximo. La mejora varía en función del modelo y la capacidad de cada unidad.


NOTE: DULBE no es compatible con las cabinas de almacenamiento EF300C o EF600C por el momento.



== ¿Qué debo saber acerca de la función de volúmenes aprovisionados mediante recursos?

El aprovisionamiento de recursos es una función disponible en las cabinas de almacenamiento EF300 y EF600, lo que permite poner en uso los volúmenes de inmediato sin proceso de inicialización en segundo plano.

Un volumen aprovisionado por recursos es un volumen grueso de un grupo de volúmenes SSD o pool, donde se asigna capacidad de la unidad (asignada al volumen) cuando se crea el volumen, pero los bloques de unidades no se asignan (anula la asignación). En comparación, en un volumen grueso tradicional, todos los bloques de unidades se asignan o se asignan durante una operación de inicialización de volúmenes en segundo plano para inicializar los campos de información de protección de Data Assurance y para hacer que la paridad de datos y RAID sea coherente en cada franja de RAID. Con un volumen aprovisionado, no existe una inicialización en segundo plano vinculada al tiempo. En su lugar, cada franja RAID se inicializa con la primera escritura en un bloque de volumen en la franja.

Los volúmenes aprovisionados mediante recursos solo se admiten en los grupos de volúmenes SSD y pools, donde todas las unidades del grupo o pool admiten la funcionalidad de recuperación de error de bloque lógico no escrito o desasignado (DULBE). Cuando se crea un volumen aprovisionado por recursos, todos los bloques de unidades asignados al volumen se desasignan (desasignan). Asimismo, los hosts pueden desasignar bloques lógicos del volumen mediante el comando Gestión de conjuntos de datos de NVMe o el comando SCSI Unmap. Si se desasignan bloques, es posible mejorar la vida útil de las unidades de estado sólido y aumentar el rendimiento de escritura máximo. La mejora varía en función del modelo y la capacidad de cada unidad.

El aprovisionamiento de recursos está habilitado de forma predeterminada en sistemas donde las unidades admiten DULBE. Puede desactivar esa configuración predeterminada en *Pools y grupos de volúmenes*.


NOTE: DULBE no es compatible con las cabinas de almacenamiento EF300C o EF600C por el momento.
