---
permalink: sm-storage/faq-storage-drives.html 
sidebar: sidebar 
keywords:  
summary: Estas preguntas frecuentes pueden ser de ayuda si solo está buscando una respuesta rápida a una pregunta. 
---
= Preguntas frecuentes sobre unidades de almacenamiento para SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Estas preguntas frecuentes pueden ser de ayuda si solo está buscando una respuesta rápida a una pregunta.



== ¿Qué es una unidad de repuesto?

Las piezas de repuesto actúan como unidades en espera en los grupos de volúmenes RAID 1, RAID 5 o RAID 6. Son unidades completamente funcionales que no contienen datos. Si se produce un error en una unidad del grupo de volúmenes, la controladora automáticamente reconstruye los datos de la unidad con error en una pieza de repuesto.

Si se produce un error en una unidad de la cabina de almacenamiento, la unidad de repuesto automáticamente sustituye a la unidad con error sin necesidad de realizar un cambio físico. Si la unidad de repuesto está disponible cuando se produce un error en una unidad, la controladora utiliza datos de redundancia para reconstruir los datos de la unidad con error en la unidad de repuesto.

Una unidad de repuesto no está dedicada a un grupo de volúmenes específico. Sino que se puede usar la unidad de repuesto en lugar de cualquier unidad con error de la cabina de almacenamiento con la misma capacidad o una menor. Una unidad de repuesto debe ser del mismo tipo de medio (HDD o SSD) que las unidades que protege.

[NOTE]
====
Las unidades de repuesto no son compatibles con los pools. En lugar de las unidades de repuesto, los pools utilizan la capacidad de conservación dentro de cada unidad que compone el pool.

====


== ¿Qué es la capacidad de conservación?

La capacidad de conservación es la cantidad de capacidad (cantidad de unidades) que se reserva en un pool para admitir fallos de unidad potenciales.

Cuando se crea un pool, el sistema reserva automáticamente una cantidad predeterminada de capacidad de conservación según el número de unidades del pool.

Los pools utilizan la capacidad de conservación durante la reconstrucción, mientras que los grupos de volúmenes utilizan unidades de pieza de repuesto con el mismo fin. El método de capacidad de conservación es una mejora con respecto a las unidades de pieza de repuesto, dado que permite realizar la reconstrucción con mayor rapidez. La capacidad de conservación se distribuye en varias unidades del pool, en lugar de en una unidad como en el caso de la unidad de repuesto, por lo que la velocidad o disponibilidad de una unidad no representan una limitación.



== ¿Por qué debería reemplazar lógicamente una unidad?

Si se produce un error en una unidad o si desea reemplazarla por algún otro motivo y tiene una unidad sin asignar en la cabina de almacenamiento, puede reemplazar lógicamente la unidad con error por la unidad sin asignar. Si no tiene una unidad sin asignar, puede optar por reemplazar físicamente la unidad.

Los datos de la unidad original se copian o reconstruyen en la unidad de reemplazo.



== ¿Dónde se puede ver el estado de una unidad sujeta a reconstrucción?

Se puede ver el estado de reconstrucción de la unidad desde la consola Operaciones en curso.

En la página Inicio, haga clic en el enlace *Ver operaciones en curso* de la parte superior derecha.

Según la unidad, es posible que la reconstrucción completa demore bastante. Si se modificó la propiedad de un volumen, es posible que se realice la reconstrucción completa en lugar de la rápida.
