---
permalink: sm-storage/how-workloads-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, application, workloads, volume, 
summary: Al crear un volumen, se debe seleccionar una carga de trabajo para personalizar la configuración de la cabina de almacenamiento para una aplicación específica. 
---
= Cómo funcionan las cargas de trabajo en el software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al crear un volumen, se debe seleccionar una carga de trabajo para personalizar la configuración de la cabina de almacenamiento para una aplicación específica.

Una carga de trabajo es un objeto de almacenamiento que admite una aplicación. Se pueden definir una o más cargas de trabajo o instancias por aplicación.



== Crear una carga de trabajo

Debes especificar manualmente cuándo quieres crear una carga de trabajo que no esté asociada con una aplicación específica. También debes especificar manualmente la configuración del volumen usando la página Add Volumes.



== Vistas de aplicaciones y cargas de trabajo

Para ver aplicaciones y cargas de trabajo, ejecute System Manager de SANtricity. Desde esa interfaz, es posible ver la información asociada a una carga de trabajo específica de la aplicación de dos maneras diferentes:

* Puedes seleccionar la pestaña *Aplicaciones y cargas de trabajo* en la página Volúmenes para ver los volúmenes de la matriz de almacenamiento agrupados por carga de trabajo y el tipo de aplicación al que está asociada la carga de trabajo.
* Puedes seleccionar la pestaña *Aplicaciones y cargas de trabajo* en la página Rendimiento para ver las métricas de rendimiento (latencia, IOPS y MBs) de los objetos lógicos. Los objetos se agrupan por aplicación y carga de trabajo asociada. Al recopilar estos datos de rendimiento a intervalos regulares, puedes establecer mediciones de referencia y analizar tendencias, lo que puede ayudarte mientras investigas problemas relacionados con el rendimiento de E/S.

