---
permalink: sm-storage/increase-capacity-of-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, capacity, volume 
summary: 'Es posible aumentar la capacidad notificada (a los hosts) de un volumen con la capacidad libre que está disponible en el pool o el grupo de volúmenes.' 
---
= Aumentar la capacidad de un volumen en SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible aumentar la capacidad notificada (a los hosts) de un volumen con la capacidad libre que está disponible en el pool o el grupo de volúmenes.

.Antes de empezar
* Existe capacidad libre suficiente disponible en el pool o el grupo de volúmenes asociado.
* El volumen es óptimo y no está en ningún estado de modificación.
* No se alcanzó la capacidad notificada máxima de 256 TIB para volúmenes finos.
* No existen unidades de repuesto en uso en el volumen. (Esto se aplica solo a volúmenes que pertenecen a grupos de volúmenes.)



NOTE: Solo puede expandir la capacidad de un volumen de hasta 128 TiB a la vez.

.Acerca de esta tarea
Tenga en cuenta todos los requisitos de capacidad futuros que puede tener para otros volúmenes en este pool o grupo de volúmenes. Asegúrese de tener suficiente capacidad libre para crear imágenes Snapshot, volúmenes Snapshot o reflejos remotos.

[NOTE]
====
Solo ciertos sistemas operativos permiten aumentar la capacidad de un volumen. Si aumenta la capacidad de un volumen en un sistema operativo que no lo permite, la capacidad ampliada será inutilizable y no se podrá restaurar la capacidad de volumen original.

====
.Pasos
. En el panel izquierdo, selecciona menú:Storage[Volumes].
. Selecciona el volumen para el que quieres aumentar la capacidad y luego haz clic en el icono del menú:ellipsis[Aumentar capacidad].
+
Aparece la página Confirm Increase Capacity.

. Seleccione *Sí* para continuar.
+
Aparece la página Increase Reported Capacity.

+
Esta página muestra la capacidad actual informada del volumen y la capacidad libre disponible en el pool o grupo de volúmenes asociado al volumen.

. Usa la casilla *Aumentar la capacidad notificada añadiendo...* para añadir capacidad a la capacidad notificada disponible actual. Puedes cambiar el valor de la capacidad para que se muestre en mebibytes (MiB), gibibytes (GiB) o tebibytes (TiB).
. Haga clic en *aumentar*.


.Resultados
* System Manager aumenta la capacidad del volumen según lo seleccionado.
* Selecciona menú:Storage[Operations in Progress] para ver el progreso de la operación de aumento de capacidad que se está ejecutando actualmente para el volumen seleccionado. Esta operación puede ser larga y podría afectar el rendimiento del sistema.


.Después de terminar
Después de expandir la capacidad del volumen, debe aumentar manualmente el tamaño del sistema de archivos para que coincidan. La forma de hacerlo depende del sistema de archivos utilizado. Para obtener detalles, compruebe la documentación del sistema operativo del host.
