---
permalink: sm-storage/increase-capacity-of-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, capacity, volume 
summary: 'Es posible aumentar la capacidad notificada (a los hosts) de un volumen con la capacidad libre que está disponible en el pool o el grupo de volúmenes.' 
---
= Aumente la capacidad de un volumen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible aumentar la capacidad notificada (a los hosts) de un volumen con la capacidad libre que está disponible en el pool o el grupo de volúmenes.

.Antes de empezar
* Existe capacidad libre suficiente disponible en el pool o el grupo de volúmenes asociado.
* El volumen es óptimo y no está en ningún estado de modificación.
* No se alcanzó la capacidad notificada máxima de 256 TIB para volúmenes finos.
* No existen unidades de repuesto en uso en el volumen. (Esto se aplica solo a volúmenes que pertenecen a grupos de volúmenes.)


.Acerca de esta tarea
Tenga en cuenta todos los requisitos de capacidad futuros que puede tener para otros volúmenes en este pool o grupo de volúmenes. Asegúrese de tener suficiente capacidad libre para crear imágenes Snapshot, volúmenes Snapshot o reflejos remotos.

[NOTE]
====
Solo ciertos sistemas operativos permiten aumentar la capacidad de un volumen. Si aumenta la capacidad de un volumen en un sistema operativo que no lo permite, la capacidad ampliada será inutilizable y no se podrá restaurar la capacidad de volumen original.

====
.Pasos
. Seleccione MENU:Storage[Volumes].
. Seleccione el volumen para el que desea aumentar la capacidad y, a continuación, seleccione *aumentar capacidad*.
+
Se muestra el cuadro de diálogo Confirmar aumento de capacidad.

. Seleccione *Sí* para continuar.
+
Se muestra el cuadro de diálogo aumentar capacidad notificada.

+
En este cuadro de diálogo, se muestran la capacidad notificada actual y la capacidad libre disponibles en el pool o el grupo de volúmenes asociado.

. Utilice el cuadro *aumentar capacidad notificada agregando...* para añadir capacidad a la capacidad informada disponible actual. Es posible cambiar el valor de capacidad para que se muestre en mebibytes (MIB), gibibytes (GIB) o tebibytes (TIB).
. Haga clic en *aumentar*.


.Resultados
* System Manager aumenta la capacidad del volumen según lo seleccionado.
* Seleccione MENU:Inicio[Ver operaciones en curso] para ver el progreso de la operación de aumento de capacidad que está en ejecución actualmente para el volumen seleccionado. Es posible que esta operación demore y que afecte el rendimiento del sistema.


.Después de terminar
Después de expandir la capacidad del volumen, debe aumentar manualmente el tamaño del sistema de archivos para que coincidan. La forma de hacerlo depende del sistema de archivos utilizado. Para obtener detalles, compruebe la documentación del sistema operativo del host.
