---
permalink: sm-storage/rtv-remove-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, remote, storage, 
summary: Después de que finalice la importación, puede quitar un objeto de almacenamiento remoto si ya no desea copiar los datos entre los dispositivos local y remoto. 
---
= Quitar el objeto de almacenamiento remoto
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de que finalice la importación, puede quitar un objeto de almacenamiento remoto si ya no desea copiar los datos entre los dispositivos local y remoto.

.Antes de empezar
Asegúrese de que no haya importaciones asociadas con el objeto de almacenamiento remoto que desee quitar.

.Acerca de esta tarea
Al quitar un objeto de almacenamiento remoto, se eliminan las conexiones entre los dispositivos local y remoto.

.Pasos
. Seleccione MENU:Storage[Remote Storage].
. Seleccione el objeto de almacenamiento remoto que desea quitar de la lista.
. Haga clic en *Quitar*.
+
Se mostrará el cuadro de diálogo Confirmar eliminación de conexión de almacenamiento remoto.

. Confirme la operación escribiendo `remove` Y, a continuación, haga clic en *Quitar*.
+
Se elimina el objeto de almacenamiento remoto seleccionado.


