---
permalink: sm-storage/rtv-manage-progress-of-remote-volume-import.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, imports 
summary: Una vez que comienza el proceso de importación, puede ver y actuar sobre su progreso. 
---
= Gestione el progreso de las importaciones de almacenamiento remoto
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una vez que comienza el proceso de importación, puede ver y actuar sobre su progreso.

.Acerca de esta tarea
Para cada operación de importación, el cuadro de diálogo Operaciones en curso muestra un porcentaje de finalización y el tiempo restante estimado. Las acciones incluyen cambiar la prioridad de importación, detener y reanudar operaciones, y desconectarse de la operación.

También es posible ver operaciones en curso en la página Inicio (MENU:Inicio[Mostrar operaciones en curso]).

.Pasos
. En la página almacenamiento remoto, seleccione *Ver operaciones*.
+
Se muestra el cuadro de diálogo Operaciones en curso.

. Si lo desea, utilice los vínculos de la columna *acciones* para detener y reanudar, cambiar la prioridad o desconectarse de una operación.
+
** *Cambiar prioridad* -- Seleccione *Cambiar prioridad* para cambiar la prioridad de procesamiento de una operación en curso o pendiente. Aplique una prioridad a la operación y, a continuación, haga clic en *Aceptar*.
** *Stop* -- Seleccione *Stop* para pausar la copia de datos del dispositivo de almacenamiento remoto. La relación entre el par de importación sigue intacta y puede seleccionar *Reanudar* cuando esté listo para continuar con la operación de importación.
** *Reanudar* -- Seleccione *Reanudar* para comenzar un proceso detenido o fallido desde el punto en que lo dejó. A continuación, aplique una prioridad a la operación Reanudar y, a continuación, haga clic en *Aceptar*. Esta operación _not_ reinicia la importación desde el principio. Si desea reiniciar el proceso desde el principio, debe seleccionar *desconectar* y volver a crear la importación a través del asistente Importar almacenamiento remoto.
** *Desconectar* -- Seleccione *desconectar* para romper la relación entre los volúmenes de origen y destino para una operación de importación que se haya detenido, completado o fallido.



