---
permalink: sm-storage/turn-on-locator-lights-in-a-pool-volume-group-or-ssd-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, lights, LEDs 
summary: Se pueden localizar las unidades para identificar físicamente todas las unidades que conforman una caché SSD, un pool o un grupo de volúmenes seleccionado. En cada unidad, se enciende un indicador LED en la caché SSD, el pool o el grupo de volúmenes seleccionado. 
---
= Encender las luces localizadoras en un pool, un grupo de volúmenes o la caché SSD
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se pueden localizar las unidades para identificar físicamente todas las unidades que conforman una caché SSD, un pool o un grupo de volúmenes seleccionado. En cada unidad, se enciende un indicador LED en la caché SSD, el pool o el grupo de volúmenes seleccionado.

.Pasos
. Seleccione MENU:almacenamiento[Pools y grupos de volúmenes].
. Seleccione el pool, el grupo de volúmenes o la caché SSD que desea localizar y, a continuación, haga clic en menu:more[encender las luces de localización].
+
Se muestra un cuadro de diálogo que indica que las luces de las unidades que conforman la caché SSD, el pool o el grupo de volúmenes seleccionado están encendidas.

. Una vez que haya localizado correctamente las unidades, haga clic en *Apagar*.

