---
permalink: sm-storage/view-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, ssd cache, statistics 
summary: Es posible ver estadísticas de la caché SSD, como lecturas, escrituras, aciertos en caché, porcentaje de asignación de caché, y el porcentaje de utilización de la caché. 
---
= Ver las estadísticas de caché SSD en SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible ver estadísticas de la caché SSD, como lecturas, escrituras, aciertos en caché, porcentaje de asignación de caché, y el porcentaje de utilización de la caché.

Las estadísticas nominales, que son un subconjunto de estadísticas detalladas, se muestran en el cuadro de diálogo Ver estadísticas de la caché SSD. Es posible ver estadísticas detalladas de la caché SSD solo cuando se exportan todas las estadísticas de SSD a un `.csv` archivo.

Al revisar e interpretar las estadísticas, tenga en cuenta que algunas interpretaciones provienen del análisis de una combinación de estadísticas.

.Pasos
. Seleccione MENU:almacenamiento[Pools y grupos de volúmenes].
. Seleccione la caché SSD para la cual desea ver estadísticas y haga clic en menú:más[Ver estadísticas de la caché SSD].
+
Se muestra el cuadro de diálogo Ver estadísticas de la caché SSD, donde se proporcionan las estadísticas nominales de la caché SSD seleccionada.

+
.Detalles del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Configuración | Descripción 


 a| 
Lecturas
 a| 
Se muestra el número total de lecturas del host de los volúmenes con la función de caché SSD habilitada. Cuanto más alto sea el ratio de lecturas a escrituras, mejor será el funcionamiento de la caché.



 a| 
Escrituras
 a| 
El número total de escrituras del host en los volúmenes con la función de caché SSD habilitada. Cuanto más alto sea el ratio de lecturas a escrituras, mejor será el funcionamiento de la caché.



 a| 
Aciertos en caché
 a| 
Se muestra el número de aciertos en caché.



 a| 
Aciertos en caché
 a| 
Se muestra el porcentaje de aciertos en caché. Este número deriva de los aciertos en caché/(lecturas + escrituras). El porcentaje de aciertos en caché debe ser mayor que 50 % para un funcionamiento eficaz de la caché SSD.



 a| 
Asignación en caché
 a| 
Se muestra el porcentaje de almacenamiento de la caché SSD asignado, expresado como un porcentaje del almacenamiento de la caché SSD que está disponible para esta controladora y deriva de los bytes asignados/bytes disponibles.



 a| 
Uso de caché
 a| 
Se muestra el porcentaje de almacenamiento de la caché SSD que contiene datos de volúmenes habilitados, expresado como un porcentaje del almacenamiento de la caché SSD asignado. Esta cantidad representa la utilización o la densidad de la caché SSD. Derivado de bytes asignados/bytes disponibles.



 a| 
Exportar todo
 a| 
Exporta todas las estadísticas de la caché SSD a un formato CSV. El archivo exportado contiene todas las estadísticas disponibles de la caché SSD (tanto nominales como detalladas).

|===
====
. Haga clic en *Cancelar* para cerrar el cuadro de diálogo.

