---
permalink: sm-storage/volume-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, terms 
summary: Conozca la forma en que los términos de volúmenes se aplican a su cabina de almacenamiento. 
---
= Terminología de volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conozca la forma en que los términos de volúmenes se aplican a su cabina de almacenamiento.



== Todos los tipos de volúmenes

[cols="25h,~"]
|===
| Duración | Descripción 


 a| 
Capacidad asignada
 a| 
Se utiliza la capacidad asignada para crear volúmenes y para operaciones de servicios de copia.

La capacidad asignada y la capacidad notificada son iguales en los volúmenes gruesos, pero son diferentes en los volúmenes finos. En el caso de un volumen grueso, el espacio físicamente asignado es igual al espacio que se informa en el host. En un volumen fino, la capacidad notificada es la capacidad que se notifica a los hosts, mientras que la capacidad asignada es la cantidad de espacio de la unidad asignado para la escritura de datos.



 a| 
Cliente más
 a| 
Una aplicación es un software, como SQL Server o Exchange. Se definen una o más cargas de trabajo que sean compatibles con cada aplicación. En algunas aplicaciones, el sistema recomienda automáticamente una configuración de volumen que optimice el almacenamiento. Las características como el tipo de I/o, el tamaño de segmento, la propiedad de controladora y la caché de lectura y escritura se incluyen en la configuración de volumen.



 a| 
Capacidad
 a| 
La capacidad es la cantidad de datos que se pueden almacenar en un volumen.



 a| 
Propiedad de la controladora
 a| 
La propiedad de controladora define la controladora que se designa como propietaria o primaria, la controladora del volumen. Un volumen puede tener un controlador preferido (A o B) que "'posea'" el volumen. La propiedad del volumen se ajusta automáticamente con la función Automatic Load Balancing para corregir cualquier problema de equilibrio de carga cuando las cargas de trabajo cambian entre las controladoras. La función Automatic Load Balancing proporciona equilibrio de cargas de trabajo de I/o automatizado y garantiza que el tráfico de I/o entrante desde los hosts se gestione de manera dinámica y se equilibre entre ambas controladoras.



 a| 
Captura previa de lectura de caché dinámica
 a| 
La captura previa de lectura de la caché dinámica permite a la controladora copiar otros bloques de datos secuenciales en la caché mientras lee bloques de datos de una unidad en la caché. Ese almacenamiento en caché aumenta la posibilidad de que se puedan cumplir futuras solicitudes de datos de la caché. La captura previa de lectura de la caché dinámica es importante para las aplicaciones multimedia que utilizan I/o secuencial La cantidad y la velocidad de las capturas previas de los datos en la caché se ajustan automáticamente según la velocidad y el tamaño de solicitud de las lecturas del host. El acceso aleatorio no provoca la captura previa de los datos en la caché. Esta función no se aplica cuando el almacenamiento en caché de lectura está deshabilitado.

En el caso de volumen fino, la captura previa de la lectura de caché dinámica siempre está deshabilitada y no se puede modificar.



 a| 
Área de capacidad libre
 a| 
Un área de capacidad libre es la capacidad libre que puede surgir después de eliminar un volumen o por no utilizar toda la capacidad libre disponible durante la creación de un volumen. Cuando se crea un volumen en un grupo de volúmenes que tiene una o más áreas de capacidad libre, la capacidad del volumen se limita al área de capacidad libre más grande de ese grupo de volúmenes. Por ejemplo, si un grupo de volúmenes tiene una capacidad libre total de 15 GIB y el área de capacidad libre más grande es 10 GIB, el volumen más grande que se puede crear es de 10 GIB.

Al consolidar la capacidad libre, se pueden crear volúmenes adicionales de la cantidad máxima de capacidad libre de un grupo de volúmenes.



 a| 
Host
 a| 
Un host es un servidor que envía I/o a un volumen de una cabina de almacenamiento.



 a| 
Clúster de hosts
 a| 
Un clúster de hosts es un grupo de hosts. Se crea un clúster de hosts para facilitar la asignación de los mismos volúmenes en varios hosts.



 a| 
Unidad de repuesto
 a| 
Las unidades de repuesto solo son compatibles con los grupos de volúmenes. La unidad de repuesto no contiene datos y queda en espera en caso de que se produzca un error en una unidad de los volúmenes RAID 1, RAID 3, RAID 5 o RAID 6 que se encuentran en un grupo de volúmenes. La unidad de repuesto añade otro nivel de redundancia a la cabina de almacenamiento.



 a| 
LUN
 a| 
Un número de unidad lógica (LUN) es el número asignado al espacio de dirección que utiliza un host para acceder a un volumen. El volumen se presenta al host como capacidad en forma de LUN.

Cada host tiene su propio espacio de dirección de LUN. Por lo tanto, distintos hosts pueden utilizar el mismo LUN para acceder a diferentes volúmenes.



 a| 
Análisis de medios
 a| 
Un análisis de medios proporciona un método para detectar errores de medios en la unidad antes de que se detecten durante operaciones de lectura o escritura normales en las unidades. El análisis de medios se realiza como una operación en segundo plano y analiza todos los datos y la información de redundancia en los volúmenes de usuario definidos.



 a| 
Espacio de nombres
 a| 
Un espacio de nombres es almacenamiento NVM que se formateó para el acceso en bloque. Es análogo a una unidad lógica en SCSI, que se relaciona con un volumen en la cabina de almacenamiento.



 a| 
Piscina
 a| 
Un pool es un conjunto de unidades que se agrupan en forma lógica. Se puede usar un pool para crear uno o más volúmenes accesibles para un host. (Se crean volúmenes desde un pool o un grupo de volúmenes).



 a| 
Capacidad de pool o grupo de volúmenes
 a| 
La capacidad de pool, volumen o grupo de volúmenes es la capacidad de una cabina de almacenamiento que se asignó a un pool o un grupo de volúmenes. Esta capacidad se usa para crear volúmenes y atender las diversas necesidades de capacidad de las operaciones de servicios de copia y objetos de almacenamiento.



 a| 
Caché de lectura
 a| 
La caché de lectura es un búfer que almacena datos que se leyeron de las unidades. Es posible que los datos de una operación de lectura ya deban estar en la caché debido a una operación anterior, por lo tanto, no es necesario acceder a las unidades. Los datos se conservan en la caché de lectura hasta que esta se vacía.



 a| 
Capacidad notificada
 a| 
La capacidad notificada es la capacidad que se informa al host y a la que el host puede acceder.

La capacidad notificada y la capacidad asignada son iguales en los volúmenes gruesos, pero son diferentes en los volúmenes finos. En el caso de un volumen grueso, el espacio físicamente asignado es igual al espacio que se informa en el host. En un volumen fino, la capacidad notificada es la capacidad que se notifica a los hosts, mientras que la capacidad asignada es la cantidad de espacio de la unidad asignado para la escritura de datos.



 a| 
Tamaño de los segmentos
 a| 
Un segmento es la cantidad de datos en kilobytes (KiB) que se almacenan en una unidad antes de que la cabina de almacenamiento pase a la unidad siguiente en la franja (grupo RAID). El tamaño del segmento es igual o menor que la capacidad del grupo de volúmenes. El tamaño del segmento es fijo y no se puede cambiar para los pools.



 a| 
Segmentación
 a| 
La segmentación es una manera de almacenar datos en la cabina de almacenamiento. La segmentación divide el flujo de datos en bloques de un determinado tamaño (denominado "tamaño de bloque") y luego escribe esos bloques en las unidades uno por uno. Esta manera de almacenamiento de datos se usa para distribuir y almacenar datos en varias unidades físicas. La segmentación es un sinónimo de RAID 0 y distribuye los datos en todas las unidades de un grupo RAID sin paridad.



 a| 
Volumen
 a| 
Un volumen es un contenedor en el cual las aplicaciones, las bases de datos y los sistemas de archivos almacenan datos. Es el componente lógico que se crea para que el host acceda al almacenamiento de la cabina de almacenamiento.



 a| 
Asignación de volúmenes
 a| 
La asignación de volumen es cómo se asignan los LUN de host a un volumen.



 a| 
Nombre del volumen
 a| 
Un nombre de volumen es una cadena de caracteres que se asignan al volumen cuando se crea. Se puede aceptar el nombre predeterminado o se puede proporcionar un nombre más descriptivo que indique el tipo de datos almacenados en el volumen.



 a| 
Grupo de volúmenes
 a| 
Un grupo de volúmenes es un contenedor para volúmenes con características compartidas. Un grupo de volúmenes tiene una capacidad definida y un nivel de RAID. Se puede usar un grupo de volúmenes para crear uno o más volúmenes a los que se pueda acceder mediante un host. (Los volúmenes se crean a partir de un pool o un grupo de volúmenes).



 a| 
Carga de trabajo
 a| 
Una carga de trabajo es un objeto de almacenamiento que admite una aplicación. Se pueden definir una o más cargas de trabajo o instancias por aplicación. En algunas aplicaciones, el sistema configura la carga de trabajo para contener volúmenes con características subyacentes similares. Estas características de volumen se optimizan según el tipo de aplicación que es compatible con la carga de trabajo. Por ejemplo, si crea una carga de trabajo que es compatible con la aplicación Microsoft SQL Server y, a continuación, crea volúmenes para esa carga de trabajo, las características de volumen subyacentes se optimizan para ser compatibles con Microsoft SQL Server.



 a| 
Caché de escritura
 a| 
La caché de escritura es un búfer que almacena datos del host que todavía no se escribieron en las unidades. Los datos permanecen en la caché de escritura hasta que se escriben en las unidades. El almacenamiento en caché de escritura puede aumentar el rendimiento de I/O.



 a| 
Almacenamiento en caché de escritura con mirroring
 a| 
El almacenamiento en caché de escritura con mirroring se produce cuando los datos escritos en la memoria caché de una controladora también se escriben en la memoria caché de otra controladora. Por lo tanto, si una controladora falla, la otra puede completar todas las operaciones de escritura pendientes. El mirroring de la caché de escritura está disponible solo si el almacenamiento en caché de escritura está habilitado y existen dos controladoras. El almacenamiento en caché de escritura con mirroring es la configuración predeterminada cuando se crea un volumen.



 a| 
Almacenamiento en caché de escritura sin baterías
 a| 
La configuración de almacenamiento en caché de escritura sin baterías permite que el almacenamiento en caché de escritura continúe incluso si las baterías faltan, fallan, están completamente descargadas o no están totalmente cargadas. Por lo general, no se recomienda elegir el almacenamiento en caché de escritura sin baterías porque se pueden perder los datos en caso de interrupción del suministro eléctrico. Comúnmente, la controladora desactiva en forma temporal el almacenamiento en caché de escritura hasta que se cargan las baterías o se reemplaza una batería con errores.

|===


== Específico de volúmenes finos

[NOTE]
====
System Manager no proporciona ninguna opción para crear volúmenes finos. Si se desea crear volúmenes finos, se debe usar la interfaz de línea de comandos (CLI).

====
[NOTE]
====
Los volúmenes finos no están disponibles en los sistemas de almacenamiento EF600 o EF300.

====
[cols="25h,~"]
|===
| Duración | Descripción 


 a| 
Límite de capacidad asignada
 a| 
El límite de la capacidad asignada equivale a cuánto puede aumentar la capacidad física asignada para un volumen fino.



 a| 
Capacidad escrita
 a| 
La capacidad escrita es la cantidad que se escribió de la capacidad reservada asignada para volúmenes finos.



 a| 
Umbral de advertencia
 a| 
Se puede definir una alerta de umbral de advertencia que indique cuándo la capacidad asignada para un volumen fino alcanza la totalidad del porcentaje (el umbral de advertencia).

|===