---
permalink: sm-storage/what-is-redundancy-check.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, redundancy, check 
summary: Una comprobación de redundancia determina si los datos de un volumen en un pool o grupo de volúmenes son consistentes. Los datos de redundancia se utilizan para reconstruir información rápidamente en una unidad de reemplazo si falla una de las unidades de un pool o grupo de volúmenes. 
---
= ¿Qué es una comprobación de redundancia?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una comprobación de redundancia determina si los datos de un volumen en un pool o grupo de volúmenes son consistentes. Los datos de redundancia se utilizan para reconstruir información rápidamente en una unidad de reemplazo si falla una de las unidades de un pool o grupo de volúmenes.

Es posible realizar esta comprobación solo en un pool o grupo de volúmenes a la vez. Una comprobación de redundancia de un volumen realiza las acciones siguientes:

* Escanea los bloques de datos en un volumen RAID 3, un volumen RAID 5 o un volumen RAID 6 y, a continuación, comprueba la información de redundancia de cada bloque. (RAID 3 solo puede asignarse a grupos de volúmenes con interfaz de línea de comandos.)
* Compara los bloques de datos en unidades reflejadas RAID 1.
* Devuelve errores de redundancia si el firmware de la controladora determina que los datos no son consistentes.


[NOTE]
====
Si se ejecuta de inmediato una comprobación de redundancia en el mismo pool o grupo de volúmenes, se puede generar un error. Para evitar este problema, espere de uno a dos minutos antes de ejecutar otra comprobación de redundancia en el mismo pool o grupo de volúmenes.

====