---
permalink: sm-storage/why-dont-i-see-all-my-volumes-hosts-or-host-clusters.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volumes, hosts, host clusters, data assurance 
summary: 'Los volúmenes Snapshot que incluyen un volumen base con la función DA habilitada no son aptos para asignarse a un host que no es compatible con la función Data Assurance (DA). Debe deshabilitar DA en el volumen base para poder asignar un volumen Snapshot a un host que no es compatible con DA".' 
---
= ¿Por qué no se muestran todos los volúmenes, los hosts o los clústeres de hosts?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los volúmenes Snapshot que incluyen un volumen base con la función DA habilitada no son aptos para asignarse a un host que no es compatible con la función Data Assurance (DA). Debe deshabilitar DA en el volumen base para poder asignar un volumen Snapshot a un host que no es compatible con DA.

Tenga en cuenta las siguientes directrices para el host al cual planea asignar el volumen Snapshot:

* Un host no es compatible con DA si está conectado a la cabina de almacenamiento a través de una interfaz de I/o que no es compatible con DA.
* Un clúster de hosts no es compatible con DA si tiene al menos un miembro de host que no es compatible con DA.


[NOTE]
====
No se puede deshabilitar LA DA en un volumen asociado con Snapshot (grupos de coherencia, grupos Snapshot, imágenes Snapshot y volúmenes Snapshot), copias de volumen, y espejos. Toda la capacidad reservada y los objetos Snapshot asociados deben eliminarse para poder deshabilitar DA en el volumen base.

====