---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 12.0 
summary: Nuevas funciones del sistema operativo SANtricity. 
---
= Novedades en SANtricity OS 12.0
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La siguiente tabla describe las nuevas funciones en SANtricity System Manager 12.0.



== Novedades en la versión 12.0


NOTE: La versión 12.0 de SANtricity OS solo es compatible con los nuevos sistemas de almacenamiento all-flash EF80 y EF50. Si estás usando SANtricity OS 11.9 o anterior, consulta link:known-issues.html["Problemas conocidos"] para ver una lista de las nuevas funciones en versiones anteriores.

[cols="35h,~"]
|===
| Nueva función | Descripción 


 a| 
Nuevos modelos de sistemas de almacenamiento – sistemas de almacenamiento all-flash EF80 y EF50
 a| 
Esta versión presenta los sistemas de almacenamiento all-NVMe-flash EF80 y EF50. Los EF80 y EF50 admiten 24 unidades SSD NVME y una única tarjeta de interfaz del host (HIC) por controlador. Las interfaces del host NVMe over Fabrics compatibles incluyen NVMe over RoCE, NVMe over IB para EF80 y NVMe over FC para EF50. Las interfaces SCSI compatibles incluyen Fibre Channel.

Las unidades SSD NVMe de gran capacidad de 30TB o 60TB también son compatibles con EF80 y EF30. EF80 y EF30 son compatibles para uso con Dynamic Disk Pool únicamente, sin soporte para RAID heredado.



 a| 
Nueva interfaz de usuario para SANtricity System Manager
 a| 
Para los nuevos controladores EF80 y EF50, la interfaz de usuario de SANtricity System Manager se ha rediseñado para ofrecer un aspecto y una experiencia más modernos. La nueva interfaz incluye una navegación por el panel izquierdo y una mayor facilidad de uso para agilizar las tareas de administración.


NOTE: La nueva interfaz de usuario está disponible actualmente solo para los sistemas de almacenamiento EF80 y EF50 con la versión SANtricity 12.0. Si estás usando SANtricity 11.9 o una versión anterior, consulta link:https://docs.netapp.com/us-en/e-series-santricity-119/system-manager/index.html["System Manager 11,9 de SANtricity"] para instrucciones sobre cómo usar la interfaz de usuario heredada.



 a| 
Subject Alternative Names (SANs) para el certificado de servidor ahora solo permiten letras, dígitos y guiones
 a| 
Al crear o editar un certificado de servidor en SANtricity System Manager o Unified Manager, el campo Subject Alternative Names (SANs) ahora solo permite letras, dígitos y guiones. Este cambio mejora la seguridad y garantiza la compatibilidad con los estándares del sector para certificados SSL/TLS.



 a| 
El tamaño de segmento de Dynamic Disk Pools ahora es de 32K por defecto para SSD y sistemas basados en NVMe
 a| 
Para los Dynamic Disk Pools en sistemas basados en SSD y NVMe, el tamaño de segmento predeterminado se ha cambiado a 32K. Antes, el tamaño de segmento predeterminado de los Dynamic Disk Pools estaba fijado en 128K para estos sistemas. Este cambio optimiza el rendimiento para cargas de trabajo que implican una mezcla de operaciones de E/S pequeñas y grandes.



 a| 
El editor de scripts ya está disponible en SANtricity System Manager
 a| 
Ahora tienes disponible un nuevo editor de secuencias de comandos dentro de SANtricity System Manager. El editor de secuencias de comandos te permite crear o editar un archivo de secuencia de comandos, guardar un archivo de secuencia de comandos en el disco local de la estación de gestión de almacenamiento o cargar un archivo de secuencia de comandos desde el disco. El editor de secuencias de comandos ofrece comprobación de sintaxis y capacidades de ejecución de comandos para gestionar tu sistema de almacenamiento. Para más información, consulta link:sm-support/use-script-editor.html["Usar el editor de scripts"^].

|===