---
permalink: sm-mirroring/change-synchronization-settings-for-a-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, synchronization, settings, mirror, consistency, group, 
summary: Es posible cambiar la configuración de sincronización y los umbrales de advertencia que utiliza el grupo de coherencia de reflejos en la cabina de almacenamiento local cuando los datos se sincronizan inicialmente o cuando se vuelven a sincronizar durante las operaciones de mirroring asíncrono. 
---
= Cambiar la configuración de sincronización de un grupo de coherencia de reflejos
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar la configuración de sincronización y los umbrales de advertencia que utiliza el grupo de coherencia de reflejos en la cabina de almacenamiento local cuando los datos se sincronizan inicialmente o cuando se vuelven a sincronizar durante las operaciones de mirroring asíncrono.

.Acerca de esta tarea
Un cambio en la configuración de sincronización afecta las operaciones de sincronización de todas las parejas reflejadas dentro del grupo de coherencia de reflejos.

.Pasos
. Seleccione menu:Storage[Asynchronous Mirroring].
. Seleccione la ficha *grupos de consistencia de mirroring*.
+
Aparece la tabla de grupo de coherencia de reflejos y se muestran todos los grupos de coherencia de reflejos asociados con la cabina de almacenamiento.

. Seleccione el grupo de coherencia de reflejos que desea editar y, a continuación, seleccione MENU:más[Editar configuración].
+
Se muestra en el sistema el cuadro de diálogo Editar configuración.

. Edite la configuración de sincronización y alertas según corresponda y, a continuación, haga clic en *Guardar*.
+
.Detalles del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Campo | Descripción 


 a| 
Sincronizar las parejas reflejadas...
 a| 
Especifique si desea sincronizar las parejas reflejadas en la cabina de almacenamiento remota de forma manual o automática.

** **Manualmente**: Seleccione esta opción para sincronizar manualmente las parejas reflejadas en la cabina de almacenamiento remota.
** **Automáticamente, cada**: Seleccione esta opción para sincronizar automáticamente las parejas reflejadas en la cabina de almacenamiento remota especificando el intervalo desde el comienzo de la actualización anterior hasta el comienzo de la siguiente. El intervalo predeterminado es de 10 minutos.




 a| 
Enviarme una alerta...
 a| 
Si configura el método de sincronización para que se produzca automáticamente, configure las siguientes alertas:

** **Sincronización**: Configure el período de tiempo después del cual System Manager envía una alerta de que la sincronización no se ha completado.
** **Punto de recuperación remoto**: Establezca un límite de tiempo después del cual System Manager envía una alerta para indicar que los datos del punto de recuperación en la cabina de almacenamiento remota son más antiguos que el límite de tiempo definido. Defina el límite de tiempo desde la finalización de la actualización anterior.
** **Umbral de capacidad reservada**: Defina una cantidad de capacidad reservada en la que System Manager envía una alerta para indicar que está acercándose al umbral de capacidad reservada. El umbral se define según un porcentaje de la capacidad restante.


|===
====


.Resultados
System Manager modifica la configuración de sincronización de todas las parejas reflejadas en el grupo de coherencia de reflejos.
