---
permalink: sm-mirroring/faq-async-mirroring.html 
sidebar: sidebar 
keywords:  
summary: Estas preguntas frecuentes pueden ser de ayuda si solo está buscando una respuesta rápida a una pregunta. 
---
= Preguntas frecuentes sobre duplicación asincrónica para SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Estas preguntas frecuentes pueden ser de ayuda si solo está buscando una respuesta rápida a una pregunta.



== ¿En qué se diferencia el mirroring asíncrono del mirroring síncrono?

La función Asynchronous Mirroring es diferente de la función Synchronous Mirroring en un aspecto esencial: Captura el estado de un volumen de origen en un momento específico en particular, y copia solo los datos que cambiaron desde la última captura de imagen.

El mirroring síncrono no captura el estado del volumen primario en un momento en el tiempo, sino que refleja en el volumen secundario todos los cambios realizados en el volumen primario. El volumen secundario es idéntico al primario en todo momento, ya que, con este tipo de reflejo, cada vez que se produce una escritura en el volumen primario, se realiza otra en el secundario. El host no recibe la confirmación de que la escritura se realizó correctamente hasta que el volumen secundario se actualiza correctamente con los cambios realizados en el volumen primario.

Con el mirroring asíncrono, la cabina de almacenamiento remota no está completamente sincronizada con la cabina de almacenamiento local, por lo que si la aplicación necesita hacer una transición hacia la cabina de almacenamiento remota debido a una pérdida de la local, pueden perderse algunas transacciones.

Comparación entre funciones de mirroring:

[cols="1a,1a"]
|===
| Mirroring asíncrono | Mirroring síncrono 


 a| 
*Método de replicación*



 a| 
* *Punto en tiempo*
+
El mirroring se realiza bajo demanda o automáticamente según la programación definida por el usuario. Las programaciones pueden definirse con una granularidad de minutos. El tiempo mínimo entre sincronizaciones es de 10 minutos.


 a| 
* *Continuo*
+
El mirroring se ejecuta automáticamente de forma continua, copiando datos en cada escritura del host.





 a| 
*Capacidad reservada*



 a| 
* *Múltiples*
+
Se requiere un volumen de capacidad reservada para cada pareja reflejada.


 a| 
* *Individual*
+
Se requiere un volumen de capacidad reservada individual para todos los volúmenes reflejados.





 a| 
*Comunicación*



 a| 
* *ISCSI y Fibre Channel*
+
Admite interfaces iSCSI y Fibre Channel entre cabinas de almacenamiento.


 a| 
* *Fibre Channel*
+
Admite solo interfaces Fibre Channel entre cabinas de almacenamiento.





 a| 
*Distancia*



 a| 
* *Ilimitada*
+
Admite distancias prácticamente ilimitadas entre la cabina de almacenamiento local y la cabina de almacenamiento remota, con la distancia generalmente limitada solo por las capacidades de la red y la tecnología de extensión de canal.


 a| 
* *Restringido*
+
Generalmente debe estar dentro de una distancia de 10 km (6.2 millas) aproximadamente de la cabina de almacenamiento local para satisfacer los requisitos de latencia y rendimiento de la aplicación.



|===


== ¿Por qué no puedo acceder a la función de duplicación que elegí?

La función de mirroring se configura en la interfaz de SANtricity Unified Manager.

[NOTE]
====
La función de mirroring síncrono no está disponible en las cabinas de almacenamiento EF600/EF600C o EF300/EF300C.

====
Para habilitar y configurar el mirroring entre dos cabinas, compruebe lo siguiente:

* El proxy de servicios web se encuentra en ejecución. (Unified Manager se encuentra instalado en un sistema host junto con el proxy de servicios web.)
* Unified Manager se ejecuta en el host local a través de una conexión HTTPS.
* Las dos cabinas de almacenamiento que se desean usar para el mirroring se detectaron en Unified Manager.
* Unified Manager tiene certificados SSL válidos para las cabinas de almacenamiento. Puede aceptar un certificado autofirmado o instalar certificados firmados por CA desde Unified Manager.


Para obtener instrucciones de configuración, consulte lo siguiente:

* link:../um-manage/create-asynchronous-mirrored-pair-um.html["Crear una pareja reflejada asíncrona (en Unified Manager)"]
* link:../um-manage/create-synchronous-mirrored-pair-um.html["Crear una pareja reflejada síncrona (en Unified Manager)"]




== ¿Qué debo saber antes de crear un grupo de coherencia de reflejos?

Siga estas directrices para poder crear un grupo de coherencia de reflejos.

[NOTE]
====
El mirroring síncrono no está disponible en el sistema de almacenamiento EF600/EF600C o EF300/EF300C.

====
El grupo de coherencia se crea en Unified Manager en el asistente Crear pareja reflejada.

Cumpla con los siguientes requisitos para Unified Manager:

* El proxy de servicios web se encuentra en ejecución.
* Unified Manager se ejecuta en el host local a través de una conexión HTTPS.
* SANtricity Unified Manager debe mostrar los certificados SSL válidos para la cabina de almacenamiento. Es posible aceptar un certificado autofirmado o instalar una certificación de seguridad propia con Unified Manager. Para hacerlo, debe navegar hasta MENU:Certificate[Gestión de certificados].


También debe cumplir con los siguientes requisitos para las cabinas de almacenamiento:

* Las dos cabinas de almacenamiento se encuentran detectadas en Unified Manager.
* Cada cabina de almacenamiento debe tener dos controladoras.
* Cada controladora en la cabina primaria y la cabina secundaria debe tener un puerto Ethernet de gestión configurado y debe estar conectada a la red.
* Las cabinas de almacenamiento deben tener la versión de firmware 7.84 como mínimo. (Cada una puede ejecutar versiones de sistema operativo diferentes).
* Debe conocer la contraseña de las cabinas de almacenamiento remota y local.
* Las cabinas de almacenamiento local y remota se encuentran conectadas a través de una estructura Fibre Channel o una interfaz iSCSI.




== Mirroring asíncrono: ¿Qué debo saber antes de crear una pareja reflejada?

Las parejas reflejadas se configuran en la interfaz de SANtricity Unified Manager y, posteriormente, se gestionan en SANtricity System Manager.

Antes de crear una pareja reflejada, siga estas directrices.

* Debe tener dos cabinas de almacenamiento.
* Cada cabina de almacenamiento debe tener dos controladoras.
* Cada controladora en la cabina primaria y la cabina secundaria debe tener un puerto Ethernet de gestión configurado y debe estar conectada a la red.
* Las cabinas de almacenamiento local y remota se encuentran conectadas a través de una estructura Fibre Channel o una interfaz iSCSI.
* Las cabinas de almacenamiento deben tener la versión de firmware 7.84 como mínimo. (Cada una puede ejecutar versiones de sistema operativo diferentes).
* Debe conocer la contraseña de las cabinas de almacenamiento remota y local.
* Debe tener suficiente capacidad libre en la cabina de almacenamiento remota para crear un volumen secundario mayor o igual que el volumen primario que desea reflejar.
* Instaló el proxy de servicios web y Unified Manager. Las parejas reflejadas se configuran en la interfaz de Unified Manager.
* Las dos cabinas de almacenamiento se encuentran detectadas en Unified Manager.
* La cabina de almacenamiento debe contener al menos un grupo de coherencia de reflejos. El grupo de coherencia se crea en Unified Manager en el asistente Crear pareja reflejada.




== ¿Qué debo saber antes de aumentar la capacidad reservada en un volumen de parejas reflejadas?

Por lo general, se debe aumentar la capacidad reservada cuando se recibe una advertencia que indica que la capacidad reservada para una pareja reflejada está por completarse. Es posible aumentar la capacidad reservada únicamente en incrementos de 8 GIB.

Para operaciones de mirroring asíncrono, la capacidad reservada, por lo general, representa el 20 % del volumen base. Elija una capacidad mayor para capacidad reservada si existe una de las siguientes condiciones o ambas:

* Se pretende conservar la pareja reflejada por un periodo prolongado.
* Un gran porcentaje de bloques de datos cambiará en el volumen primario debido a una gran actividad de I/O. Utilice datos históricos de rendimiento u otra utilidad del sistema operativo para determinar la actividad de I/o típica del volumen primario.


Es posible aumentar la capacidad reservada para una pareja reflejada llevando a cabo una de las siguientes acciones:

* Ajuste el porcentaje de capacidad para un volumen de parejas reflejadas seleccionando MENU:almacenamiento[Pools y grupos de volúmenes] y luego haga clic en la pestaña *capacidad reservada*.
* Cree un volumen nuevo usando la capacidad libre que esté disponible en un pool o grupo de volúmenes.
+
Si no hay capacidad libre en ningún pool o grupo de volúmenes, es posible añadir capacidad sin configurar en forma de unidades sin usar a un pool o grupo de volúmenes.





== ¿Por qué no puedo aumentar la capacidad reservada con la cantidad solicitada?

Es posible aumentar la capacidad reservada únicamente en incrementos de 4 GIB.

Revise las siguientes directrices:

* Debe tener suficiente capacidad libre en el pool o el grupo de volúmenes para poder realizar una expansión si es necesario.
+
Si no hay capacidad libre en ningún pool o grupo de volúmenes, es posible añadir capacidad sin asignar en forma de unidades no utilizadas a un pool o un grupo de volúmenes.

* El volumen en el pool o el grupo de volúmenes debe tener el estado óptima y no debe estar en ningún estado de modificación.
* Debe existir capacidad libre en el pool o grupo de volúmenes que desea usar para aumentar la capacidad.


Para las operaciones de mirroring asíncrono, generalmente es el 20 % del volumen base. Use un porcentaje más alto si cree que el volumen base se someterá a muchos cambios, o si la expectativa de duración estimada de una operación de servicio de copia de un objeto de almacenamiento será muy larga.



== ¿Por qué debería cambiar este porcentaje?

En general, la capacidad reservada constituye el 40 % del volumen base para operaciones Snapshot y el 20 % del volumen base para operaciones de mirroring asíncrono.

Por lo general, esta capacidad es suficiente. La capacidad necesaria varía, según la frecuencia y el tamaño de las escrituras de I/o en el volumen base y el periodo durante el cual se pretenda utilizar la operación de servicios de copia del objeto de almacenamiento.

Por lo general, se debe seleccionar un porcentaje alto de capacidad reservada si existe una de estas condiciones, o ambas:

* Si la vida útil de la operación de servicios de copia de un objeto de almacenamiento en particular será muy prolongada.
* Si un gran porcentaje de bloques de datos cambiará en el volumen base debido a una gran actividad de I/O. Utilice los datos históricos de rendimiento u otras utilidades del sistema operativo como ayuda para determinar la actividad de I/o típica en el volumen base.




== ¿Por qué se muestra más de un candidato de capacidad reservada?

Si existe más de un volumen en un pool o grupo de volúmenes que cumple con el porcentaje de capacidad seleccionado para el objeto de almacenamiento, se mostrarán varios candidatos.

Para actualizar la lista de candidatos recomendados, es posible modificar el porcentaje de espacio de la unidad física que desea reservar en el volumen base para las operaciones de servicios de copia. Se mostrarán los mejores candidatos en función de su selección.



== ¿Por qué se muestran valores no disponibles en la tabla?

En la tabla se enumeran los valores no disponible cuando la visualización de los datos ubicados en la cabina de almacenamiento remota no se encuentra disponible.

Para visualizar los datos de la cabina de almacenamiento remota, ejecute System Manager desde Unified Manager.



== ¿Por qué no veo todos mis pools y grupos de volúmenes?

Cuando se crea un volumen secundario para la pareja reflejada asíncrona, el sistema muestra una lista de todos los pools y los grupos de volúmenes elegibles para esa pareja reflejada asíncrona. En esa lista, no se muestra ningún pool o grupo de volúmenes que no sea elegible para su uso.

Los pools o grupos de volúmenes pueden no ser elegibles por cualquiera de los motivos siguientes.

* Las funcionalidades de seguridad de un pool o un grupo de volúmenes no coinciden.
* Un pool o un grupo de volúmenes se encuentra en un estado distinto a Optimal.
* La capacidad de un pool o grupo de volúmenes es muy reducida.




== Duplicación asincrónica: ¿por qué no veo todos mis volúmenes?

Cuando se selecciona un volumen primario para una pareja reflejada, se muestra una lista con todos los volúmenes elegibles.

Si algún volumen no es apto para el uso, no se muestra en esa lista. Es posible que haya volúmenes no elegibles por alguno de los siguientes motivos:

* El volumen no está en estado óptimo.
* El volumen ya participa en una relación de mirroring.
* Para los volúmenes finos, se debe habilitar la expansión automática.



NOTE: Para las controladoras EF600 y EF300, los volúmenes primario y secundario de una pareja reflejada asíncrona deben coincidir con el mismo protocolo, nivel de soporte, tamaño de segmento, tipo de seguridad y nivel de RAID. Las parejas reflejadas asíncronas no elegibles no aparecerán en la lista de volúmenes disponibles.



== Duplicación asincrónica: ¿por qué no veo todos los volúmenes en la matriz de almacenamiento remota?

Cuando se selecciona un volumen secundario en la cabina de almacenamiento remota, se muestra una lista de todos los volúmenes elegibles para esa pareja reflejada.

Todos los volúmenes que no son elegibles no aparecen en esa lista. Es posible que los volúmenes no sean admisibles por uno de los siguientes motivos:

* El volumen no está en estado óptimo.
* El volumen ya participa en una relación de mirroring.
* Los atributos de volumen fino entre el volumen primario y el volumen secundario no coinciden.
* Si utiliza Data Assurance (DA), el volumen primario y el secundario deben tener la misma configuración DE DA.
+
** Si el volumen primario tiene la función DA habilitada, el volumen secundario también debe tenerla.
** Si el volumen primario no tiene la función DA habilitada, el volumen secundario tampoco debe tenerla.






== ¿Por qué debería actualizar la dirección IP de mi matriz de almacenamiento remota?

La dirección IP de la cabina de almacenamiento remota se actualiza cuando cambia la dirección IP de un puerto iSCSI y la cabina de almacenamiento local no puede comunicarse con la cabina de almacenamiento remota.

Cuando se establece una relación de mirroring asíncrono con una conexión iSCSI, tanto la cabina de almacenamiento remota como la local guardan un registro de la dirección IP de la cabina de almacenamiento remota en la configuración de mirroring asíncrono. Si cambia la dirección IP de un puerto iSCSI, la cabina de almacenamiento remota que intenta utilizar ese puerto se encuentra con un error de comunicación.

La cabina de almacenamiento con la dirección IP modificada envía un mensaje a cada cabina de almacenamiento remota asociada con los grupos de coherencia de reflejos configurados para reflejar a través de una conexión iSCSI. Las cabinas de almacenamiento que reciben este mensaje actualizan automáticamente su dirección IP objetivo remota.

Si la cabina de almacenamiento con la dirección IP modificada no puede enviar el mensaje entre cabinas a una cabina de almacenamiento remota, el sistema envía una alerta del problema de conectividad. Utilice la opción Actualizar dirección IP remota para volver a establecer la conexión con la cabina de almacenamiento local.
