---
permalink: sm-mirroring/remove-synchronous-mirror-relationship.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, synchronous, mirror, relationship, 
summary: Quite una pareja reflejada para eliminar la relación de reflejo del volumen primario en la cabina de almacenamiento local y el volumen secundario en la cabina de almacenamiento remota. 
---
= Quitar una relación de reflejo síncrono
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quite una pareja reflejada para eliminar la relación de reflejo del volumen primario en la cabina de almacenamiento local y el volumen secundario en la cabina de almacenamiento remota.

.Acerca de esta tarea
También se puede quitar una pareja reflejada para corregir un estado de pareja reflejada huérfana. Revise la siguiente información sobre parejas reflejadas huérfanas:

* Se crea una pareja reflejada huérfana cuando se quita un volumen miembro de un lado (local/remoto), pero no del otro lado.
* Las parejas reflejadas huérfanas se detectan cuando se restaura la comunicación dentro de la cabina.


.Pasos
. Seleccione MENU:Storage[Synchronous Mirroring].
. Seleccione la pareja reflejada que desea quitar y haga clic en el menú:tareas no comunes[Quitar].
+
Se muestra el cuadro de diálogo Eliminar relación de reflejo.

. Confirme que desea eliminar la pareja reflejada y, a continuación, haga clic en *Quitar*.


.Resultados
System Manager realiza lo siguiente:

* Elimina la relación de reflejo de la pareja reflejada en la cabina de almacenamiento local y en la cabina de almacenamiento remota.
* Devuelve el volumen primario y el volumen secundario a los volúmenes no reflejados a los que se puede acceder desde hosts.
* Actualiza el icono Mirroring síncrono con la eliminación de la pareja reflejada síncrona.

