---
permalink: sm-mirroring/workflow-for-mirroring-a-volume-synchronously.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, workflow, mirroring, synchronously, 
summary: El mirroring síncrono se debe configurar mediante el siguiente flujo de trabajo. 
---
= Flujo de trabajo para reflejar un volumen de forma síncrona
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El mirroring síncrono se debe configurar mediante el siguiente flujo de trabajo.

[NOTE]
====
Esta función no está disponible en los sistemas de almacenamiento EF600 o EF300.

====
. Realice la configuración inicial en Unified Manager:
+
.. Seleccione una cabina de almacenamiento local como el origen de la transferencia de datos.
.. Seleccione un volumen primario de la cabina de almacenamiento local.
.. Seleccione una cabina de almacenamiento remota como el destino de la transferencia de datos y, a continuación, seleccione un volumen secundario.
.. Seleccione las prioridades de sincronización y resincronización.
.. Inicie la transferencia de datos inicial desde el volumen primario hacia el volumen secundario. Según el tamaño de los volúmenes, esta transferencia inicial puede tardar varias horas.


. Compruebe el progreso de la sincronización inicial:
+
.. En Unified Manager, inicie la instancia de System Manager para la cabina local.
.. En System Manager, consulte el estado de la operación de mirroring. Cuando se complete el mirroring, el estado de la pareja reflejada será "óptimo". Las dos cabinas intentarán mantener la sincronización a través de las operaciones normales. Solo se transferirán los bloques nuevos y cambiados del volumen primario al volumen secundario.


. *Opcional:* puede cambiar la configuración de sincronización en System Manager.
+
[NOTE]
====
Como la replicación síncrona es continua, el enlace de replicación entre los dos sitios debe proporcionar funcionalidades de ancho de banda suficientes.

====

