---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: Debe configurar la cabina de almacenamiento con una contraseña de administrador para protegerla del acceso no autorizado. 
---
= Administrar la protección con contraseña
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar la cabina de almacenamiento con contraseñas para protegerla del acceso no autorizado.



== Configurar y cambiar contraseñas

Cuando inicia System Manager por primera vez, se le solicita que establezca una contraseña de administrador. Cualquier usuario que tenga la contraseña de administrador puede realizar cambios de configuración en la cabina de almacenamiento, por ejemplo, añadir, cambiar o quitar objetos o la configuración. Para establecer la contraseña de administrador durante el inicio inicial, consulte link:../san-getstarted/access-sam.html["Acceda a System Manager"].

Por razones de seguridad, puede intentar introducir una contraseña solo cinco veces antes de que la cabina de almacenamiento quede bloqueada. En este estado, la cabina de almacenamiento rechaza cualquier nuevo intento de introducir una contraseña. Se deben esperar 10 minutos para que la cabina de almacenamiento se restablezca y pueda volver a introducir una contraseña.

Además de la contraseña de administrador, la cabina de almacenamiento incluye perfiles de usuario predefinidos con uno o varios roles asignados. Para obtener más información, consulte link:../sm-settings/permissions-for-mapped-roles.html["Permisos para roles asignados"]. Los perfiles de usuario y las asignaciones no pueden cambiarse. Solo las contraseñas pueden modificarse. Si desea cambiar la contraseña de administrador u otras contraseñas de usuario, consulte link:../sm-settings/change-passwords.html["Cambiar contraseñas"].



== Vuelva a introducir contraseñas después de tiempos de espera de la sesión

El sistema solicita la contraseña una sola vez durante una misma sesión de gestión. Sin embargo, una sesión finaliza a los 30 minutos de inactividad; después de ese período, deberá introducir la contraseña otra vez. Si otro usuario que esté gestionando la misma cabina de almacenamiento desde otro cliente de gestión cambia la contraseña mientras su sesión está en progreso, se le solicitará una contraseña la próxima vez que intente realizar una operación de configuración o de vista.

Es posible ajustar el tiempo de espera de la sesión, o bien directamente pueden deshabilitarse los tiempos de espera de sesión. Consulte link:../sm-settings/manage-session-timeouts-sam.html["Gestionar los tiempos de espera de sesión"].



== Quite las unidades o la protección con contraseña

Si quita unidades protegidas con contraseña o desea deshabilitar la protección con contraseña, debe tener en cuenta lo siguiente:

* *Si quita unidades con protección por contraseña* -- la contraseña se almacena en un área reservada de cada unidad de la matriz de almacenamiento. Si se quitan todas las unidades de la cabina de almacenamiento, la contraseña ya no funciona. Para corregir esta situación, se debe volver a instalar una de las unidades originales en la cabina de almacenamiento.
* *Si desea eliminar la protección con contraseña* -- Si ya no desea que los comandos estén protegidos con contraseña, introduzca la contraseña de administrador actual y deje los cuadros de texto de la nueva contraseña en blanco.


[CAUTION]
====
Si se ejecutan comandos de configuración en una cabina de almacenamiento, se pueden producir daños graves, incluso la pérdida de datos. Por este motivo, siempre debe configurar una contraseña de administrador para la cabina de almacenamiento. Use una contraseña de administrador de al menos 15 caracteres alfanuméricos para reforzar la seguridad.

====