---
permalink: sm-interface/faq-storage-system-setup.html 
sidebar: sidebar 
keywords:  
summary: Estas preguntas frecuentes pueden ser de ayuda si solo está buscando una respuesta rápida a una pregunta. 
---
= Preguntas frecuentes sobre la configuración del sistema de almacenamiento para SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Estas preguntas frecuentes pueden ser de ayuda si solo está buscando una respuesta rápida a una pregunta.



== ¿Qué pasa si no veo todos mis componentes de hardware?

Si no se ven todos los componentes de hardware en el cuadro de diálogo verificar hardware, es posible que una bandeja de unidades no esté conectada correctamente o que se haya instalado una bandeja incompatible en la cabina de almacenamiento.

Verifique que se hayan conectado correctamente todas las bandejas de unidades. Si no está seguro de cuáles bandejas de unidades son compatibles, póngase en contacto con el soporte técnico.



== ¿Qué pasa si no veo todos mis hosts?

Si no se observan los hosts conectados, hay un error en la detección automática, los hosts están conectados incorrectamente o no hay hosts conectados actualmente.

Es posible configurar los hosts más adelante, después de completar la configuración. Es posible crear hosts manualmente de la siguiente manera:

* Es posible crear hosts manualmente y asociarlos con los identificadores de puerto de host adecuados en menu:Storage[hosts]. Los hosts que se han creado manualmente también aparecen en el asistente *Configuración inicial*.
* El objetivo y el host deben configurarse para el tipo de puerto de host (por ejemplo, iSCSI o NVMe over roce), y debe establecerse una sesión en el almacenamiento para que la detección automática funcione.




== ¿Cómo ayuda la identificación de aplicaciones a gestionar la cabina de almacenamiento?

Cuando se identifican aplicaciones, System Manager de SANtricity recomienda automáticamente una configuración de volumen que optimiza el almacenamiento según el tipo de aplicación.

La optimización de volúmenes por aplicación puede aumentar la eficiencia de las operaciones de almacenamiento de datos. Las características como el tipo de I/o, el tamaño de segmento, la propiedad de controladora y la caché de lectura y escritura se incluyen en la configuración de volumen. Además, es posible visualizar datos de rendimiento por aplicación y por carga de trabajo para evaluar la latencia, las I/o por segundo y los MIB/seg de aplicaciones y de sus cargas de trabajo asociadas.



== ¿Qué es una carga de trabajo?

Para algunas aplicaciones de la red, como SQL Server o Exchange, es posible definir una carga de trabajo que optimice el almacenamiento para esa aplicación.

Una carga de trabajo es un objeto de almacenamiento que admite una aplicación. Se pueden definir una o más cargas de trabajo o instancias por aplicación. En algunas aplicaciones, el sistema configura la carga de trabajo para contener volúmenes con características subyacentes similares. Estas características de volumen se optimizan según el tipo de aplicación que es compatible con la carga de trabajo. Por ejemplo, si crea una carga de trabajo que es compatible con la aplicación Microsoft SQL Server y, a continuación, crea volúmenes para esa carga de trabajo, las características de volumen subyacentes se optimizan para ser compatibles con Microsoft SQL Server.

Durante la creación de un volumen, el sistema indica que se deben responder preguntas acerca del uso de las cargas de trabajo. Por ejemplo, si se crean volúmenes para Microsoft Exchange, se consultará cuántos buzones se necesitan, cuáles son los requisitos de capacidad promedio del buzón y cuántas copias de la base de datos se desean. El sistema utiliza esta información para crear una configuración de volumen óptima para el usuario, que se puede editar en caso de ser necesario.



== ¿Cómo se configura el método de entrega para AutoSupport?

Para acceder a las tareas de configuración de los métodos de entrega de AutoSupport, vaya al menú:Soporte[Centro de soporte] y, a continuación, haga clic en la ficha *AutoSupport*.

Se admiten los siguientes protocolos: HTTPS y SMTP.



== ¿Cómo saber si debe aceptarse la configuración de pool recomendada?

Si se acepta la configuración de pool recomendada depende de unos pocos factores.

Para determinar el tipo de almacenamiento que es mejor para sus requisitos, responda estas preguntas:

* ¿Prefiere varios pools de menor capacidad en lugar de pools con la mayor capacidad posible?
* ¿Prefiere grupos de volúmenes RAID en lugar de pools?
* ¿Prefiere aprovisionar manualmente las unidades en lugar de que le recomienden una configuración?


Si respondió afirmativamente a cualquiera de esas preguntas, considere rechazar la configuración de pool recomendada.



== System Manager de SANtricity no detectó ningún host. ¿Qué debo hacer?

Si no se observan los hosts conectados, hay un error en la detección automática, los hosts están conectados incorrectamente o no hay hosts conectados actualmente.

Es posible configurar los hosts más adelante, después de completar la configuración. Es posible crear hosts manualmente de la siguiente manera:

* Es posible crear hosts manualmente y asociarlos con los identificadores de puerto de host adecuados en menu:Storage[hosts]. Los hosts que se han creado manualmente también aparecen en el asistente *Configuración inicial*.
* El objetivo y el host deben configurarse para el tipo de puerto de host (por ejemplo, iSCSI o NVMe over roce), y debe establecerse una sesión en el almacenamiento para que la detección automática funcione.

