---
permalink: sm-interface/home-page.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, home page 
summary: La página Inicio ofrece una vista de consola para la gestión cotidiana de la cabina de almacenamiento. Cuando se inicia sesión en System Manager, la página Inicio es la primera pantalla que aparece. 
---
= Página de inicio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La página Inicio ofrece una vista de consola para la gestión cotidiana de la cabina de almacenamiento. Cuando se inicia sesión en System Manager, la página Inicio es la primera pantalla que aparece.

La vista de consola incluye cuatro áreas de resumen que contienen información clave sobre el estado y la condición de la cabina de almacenamiento. Es posible encontrar más información en el área de resumen.

* *Notificaciones*
+
El área de notificaciones muestra notificaciones de problemas que indican el estado de la cabina de almacenamiento y sus componentes. Además, este portlet muestra alertas automatizadas que pueden ayudarle a resolver problemas antes de que afecten a otras áreas de su entorno de almacenamiento.

* *Rendimiento*
+
El área de rendimiento permite comparar y contrastar el uso de recursos a lo largo del tiempo. Es posible ver las métricas de rendimiento de una cabina de almacenamiento relacionadas con el tiempo de respuesta (IOPS), las tasas de transferencia (MIB/s) y la cantidad de capacidad de procesamiento que se utiliza (CPU).

* *Capacidad*
+
El área de capacidad muestra una vista de gráfico de la capacidad asignada, la capacidad de almacenamiento libre y la capacidad de almacenamiento sin asignar en la cabina de almacenamiento.

* *Jerarquía de almacenamiento*
+
El área de jerarquía de almacenamiento ofrece una vista organizada de los distintos componentes de hardware y objetos de almacenamiento gestionados por la cabina de almacenamiento. Haga clic en la flecha desplegable para realizar una determinada acción en ese componente de hardware u objeto de almacenamiento.


