---
permalink: sm-interface/overview-interface-sam.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: Se accede a la interfaz principal para acceder a las funciones y tareas de System Manager. 
---
= Conozca la interfaz de SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager de SANtricity es una interfaz basada en Web que permite gestionar una cabina de almacenamiento en una sola vista.



== Página de inicio

La página Inicio ofrece una vista de consola para la gestión cotidiana de la cabina de almacenamiento. Cuando se inicia sesión en System Manager, la página Inicio es la primera pantalla que aparece.

La vista de consola comprende tres áreas de resumen que contienen información clave sobre el estado y la salud de tu matriz de almacenamiento. Puedes encontrar más información en el área de resumen.

[cols="25h,~"]
|===
| Zona | Descripción 


 a| 
Rendimiento
 a| 
El área de rendimiento permite comparar y contrastar el uso de recursos a lo largo del tiempo. Es posible ver las métricas de rendimiento de una cabina de almacenamiento relacionadas con el tiempo de respuesta (IOPS), las tasas de transferencia (MIB/s) y la cantidad de capacidad de procesamiento que se utiliza (CPU).



 a| 
Capacidad
 a| 
El área de capacidad muestra una vista de gráfico de la capacidad asignada, la capacidad de almacenamiento libre y la capacidad de almacenamiento sin asignar en la cabina de almacenamiento.



 a| 
Jerarquía de almacenamiento
 a| 
El área de jerarquía de almacenamiento ofrece una vista organizada de los distintos componentes de hardware y objetos de almacenamiento gestionados por la cabina de almacenamiento. Haga clic en la flecha desplegable para realizar una determinada acción en ese componente de hardware u objeto de almacenamiento.

|===


== Área de notificaciones

El área de Notificaciones está disponible a través del icono de campana en la esquina superior de la ventana. El área de Notificaciones muestra notificaciones de problemas que indican el estado de la matriz de almacenamiento y sus componentes. Además, esta sección muestra alertas automatizadas que pueden ayudarte a solucionar problemas antes de que afecten a otras áreas de tu entorno de almacenamiento.



== Configuración de la interfaz

Puede cambiar las preferencias de presentación y otras configuraciones desde la interfaz principal.



== Inicios de sesión y contraseñas de usuario

El usuario actual que ha iniciado sesión en el sistema se muestra en la configuración de usuario.

Para obtener más información sobre usuarios y contraseñas, consulte:

* link:administrator-password-protection.html["Configure la protección con contraseña de administrador"]
* link:../sm-settings/change-passwords.html["Cambiar contraseñas"]

