---
permalink: sm-interface/what-is-a-workload.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, workload 
summary: Para algunas aplicaciones de la red, como SQL Server o Exchange, es posible definir una carga de trabajo que optimice el almacenamiento para esa aplicación. 
---
= ¿Qué es una carga de trabajo?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para algunas aplicaciones de la red, como SQL Server o Exchange, es posible definir una carga de trabajo que optimice el almacenamiento para esa aplicación.

Una carga de trabajo es un objeto de almacenamiento que admite una aplicación. Se pueden definir una o más cargas de trabajo o instancias por aplicación. En algunas aplicaciones, el sistema configura la carga de trabajo para contener volúmenes con características subyacentes similares. Estas características de volumen se optimizan según el tipo de aplicación que es compatible con la carga de trabajo. Por ejemplo, si crea una carga de trabajo que es compatible con la aplicación Microsoft SQL Server y, a continuación, crea volúmenes para esa carga de trabajo, las características de volumen subyacentes se optimizan para ser compatibles con Microsoft SQL Server.

Durante la creación de un volumen, el sistema indica que se deben responder preguntas acerca del uso de las cargas de trabajo. Por ejemplo, si se crean volúmenes para Microsoft Exchange, se consultará cuántos buzones se necesitan, cuáles son los requisitos de capacidad promedio del buzón y cuántas copias de la base de datos se desean. El sistema utiliza esta información para crear una configuración de volumen óptima para el usuario, que se puede editar en caso de ser necesario.
