---
permalink: sm-hardware/faq-storage-shelf.html 
sidebar: sidebar 
keywords:  
summary: Estas preguntas frecuentes pueden ser de ayuda si solo está buscando una respuesta rápida a una pregunta. 
---
= Preguntas frecuentes sobre estantes de almacenamiento para SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Estas preguntas frecuentes pueden ser de ayuda si solo está buscando una respuesta rápida a una pregunta.



== ¿Qué son la protección contra pérdida de bandeja y la protección contra pérdida de cajón?

La protección contra pérdida de bandeja y de cajón son atributos de los pools y los grupos de volúmenes para mantener el acceso a los datos en caso de fallo de una bandeja o un cajón individuales.



=== Protección contra pérdida de bandeja

Una bandeja es el compartimento que contiene las unidades o las unidades y la controladora. La protección contra pérdida de bandeja garantiza la accesibilidad a los datos en los volúmenes de un pool o un grupo de volúmenes en caso de pérdida total de comunicación con una bandeja de unidades única. Un ejemplo de pérdida total de comunicación podría ser la pérdida de energía en la bandeja de unidades o el fallo de ambos módulos de I/o (IOM).

[NOTE]
====
La protección contra pérdida de bandeja no está garantizada si una unidad ya falló en el pool o en el grupo de volúmenes. En este caso, la pérdida de acceso a la bandeja de unidades y, en consecuencia, a otra unidad en el pool o el grupo de volúmenes provoca la pérdida de datos.

====
El criterio de protección contra pérdida de bandeja depende del método de protección, tal como se describe en la tabla siguiente:

[cols="1a,1a,1a"]
|===
| Nivel | Criterios para la protección contra pérdida de bandeja | Cantidad mínima requerida de bandejas 


 a| 
Piscina
 a| 
El pool debe incluir unidades de al menos cinco bandejas y debe haber la misma cantidad de unidades en cada bandeja. La protección contra pérdida de bandeja no es aplicable a las bandejas de gran capacidad; si el sistema incluye bandejas de gran capacidad, consulte la protección contra pérdida de cajón.
 a| 
5



 a| 
RAID 6
 a| 
El grupo de volúmenes consta de dos unidades como máximo en una sola bandeja.
 a| 
3



 a| 
RAID 3 o RAID 5
 a| 
Cada unidad del grupo de volúmenes se encuentra en una bandeja aparte.
 a| 
3



 a| 
RAID 1
 a| 
Cada unidad de una pareja RAID 1 se debe ubicar en una bandeja aparte.
 a| 
2



 a| 
RAID 0
 a| 
No puede contar con protección contra pérdida de bandeja.
 a| 
No aplicable

|===


=== Protección contra pérdida de cajón

Un cajón es uno de los compartimentos de una bandeja que se extrae para acceder a las unidades. Solo las bandejas de gran capacidad poseen cajones. La protección contra pérdida de cajón garantiza la accesibilidad a los datos en los volúmenes de un pool o un grupo de volúmenes en caso de pérdida total de comunicación con un cajón único. Un ejemplo de pérdida total de comunicación podría ser la pérdida de energía en el cajón o el fallo de un componente interno dentro del cajón.

[NOTE]
====
La protección contra pérdida de cajón no está garantizada si una unidad ya falló en el pool o en el grupo de volúmenes. En este caso, la pérdida de acceso al cajón (y, en consecuencia, a otra unidad en el pool o el grupo de volúmenes) provoca la pérdida de datos.

====
El criterio de protección contra pérdida de cajón depende del método de protección, tal como se describe en la tabla siguiente:

[cols="1a,1a,1a"]
|===
| Nivel | Criterios para la protección contra pérdida de cajón | Cantidad mínima requerida de cajones 


 a| 
Piscina
 a| 
Los candidatos de pool deben incluir unidades de todos los cajones y debe haber la misma cantidad de unidades por cajón.

El pool debe incluir unidades de al menos cinco cajones y debe haber la misma cantidad de unidades por cajón.

Una bandeja de 60 unidades puede contar con protección contra pérdida de cajón cuando el pool consta de 15, 20, 25, 30, 35, 40, 45, 50, 55 o 60 unidades. Los incrementos en múltiplos de 5 se pueden agregar al pool después de la creación inicial.
 a| 
5



 a| 
RAID 6
 a| 
El grupo de volúmenes consta de dos unidades como máximo en un solo cajón.
 a| 
3



 a| 
RAID 3 o RAID 5
 a| 
Cada unidad del grupo de volúmenes se encuentra en un cajón aparte.
 a| 
3



 a| 
RAID 1
 a| 
Cada unidad de una pareja reflejada se debe ubicar en un cajón aparte.
 a| 
2



 a| 
RAID 0
 a| 
No puede contar con protección contra pérdida de cajón.
 a| 
No aplicable

|===


== ¿Qué son los ciclos de aprendizaje de la batería?

Un ciclo de aprendizaje es un ciclo automático para calibrar el indicador de batería inteligente.

Un ciclo de aprendizaje consta de las siguientes fases:

* Descarga controlada de batería
* Periodo de descanso
* Carga


Las baterías se descargan hasta un umbral predeterminado. Durante esta fase, se calibra el indicador de batería.

Un ciclo de aprendizaje requiere los siguientes parámetros:

* Baterías totalmente cargadas
* Baterías que no estén sobrecalentadas


Los ciclos de aprendizaje para sistemas de controladoras dobles se ejecutan simultáneamente. Para controladoras que tienen alimentación de backup de varias baterías o conjuntos de celdas de batería, los ciclos de aprendizaje se ejecutan secuencialmente.

Los ciclos de aprendizaje se programan para comenzar automáticamente en intervalos regulares, a la misma hora y el mismo día de la semana. El intervalo entre los ciclos se describe en semanas.

[NOTE]
====
Un ciclo de aprendizaje podría demorar varias horas para completarse.

====