---
permalink: sm-hardware/place-controller-in-service-mode.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, place, controller, service, mode, 
summary: Si se le indica hacerlo, puede colocar una controladora en modo de servicio. 
---
= Colocar una controladora en modo de servicio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si se le indica hacerlo, puede colocar una controladora en modo de servicio.

.Antes de empezar
* La cabina de almacenamiento debe tener dos controladoras. La controladora que no se coloca en modo de servicio debe estar en línea (en el estado óptimo).
* Asegúrese de que no existan volúmenes en uso o que exista un controlador multivía instalado en todos los hosts que utilizan estos volúmenes.


[NOTE]
====
La colocación de una controladora en modo de servicio puede reducir considerablemente el rendimiento. No coloque una controladora en modo de servicio a menos que el soporte técnico le indique hacerlo.

====
.Pasos
. Seleccione *hardware*.
. Si el gráfico muestra las unidades, haga clic en *Mostrar parte posterior de la bandeja*.
+
El gráfico cambia y muestra las controladoras en lugar de las unidades.

. Haga clic en la controladora que desea colocar en modo de servicio.
+
Aparece el menú contextual de la controladora.

. Seleccione *colocar en modo de servicio* y confirme que desea realizar la operación.

