---
permalink: sm-hardware/place-controller-offline.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, place, controller, offline, 
summary: Si se le indica hacerlo, puede colocar una controladora en estado sin conexión. 
---
= Coloque una controladora en estado sin conexión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si se le indica hacerlo, puede colocar una controladora en estado sin conexión.

.Antes de empezar
* Una cabina de almacenamiento debe tener dos controladoras. La controladora que no se coloca en estado sin conexión debe estar en línea (en el estado óptimo).
* Asegúrese de que no existan volúmenes en uso o que exista un controlador multivía instalado en todos los hosts que utilizan estos volúmenes.


.Acerca de esta tarea
++ ++

[CAUTION]
====
No coloque una controladora en estado sin conexión a menos que el soporte técnico o Recovery Guru le indique hacerlo.

====
.Pasos
. Seleccione *hardware*.
. Si el gráfico muestra las unidades, haga clic en *Mostrar parte posterior de la bandeja*.
+
El gráfico cambia y muestra las controladoras en lugar de las unidades.

. Haga clic en la controladora que desea colocar en estado sin conexión.
+
Aparece el menú contextual de la controladora.

. Seleccione *colocar fuera de línea* y confirme que desea realizar la operación.


.Resultados
Es posible que System Manager demore varios minutos en actualizar el estado de la controladora a sin conexión. No inicie ninguna otra operación hasta que se haya actualizado el estado.
