---
permalink: um-manage/why-dont-i-see-all-the-volumes-on-the-remote-storage-array-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, volumes missing 
summary: Cuando se selecciona un volumen secundario en la cabina de almacenamiento remota, se muestra una lista de todos los volúmenes elegibles para esa pareja reflejada. 
---
= ¿Por qué no se muestran todos los volúmenes en la cabina de almacenamiento remota?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se selecciona un volumen secundario en la cabina de almacenamiento remota, se muestra una lista de todos los volúmenes elegibles para esa pareja reflejada.

Todos los volúmenes que no son elegibles no aparecen en esa lista. Es posible que haya volúmenes no elegibles por alguno de los siguientes motivos:

* El volumen no es estándar, por ejemplo, un volumen Snapshot.
* El volumen no está en estado óptimo.
* El volumen ya participa en una relación de mirroring.
* Para el mirroring asíncrono, los atributos de volumen fino entre el volumen primario y el volumen secundario no coinciden.
* Si utiliza Data Assurance (DA), el volumen primario y el secundario deben tener la misma configuración DE DA.
+
** Si el volumen primario tiene la función DA habilitada, el volumen secundario también debe tenerla.
** Si el volumen primario no tiene la función DA habilitada, el volumen secundario tampoco debe tenerla.


* Para el mirroring asíncrono, el volumen primario y el volumen secundario deben tener las mismas capacidades Drive Security.
+
** Si el volumen primario es compatible con FIPS, el volumen secundario debe ser compatible con FIPS.
** Si el volumen primario es compatible con FDE, el volumen secundario debe ser compatible con FDE.
** Si el volumen primario no utiliza Drive Security, el volumen secundario no debe usar Drive Security.



