---
permalink: sm-settings/access-management-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, terms 
summary: Conozca la forma en que los términos de Access Management se aplican a su cabina de almacenamiento. 
---
= Terminología de Access Management
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conozca la forma en que los términos de Access Management se aplican a su cabina de almacenamiento.

[cols="25h,~"]
|===
| Duración | Descripción 


 a| 
Token de acceso
 a| 
Los tokens de acceso se utilizan para la autenticación con la API DE REST o la interfaz de línea de comandos (CLI) en lugar de un nombre de usuario y una contraseña. Los tokens están asociados a un usuario específico (incluidos los usuarios LDAP) e incluyen un conjunto de permisos y una caducidad.



 a| 
Active Directory
 a| 
Active Directory (AD) es un servicio de directorio de Microsoft en el que se utiliza LDAP para redes de dominio de Windows.



 a| 
Vinculación
 a| 
Las operaciones de vinculación se usan para autenticar clientes en el servidor de directorio. Por lo general, la vinculación requiere credenciales de cuenta y contraseña, pero algunos servidores aceptan operaciones de vinculación anónimas.



 a| 
APROX
 a| 
Una entidad de certificación (CA) es una entidad de confianza que emite documentos electrónicos, denominados certificados digitales, para la seguridad de Internet. Estos certificados identifican a los propietarios de sitios web y, de esta manera, permiten conexiones seguras entre clientes y servidores.



 a| 
Certificado
 a| 
Un certificado identifica al propietario de un sitio con el fin de brindar seguridad, para evitar que atacantes se hagan pasar por los propietarios del sitio. El certificado tiene información acerca del propietario del sitio y la identidad de la entidad de confianza que certifica (firma) esta información.



 a| 
IDP
 a| 
Un proveedor de identidades (IDP) es un sistema externo que se usa para solicitar credenciales a un usuario y para determinar si el usuario se autentica correctamente. El IDP se puede configurar para ofrecer autenticación multifactor y para usar cualquier base de datos de usuario, como Active Directory. El equipo de seguridad es responsable de mantener el IDP.



 a| 
LDAP
 a| 
El protocolo ligero de acceso a directorios (LDAP) es un protocolo de aplicación para acceder a servicios distribuidos de información de directorio y mantenerlos. Este protocolo permite que varias aplicaciones y servicios se conecten con el servidor LDAP para validar usuarios.



 a| 
RBAC
 a| 
El control de acceso basado en funciones (RBAC) es un método para regular el acceso a los recursos informáticos o de red en función de las funciones de los usuarios individuales. Los controles de RBAC se aplican en la cabina de almacenamiento y se componen de roles predefinidos.



 a| 
SAML
 a| 
El lenguaje de marcado de aserción de seguridad (SAML) es un estándar basado en XML para fines de autenticación y autorización entre dos entidades. SAML permite utilizar la autenticación multifactor, en la cual los usuarios deben introducir dos o más elementos para validar su identidad (por ejemplo, una contraseña y una huella digital). La función de SAML integrada de la cabina de almacenamiento es compatible con SAML2.0 para autenticación, autorización y confirmación de identidades.



 a| 
SP
 a| 
Un proveedor de servicios (SP) es un sistema que controla la autenticación y el acceso de usuario. Cuando se configura Access Management con SAML, la cabina de almacenamiento actúa como proveedor de servicios, ya que solicita la autenticación del proveedor de identidades.



 a| 
SSO
 a| 
El inicio de sesión único (SSO) es un servicio de autenticación que permite el uso de un conjunto de credenciales de inicio de sesión para acceder a varias aplicaciones.

|===