---
permalink: sm-settings/change-passwords.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, passwords, user, passwords, 
summary: Es posible cambiar las contraseñas de usuario de cada perfil de usuario desde Access Management. 
---
= Cambiar contraseñas
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar las contraseñas de usuario de cada perfil de usuario desde Access Management.

.Antes de empezar
* Inició sesión como administrador local, lo que incluye permisos de administrador raíz.
* Debe conocer la contraseña de administrador local.


.Acerca de esta tarea
Tenga en cuenta estas directrices al elegir una contraseña:

* Todas las contraseñas de usuarios locales nuevas deben alcanzar o superar la configuración de longitud mínima actual de la contraseña (en Ver/editar configuración).
* Las contraseñas distinguen mayúsculas de minúsculas.
* Los espacios al final de la contraseña no se eliminan, si se los utiliza. Procure incluir espacios si se incluyeron en la contraseña.
* Para mayor seguridad, use al menos 15 caracteres alfanuméricos y cambie la contraseña con frecuencia.


[NOTE]
====
Cuando se cambia la contraseña en System Manager también se modifica en la interfaz de línea de comandos (CLI). Además, los cambios de contraseña provocan el cierre de la sesión activa del usuario.

====
.Pasos
. Seleccione MENU:Settings[Access Management].
. Seleccione la ficha *roles de usuario local*.
. Seleccione un usuario de la tabla.
+
Se habilita el botón Cambiar contraseña.

. Seleccione *Cambiar contraseña*.
+
Se abre el cuadro de diálogo Cambiar contraseña.

. Si no se estableció una longitud de contraseña mínima para las contraseñas de usuario local, se puede marcar la casilla para solicitar que el usuario seleccionado introduzca una contraseña para acceder a la cabina de almacenamiento y, a continuación, se puede escribir la contraseña nueva para el usuario seleccionado.
. Introduzca su contraseña de administrador local y, a continuación, haga clic en *Cambiar*.


.Resultados
Si el usuario está conectado, el cambio de contraseña provocará el cierre de la sesión activa del usuario.
