---
permalink: sm-settings/change-local-user-passwords-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, local, user, password, settings, 
summary: Es posible configurar la longitud mínima requerida para todas las contraseñas de usuario locales nuevas o actualizadas de la cabina de almacenamiento. También es posible permitir a los usuarios locales acceder a la cabina de almacenamiento sin introducir una contraseña. 
---
= Cambie la configuración de contraseña de usuario local
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible configurar la longitud mínima requerida para todas las contraseñas de usuario locales nuevas o actualizadas de la cabina de almacenamiento. También es posible permitir a los usuarios locales acceder a la cabina de almacenamiento sin introducir una contraseña.

.Antes de empezar
Inició sesión como administrador local, lo que incluye permisos de administrador raíz.

.Acerca de esta tarea
Recuerde estas directrices cuando configure la longitud mínima para las contraseñas de usuario local:

* Los cambios en la configuración no afectan a las contraseñas existentes de usuarios locales.
* La configuración de la longitud mínima requerida para las contraseñas de usuario local debe tener entre 0 y 30 caracteres.
* Todas las contraseñas de usuario local nuevas deben alcanzar o superar la configuración de longitud mínima actual.
* No configure una longitud mínima para la contraseña si no desea que usuarios locales accedan a la cabina de almacenamiento sin introducir una contraseña.


.Pasos
. Seleccione MENU:Settings[Access Management].
. Seleccione la ficha *roles de usuario local*.
. Seleccione el botón *Ver/editar configuración*.
+
Se abre el cuadro de diálogo Configuración de contraseña de usuario local.

. Debe realizar una de las siguientes acciones:
+
** Para permitir a los usuarios locales acceder a la cabina de almacenamiento _sin_ introducir una contraseña, desactive la casilla de comprobación "require all local user passwords to be at least".
** Para configurar una longitud mínima de contraseña para todas las contraseñas de usuarios locales, active la casilla de comprobación "require all local user passwords to be at least" y luego use el cuadro de desplazamiento para configurar la longitud mínima requerida para todas las contraseñas de usuarios locales.
+
Todas las contraseñas de usuario local nuevas deben alcanzar o superar la configuración actual.



. Haga clic en *Guardar*.

