---
permalink: sm-settings/change-saml-role-mappings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, saml, role, mappings, 
summary: Si anteriormente configuró SAML para Access Management, puede cambiar las asignaciones de roles entre los grupos IDP y los roles predefinidos de la cabina de almacenamiento. 
---
= Cambiar las asignaciones de roles SAML
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si anteriormente configuró SAML para Access Management, puede cambiar las asignaciones de roles entre los grupos IDP y los roles predefinidos de la cabina de almacenamiento.

.Antes de empezar
* Debe iniciar sesión con un perfil de usuario que cuente con permisos de administración de seguridad. De lo contrario, no se mostrarán las funciones de Access Management.
* Un administrador IDP configuró los atributos del usuario y la pertenencia al grupo en el sistema IDP.
* SAML debe estar configurado y habilitado.


.Pasos
. Seleccione MENU:Settings[Access Management].
. Seleccione la pestaña *SAML*.
. Seleccione *asignación de roles*.
+
Se abre el cuadro de diálogo asignación de roles.

. Asigne los grupos y atributos de usuario IDP a los roles predefinidos. Un grupo puede tener varios roles asignados.
+
[CAUTION]
====
Tenga cuidado de no quitar los permisos mientras SAML está habilitado; de lo contrario, perderá el acceso a System Manager.

====
+
.Detalles del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Ajuste | Descripción 


 a| 
*Asignaciones*



 a| 
Atributo de usuario
 a| 
Especifique un atributo (por ejemplo, "miembro de") para el grupo SAML que será asignado.



 a| 
Valor de atributo
 a| 
Especifique el valor de atributo para el grupo que será asignado.



 a| 
Funciones
 a| 
Haga clic en el campo y seleccione uno de los roles de la cabina de almacenamiento que se asignará al atributo. Debe seleccionar individualmente cada rol que desee incluir en este grupo. Se necesita el rol de supervisión en combinación con los demás roles para iniciar sesión en System Manager. También se debe asignar el rol de administración de seguridad al menos a un grupo. Los roles asignados incluyen los siguientes permisos:

** *Storage admin* -- acceso completo de lectura/escritura a los objetos de almacenamiento (por ejemplo, volúmenes y pools de discos), pero sin acceso a la configuración de seguridad.
** *Administración de seguridad* -- acceso a la configuración de seguridad en Access Management, administración de certificados, administración de registros de auditoría y la capacidad de activar o desactivar la interfaz de administración heredada (Symbol).
** *Support admin* -- acceso a todos los recursos de hardware en la cabina de almacenamiento, datos de fallos, eventos MEL y actualizaciones del firmware de la controladora. No brinda acceso a los objetos de almacenamiento ni a la configuración de seguridad.
** *Monitor* -- acceso de sólo lectura a todos los objetos de almacenamiento, pero sin acceso a la configuración de seguridad.


|===
====
+

NOTE: El rol de supervisión se requiere para todos los usuarios, incluido el administrador. System Manager no funcionará correctamente para los usuarios que no tengan el rol de supervisión.

. Opcionalmente, haga clic en *Agregar otra asignación* para introducir más asignaciones de grupo a rol.
. Haga clic en *Guardar*.


.Resultados
Una vez finalizada esta tarea, se finalizarán todas las sesiones de usuario activas. Solo se mantiene la sesión de usuario actual.
