---
permalink: sm-settings/default-host-operating-system-type.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, default, host, operating, system, 
summary: La cabina de almacenamiento utiliza el tipo de host predeterminado cuando se conectan inicialmente los hosts. Define la manera en que funcionan las controladoras en la cabina de almacenamiento con el sistema operativo del host cuando se accede a los volúmenes. 
---
= Obtenga información sobre el tipo de sistema operativo host predeterminado en el software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La cabina de almacenamiento utiliza el tipo de host predeterminado cuando se conectan inicialmente los hosts. Define la manera en que funcionan las controladoras en la cabina de almacenamiento con el sistema operativo del host cuando se accede a los volúmenes.

Es posible cambiar el tipo de host si hay una necesidad de cambiar la manera en que opera la cabina de almacenamiento en relación con los hosts que están conectados con ella. En general, se debe cambiar el tipo de host predeterminado antes de conectar hosts a la cabina de almacenamiento o al añadir hosts adicionales.

Tenga en cuenta estas directrices:

* Si todos los hosts que piensa conectar a la cabina de almacenamiento tienen el mismo sistema operativo (entorno de host homogéneo), cambie el tipo de host para que coincida con el sistema operativo.
* Si hay hosts con diferentes sistemas operativos que piensa conectar a la cabina de almacenamiento (entorno de host heterogéneo), cambie el tipo de host para que coincida con la mayoría de los sistemas operativos de los hosts.
+
Por ejemplo, si va a conectar ocho hosts diferentes a la cabina de almacenamiento y seis de ellos tienen un sistema operativo Windows, debe seleccionar Windows como tipo de sistema operativo de host predeterminado.

* Si la mayoría de los hosts conectados poseen una combinación de sistemas operativos diferentes, cambie el tipo de host a opción predeterminada de fábrica.
+
Por ejemplo, si va a conectar ocho hosts diferentes a la cabina de almacenamiento y dos de ellos tienen un sistema operativo Windows, tres ejecutan un sistema operativo VMware, Y otros tres ejecutan un sistema operativo Linux, debe seleccionar opción predeterminada de fábrica como el tipo de sistema operativo del host predeterminado.


