---
permalink: sm-settings/edit-storage-array-name.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, storage array, name, 
summary: Es posible cambiar el nombre de la cabina de almacenamiento que aparece en la barra de título de SANtricity System Manager. 
---
= Edite el nombre de la cabina de almacenamiento
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar el nombre de la cabina de almacenamiento que aparece en la barra de título de SANtricity System Manager.

.Pasos
. Seleccione MENU:Settings[System].
. En *General*, busque el campo *Nombre:*.
+
Si no se definió un nombre de cabina de almacenamiento, este campo muestra el texto "Unknown".

. Haga clic en el icono *Editar* (lápiz) ubicado junto al nombre de la cabina de almacenamiento.
+
Ahora el campo puede editarse.

. Introduzca un nombre nuevo.
+
Un nombre puede contener letras, números y los caracteres especiales subrayado (_), guión (-) y signo numeral (#). Un nombre no puede contener espacios. Un nombre puede contener un máximo de 30 caracteres. El nombre debe ser único.

. Haga clic en el icono *Guardar* (Marca de verificación).
+
[NOTE]
====
Si desea cerrar el campo editable sin realizar cambios, haga clic en el icono *Cancelar* (X).

====


.Resultados
El nuevo nombre aparecerá en la barra de título de SANtricity System Manager.
