---
permalink: sm-settings/edit-mail-server-for-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, mail, server, alerts, 
summary: Es posible cambiar la dirección del servidor de correo y la dirección del remitente de correo utilizada para las alertas por correo electrónico. 
---
= Editar servidor de correo para alertas
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar la dirección del servidor de correo y la dirección del remitente de correo utilizada para las alertas por correo electrónico.

.Antes de empezar
La dirección del servidor de correo que desea cambiar debe estar disponible. La dirección puede ser IPv4 o IPv6, o bien un nombre de dominio completo.

[NOTE]
====
Para usar un nombre de dominio completo, debe configurar un servidor DNS en ambas controladoras. Es posible configurar un servidor DNS desde la página hardware.

====
.Pasos
. Seleccione MENU:Settings[Alerts].
. Seleccione la ficha *correo electrónico*.
. Seleccione *Configurar el servidor de correo*.
+
Se abre el cuadro de diálogo Configurar el servidor de correo.

. Edite la dirección del servidor de correo, la información del remitente y la información de contacto.
+
** *Dirección del servidor de correo* -- edite el nombre de dominio completo, la dirección IPv4 o la dirección IPv6 del servidor de correo.
+
[NOTE]
====
Para usar un nombre de dominio completo, debe configurar un servidor DNS en ambas controladoras. Es posible configurar un servidor DNS desde la página hardware.

====
** *Dirección del remitente de correo electrónico* -- edite la dirección de correo electrónico que se utilizará como remitente del correo electrónico. Esta dirección aparece en el campo "de" del mensaje de correo electrónico.
** *Incluir información de contacto en el correo electrónico* -- para editar la información de contacto del remitente, seleccione esta opción y, a continuación, edite el nombre y el número de teléfono.


. Haga clic en *Guardar*.

