---
permalink: sm-settings/enable-or-disable-resource-provisioning-for-new-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, disable, resource, provisioning, 
summary: Si anteriormente deshabilitó la función predeterminada para el aprovisionamiento de recursos, puede ir a Configuración y volver a habilitarla para todos los grupos de volúmenes SSD o pools nuevos que cree. También puede desactivar de nuevo el ajuste. 
---
= Habilitar o deshabilitar el aprovisionamiento de recursos para nuevos grupos de volúmenes o pools
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si anteriormente deshabilitó la función predeterminada para el aprovisionamiento de recursos, puede volver a habilitarla para todos los grupos de volúmenes SSD o pools nuevos que cree. También puede desactivar de nuevo el ajuste.

El aprovisionamiento de recursos es una función disponible en las cabinas de almacenamiento EF300 y EF600, lo que permite poner en uso los volúmenes de inmediato sin proceso de inicialización en segundo plano. Todos los bloques de unidades asignados al volumen no se asignan (desasignan), es posible mejorar la vida útil de las unidades de estado sólido y aumentar el rendimiento de escritura máximo.


NOTE: De forma predeterminada, el aprovisionamiento de recursos está habilitado en sistemas donde las unidades admiten DULBE.

.Antes de empezar
* Debe tener una cabina de almacenamiento EF300 o EF600.
* Debe tener grupos de volúmenes SSD o pools, donde todas las unidades admiten la funcionalidad de recuperación de error de bloque lógico no escrito o desasignado (DULBE).


.Acerca de esta tarea
Cuando se vuelve a habilitar el aprovisionamiento de recursos para nuevos grupos de volúmenes o pools, solo se ven afectados los grupos de volúmenes y pools recién creados. Todos los grupos de volúmenes y pools existentes con el aprovisionamiento de recursos habilitado permanecerán sin cambios.

.Pasos
. Seleccione MENU:Settings[System].
. Desplácese hasta *Configuración adicional* y, a continuación, haga clic en *Habilitar/deshabilitar volúmenes aprovisionados mediante recursos*.
+
La descripción de la configuración indica si el aprovisionamiento de recursos está activado o desactivado.

. Confirme la operación en el cuadro de diálogo.


.Resultados
La habilitación o deshabilitación del aprovisionamiento de recursos afecta únicamente a los pools de SSD o los grupos de volúmenes nuevos que se creen. Los pools o grupos de volúmenes existentes no cambian.
