---
permalink: sm-settings/enable-feature-pack.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, feature, pack, 
summary: 'Un paquete de funciones es un paquete que cambia los atributos de la cabina de almacenamiento (por ejemplo, cambiar el protocolo Fibre Channel a iSCSI). Para habilitar paquetes de funciones, se requiere una clave especial.' 
---
= Habilite el paquete de funciones
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un paquete de funciones es un paquete que cambia los atributos de la cabina de almacenamiento (por ejemplo, cambiar el protocolo Fibre Channel a iSCSI). Para habilitar paquetes de funciones, se requiere una clave especial.

.Antes de empezar
* Siguió las instrucciones adecuadas donde se describen la conversión y la preparación de los nuevos atributos de la cabina de almacenamiento. Para obtener instrucciones sobre la conversión de protocolos de host, consulte la guía de mantenimiento de hardware para su modelo de controladora.
* La cabina de almacenamiento está sin conexión, por lo que ningún host ni aplicación accede a la cabina.
* Existen backups de todos los datos.
* Obtuvo un archivo de paquete de funciones.
+
El paquete de funciones está cargado en el cliente de gestión (el sistema con un explorador para acceder a System Manager).



[NOTE]
====
Debe programar una ventana de mantenimiento de tiempo de inactividad y detener todas las operaciones de I/o entre el host y las controladoras. Además, tenga en cuenta que no podrá acceder a los datos en la cabina de almacenamiento hasta después de completar correctamente la conversión.

====
.Acerca de esta tarea
En esta tarea, se describe cómo usar System Manager para habilitar un paquete de funciones. Al finalizar, debe reiniciar la cabina de almacenamiento.

.Pasos
. Seleccione MENU:Settings[System].
. En *Complementos*, seleccione *Cambiar paquete de funciones*.
. Haga clic en *examinar* y, a continuación, seleccione el archivo de claves.
+
El nombre del archivo aparece en el cuadro de diálogo.

. Tipo `change` en el campo.
. Haga clic en *Cambiar*.
+
Comienza la migración del paquete de funciones y se reinician las controladoras. Se eliminan los datos no escritos en la caché, lo que garantiza que no exista actividad de I/O. Las dos controladoras se reinician automáticamente para que el nuevo paquete de funciones entre en vigencia. La cabina de almacenamiento vuelve a responder cuando se completa el reinicio.


