---
permalink: sm-settings/what-is-the-difference-between-internal-security-key-and-external-security-key-management.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, internal, security, key, external, security, key, management, 
summary: Cuando se implementa la función Drive Security, es posible utilizar una clave de seguridad interna o una clave de seguridad externa para bloquear los datos cuando se quita una unidad con la función de seguridad habilitada de la cabina de almacenamiento. 
---
= ¿Cuál es la diferencia entre la gestión de claves de seguridad interna y de claves de seguridad externa?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se implementa la función Drive Security, es posible utilizar una clave de seguridad interna o una clave de seguridad externa para bloquear los datos cuando se quita una unidad con la función de seguridad habilitada de la cabina de almacenamiento.

Una clave de seguridad es una cadena de caracteres, que se comparte entre las unidades y controladoras con la función de seguridad habilitada en una cabina de almacenamiento. Las claves internas se conservan en la memoria persistente de la controladora. Las claves externas se mantienen en un servidor de gestión de claves individual mediante un protocolo de interoperabilidad de gestión de claves (KMIP).
