---
permalink: sm-settings/why-are-timestamps-inconsistent-between-the-array-and-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, timestamps, inconsistent, array, alerts, 
summary: 'Cuando la cabina de almacenamiento envía alertas, no corrige la zona horaria según el host o servidor de destino que recibe las alertas. En cambio, la cabina de almacenamiento utiliza la hora local (GMT) para crear la Marca de tiempo que se utiliza para el registro de alertas. Como resultado, es posible que se observen inconsistencias entre las marcas de tiempo de la cabina de almacenamiento y el servidor o host que recibe una alerta.' 
---
= ¿Por qué las marcas de tiempo no son consistentes entre la cabina y las alertas?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando la cabina de almacenamiento envía alertas, no corrige la zona horaria según el host o servidor de destino que recibe las alertas. En cambio, la cabina de almacenamiento utiliza la hora local (GMT) para crear la Marca de tiempo que se utiliza para el registro de alertas. Como resultado, es posible que se observen inconsistencias entre las marcas de tiempo de la cabina de almacenamiento y el servidor o host que recibe una alerta.

Debido a que la cabina de almacenamiento no corrige la zona horaria cuando envía alertas, la Marca de tiempo de las alertas está en horario GMT, que tiene un valor cero de desfase de zona horaria. Para calcular una Marca de tiempo adecuada para su zona horaria local, debe determinar el desfase de su zona horaria respecto a GMT y sumar o restar ese valor a las marcas de tiempo.

[NOTE]
====
Para evitar esto, configure el protocolo de tiempo de redes (NTP) en las controladoras de la cabina de almacenamiento. NTP se asegura de que las controladoras siempre estén sincronizadas con la hora correcta.

====