---
permalink: san-getstarted/supported-browsers-os.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: Para acceder a SANtricity pueden usarse varios tipos de exploradores y sistemas operativos. 
---
= Exploradores compatibles y sistemas operativos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El software SANtricity admite varios tipos de exploradores y sistemas operativos.



== Exploradores

Se admiten los siguientes exploradores en las versiones mencionadas.

[cols="1a,1a"]
|===
| Navegador | Versión mínima 


 a| 
Google Chrome
 a| 
79



 a| 
Mozilla Firefox
 a| 
70



 a| 
Safari
 a| 
12



 a| 
Microsoft Edge
 a| 
79



 a| 
Entorno heredado de Microsoft Edge
 a| 
18



 a| 
Microsoft Internet Explorer (MSIE)
 a| 
11

|===
[NOTE]
====
Para Unified Manager, el proxy de servicios web debe estar instalado y disponible para el explorador. Para obtener más información, consulte https://docs.netapp.com/us-en/e-series/web-services-proxy/index.html["Información general sobre el proxy de servicios web de SANtricity"^]

====


== Sistemas operativos

Se admiten los sistemas operativos y las versiones siguientes.

[cols="1a,1a"]
|===
| De NetApp | Versión/arquitectura mínima 


 a| 
Red Hat Enterprise Linux (RHEL)
 a| 
7.x, 8.x / 64 bits



 a| 
SUSE Linux Enterprise Server (SLES)
 a| 
12.x, 15.x / 64 bits



 a| 
Oracle Linux (OL)
 a| 
7.x, 8.x / 64 bits



 a| 
Servidor Windows Server
 a| 
2016, 2019, 2022 / 64 bits



 a| 
Ubuntu
 a| 
18.04, 20.04 / 64 bits

|===