---
permalink: san-getstarted/supported-browsers-os.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: Para acceder a SANtricity pueden usarse varios tipos de exploradores y sistemas operativos. 
---
= Compatibilidad con navegadores y sistemas operativos del software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El software SANtricity admite varios tipos de exploradores y sistemas operativos.



== Exploradores

Se admiten los siguientes exploradores en las versiones mencionadas.

[cols="1a,1a"]
|===
| Navegador | Versión mínima 


 a| 
Google Chrome
 a| 
89



 a| 
Mozilla Firefox
 a| 
80



 a| 
Safari
 a| 
14



 a| 
Microsoft Edge
 a| 
90

|===
[NOTE]
====
Para Unified Manager, el proxy de servicios web debe estar instalado y disponible para el explorador. Para obtener más información, consulte https://docs.netapp.com/us-en/e-series/web-services-proxy/index.html["Información general sobre el proxy de servicios web de SANtricity"^]

====


== Sistemas operativos

Se admiten los sistemas operativos y las versiones siguientes.

[cols="1a,1a"]
|===
| De NetApp | Versión/arquitectura mínima 


 a| 
Red Hat Enterprise Linux (RHEL)
 a| 
8.x (SP8), 9.x (SP2) / 64-bit



 a| 
SUSE Linux Enterprise Server (SLES)
 a| 
12.x (SP4, SP5), 15.x (SP4, SP5) / 64-bit



 a| 
Oracle Linux (OL)
 a| 
8.x (U8), 9.x (U2) / 64-bit



 a| 
Servidor Windows Server
 a| 
2019, 2022, 2025 / 64-bit



 a| 
Ubuntu
 a| 
20.04, 22.04 / 64-bit

|===