---
permalink: um-certificates/access-management-with-directory-services-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, access management, directory services, 
summary: 'Los administradores pueden usar un servidor LDAP (protocolo ligero de acceso a directorios) y un servicio de directorio, como Active Directory de Microsoft.' 
---
= Access Management con servicios de directorio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los administradores puede usar un servidor de protocolo ligero de acceso a directorios (LDAP) y un servicio de directorio, como Active Directory de Microsoft.



== Flujo de trabajo de configuración

Si se utilizan un servidor LDAP y un servicio de directorio en la red, la configuración opera de la siguiente manera:

. Un administrador inicia sesión en Unified Manager con un perfil de usuario que incluye permisos de administrador de seguridad.
+
[NOTE]
====
La `admin` el usuario tiene acceso completo a todas las funciones del sistema.

====
. El administrador introduce los ajustes de configuración del servidor LDAP. Entre ellas se encuentran el nombre de dominio, la URL y la información de la cuenta vinculada.
. Si el servidor LDAP utiliza un protocolo seguro (LDAPS), el administrador carga una cadena de certificados de una entidad de certificación (CA) para la autenticación entre el servidor LDAP y el sistema host donde se instaló el proxy de servicios web.
. Después de establecer la conexión del servidor, el administrador asigna los grupos de usuarios a los roles de usuario local. Estos roles están predefinidos y no pueden modificarse.
. El administrador prueba la conexión entre el servidor LDAP y el proxy de servicios web.
. Los usuarios inician sesión en el sistema con las credenciales de LDAP/servicios de directorio asignadas.




== Gestión

Al utilizar los servicios de directorio para la autenticación, los administradores pueden realizar las siguientes tareas de gestión:

* Añadir servidor de directorio.
* Editar la configuración del servidor de directorio.
* Asignar usuarios LDAP a roles de usuario local.
* Quitar un servidor de directorio.
* Cambiar contraseñas.
* Configurar la longitud mínima de las contraseñas.
* Permitir que los usuarios inicien sesión sin contraseñas.

