---
permalink: um-certificates/access-management-terminology-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, access management, terminology 
summary: Conozca la forma en que los términos de Access Management se aplican a SANtricity Unified Manager. 
---
= Terminología de Access Management
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conozca la forma en que los términos de Access Management se aplican a Unified Manager.

[cols="25h,~"]
|===
| Duración | Descripción 


 a| 
Active Directory
 a| 
Active Directory (AD) es un servicio de directorio de Microsoft en el que se utiliza LDAP para redes de dominio de Windows.



 a| 
Vinculación
 a| 
Las operaciones de vinculación se usan para autenticar clientes en el servidor de directorio. Por lo general, la vinculación requiere credenciales de cuenta y contraseña, pero algunos servidores aceptan operaciones de vinculación anónimas.



 a| 
APROX
 a| 
Una entidad de certificación (CA) es una entidad de confianza que emite documentos electrónicos, denominados certificados digitales, para la seguridad de Internet. Estos certificados identifican a los propietarios de sitios web y, de esta manera, permiten conexiones seguras entre clientes y servidores.



 a| 
Certificado
 a| 
Un certificado identifica al propietario de un sitio con el fin de brindar seguridad, para evitar que atacantes se hagan pasar por los propietarios del sitio. El certificado tiene información acerca del propietario del sitio y la identidad de la entidad de confianza que certifica (firma) esta información.



 a| 
LDAP
 a| 
El protocolo ligero de acceso a directorios (LDAP) es un protocolo de aplicación para acceder a servicios distribuidos de información de directorio y mantenerlos. Este protocolo permite que varias aplicaciones y servicios se conecten con el servidor LDAP para validar usuarios.



 a| 
RBAC
 a| 
El control de acceso basado en funciones (RBAC) es un método para regular el acceso a los recursos informáticos o de red en función de las funciones de los usuarios individuales. Unified Manager incluye roles predefinidos.



 a| 
SSO
 a| 
El inicio de sesión único (SSO) es un servicio de autenticación que permite el uso de un conjunto de credenciales de inicio de sesión para acceder a varias aplicaciones.



 a| 
Proxy de servicios web
 a| 
El proxy de servicios web, que proporciona acceso mediante mecanismos HTTPS estándar, permite a los administradores configurar servicios de gestión para las cabinas de almacenamiento. El proxy se puede instalar en hosts Windows o Linux. La interfaz de Unified Manager se encuentra disponible con el proxy de servicios web.

|===