---
permalink: um-certificates/change-local-user-passwords-settings-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, local, user, password, settings 
summary: Es posible configurar la longitud mínima requerida para todas las contraseñas de usuario local nuevas o actualizadas. También es posible permitir a los usuarios locales que accedan al sistema sin introducir una contraseña. 
---
= Cambie la configuración de contraseña de usuario local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible configurar la longitud mínima requerida para todas las contraseñas de usuario local nuevas o actualizadas. También es posible permitir a los usuarios locales que accedan al sistema sin introducir una contraseña.

.Antes de empezar
Inició sesión como administrador local, lo que incluye permisos de administrador raíz.

.Acerca de esta tarea
Recuerde estas directrices cuando configure la longitud mínima para las contraseñas de usuario local:

* Los cambios en la configuración no afectan a las contraseñas existentes de usuarios locales.
* La configuración de la longitud mínima requerida para las contraseñas de usuario local debe tener entre 0 y 30 caracteres.
* Todas las contraseñas de usuario local nuevas deben alcanzar o superar la configuración de longitud mínima actual.
* No configure una longitud mínima para la contraseña si desea que los usuarios locales accedan al sistema sin introducir una contraseña.


.Pasos
. Seleccione *Access Management*.
. Seleccione la ficha *roles de usuario local*.
. Seleccione *Ver/editar configuración*.
+
Se abre el cuadro de diálogo Configuración de contraseña de usuario local.

. Debe realizar una de las siguientes acciones:
+
** Para permitir a los usuarios locales que accedan al sistema _without_ password, desactive la casilla de verificación "requerir que todas las contraseñas de usuario local tengan al menos...".
** Si desea configurar una longitud mínima de contraseña para todas las contraseñas de usuario local, active la casilla de comprobación "requerir que todas las contraseñas de usuario local tengan al menos..." y luego use el cuadro de desplazamiento para configurar la longitud mínima requerida para todas las contraseñas de usuario local
+
Todas las contraseñas de usuario local nuevas deben alcanzar o superar la configuración actual.



. Haga clic en *Guardar*.

