---
permalink: um-certificates/change-passwords-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, passwords 
summary: Es posible cambiar las contraseñas de usuario de cada usuario desde Access Management. 
---
= Cambiar contraseñas de perfiles de usuario local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar las contraseñas de usuario de cada usuario desde Access Management.

.Antes de empezar
* Inició sesión como administrador local, lo que incluye permisos de administrador raíz.
* Debe conocer la contraseña de administrador local.


.Acerca de esta tarea
Tenga en cuenta estas directrices al elegir una contraseña:

* Todas las contraseñas de usuarios locales nuevas deben alcanzar o superar la configuración de longitud mínima actual de la contraseña (en Ver/editar configuración).
* Las contraseñas distinguen mayúsculas de minúsculas.
* Los espacios al final de la contraseña no se eliminan si se los utiliza. Procure incluir espacios si se incluyeron en la contraseña.
* Para mayor seguridad, use al menos 15 caracteres alfanuméricos y cambie la contraseña con frecuencia.


.Pasos
. Seleccione *Access Management*.
. Seleccione la ficha *roles de usuario local*.
. Seleccione un usuario de la tabla.
+
Se habilita el botón Cambiar contraseña.

. Seleccione *Cambiar contraseña*.
+
Se abre el cuadro de diálogo Cambiar contraseña.

. Si no existe una longitud mínima de contraseña establecida para las contraseñas de usuario local, puede seleccionar la casilla de comprobación para requerir que el usuario introduzca una contraseña para acceder al sistema.
. Introduzca la contraseña nueva para el usuario seleccionado en los dos campos.
. Introduzca su contraseña de administrador local para confirmar esta operación y, a continuación, haga clic en *Cambiar*.


.Resultados
Si el usuario está conectado, el cambio de contraseña provocará el cierre de la sesión activa del usuario.
