---
permalink: um-certificates/overview-certificates-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, certificate management 
summary: 'La gestión de certificados permite crear solicitudes de firma de certificados (CSR), importar certificados y gestionar certificados existentes.' 
---
= Información general sobre certificados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La gestión de certificados permite crear solicitudes de firma de certificados (CSR), importar certificados y gestionar certificados existentes.



== ¿Qué son los certificados?

_Certificates_ son archivos digitales que identifican entidades en línea, como sitios web y servidores, para comunicaciones seguras en Internet. Existen dos tipos de certificados: Un _certificado firmado_ es validado por una entidad de certificación (CA) y un _certificado autofirmado_ es validado por el propietario de la entidad en lugar de por un tercero.

Obtenga más información:

* link:how-certificates-work-unified.html["Cómo funcionan los certificados"]
* link:certificate-terminology-unified.html["Terminología de certificados"]




== ¿Cómo se configuran los certificados?

En Certificate Management, es posible configurar certificados para la estación de gestión donde se aloja Unified Manager e importar también certificados para las controladoras en las cabinas.

Obtenga más información:

* link:use-ca-signed-certificate-um.html["Utilice certificados firmados por CA para el sistema de gestión"]
* link:import-array-certificates-unified.html["Importar certificados para cabinas"]

