---
permalink: um-certificates/permissions-for-mapped-roles-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, permissions, mapped, roles 
summary: 'Las funcionalidades de control de acceso basado en roles (RBAC) incluyen usuarios predefinidos con uno o varios roles asignados. Cada rol incluye permisos para acceder a tareas en SANtricity Unified Manager.' 
---
= Permisos para roles asignados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las funcionalidades de control de acceso basado en roles (RBAC) incluyen usuarios predefinidos con uno o varios roles asignados. Cada rol incluye permisos para acceder a tareas en SANtricity Unified Manager.

Los roles permiten que los usuarios accedan a tareas de la siguiente manera:

* *Storage admin* -- acceso completo de lectura/escritura a los objetos de almacenamiento de las matrices, pero sin acceso a la configuración de seguridad.
* *Security admin* -- acceso a la configuración de seguridad en Access Management y Certificate Management.
* *Support admin* -- acceso a todos los recursos de hardware en matrices de almacenamiento, datos de fallos y eventos MEL. No brinda acceso a los objetos de almacenamiento ni a la configuración de seguridad.
* *Monitor* -- acceso de sólo lectura a todos los objetos de almacenamiento, pero sin acceso a la configuración de seguridad.


Si un usuario no tiene permisos para una función determinada, esa función no se encuentra disponible para selección o no se muestra en la interfaz de usuario.
