---
permalink: um-certificates/use-ca-signed-certificate-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, ca-signed, certificates 
summary: Es posible obtener e importar certificados firmados por CA para establecer un acceso seguro al sistema de gestión donde se aloja Unified Manager. 
---
= Utilice certificados firmados por CA para el sistema de gestión
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible obtener e importar certificados firmados por CA para establecer un acceso seguro al sistema de gestión donde se aloja Unified Manager.

.Antes de empezar
Debe iniciar sesión con un perfil de usuario que cuente con permisos de administración de seguridad. De lo contrario, no se mostrarán las funciones de certificación.

.Acerca de esta tarea
El uso de certificados firmados por CA implica un procedimiento de tres pasos.



== Paso 1: Complete un archivo CSR

Primero, se debe generar un archivo de solicitud de firma de certificación (CSR), que identifica a la organización y al sistema host donde están instalados el proxy de servicios web y Unified Manager.

[NOTE]
====
También puede generar un archivo CSR con una herramienta como OpenSSL y saltar a. <<Paso 2: Enviar archivo CSR>>.

====
.Pasos
. Seleccione *Gestión de certificados*.
. En la ficha Administración, seleccione *completar CSR*.
. Introduzca la siguiente información y, a continuación, haga clic en *Siguiente*:
+
** *Organización* -- el nombre completo y legal de su empresa u organización. Incluya sufijos, como Inc. O Corp
** *Unidad organizativa (opcional)* -- la división de su organización que maneja el certificado.
** *Ciudad/localidad* -- la ciudad donde se encuentra su sistema anfitrión o negocio.
** *Estado/Región (opcional)* -- el estado o región donde está ubicado el sistema o negocio anfitrión.
** *Código ISO de país*: Código ISO (Organización Internacional de Normalización) de dos dígitos de su país, por ejemplo, US.


. Introduzca la siguiente información sobre el sistema host donde está instalado el proxy de servicios web:
+
** *Nombre común* -- la dirección IP o el nombre DNS del sistema host donde está instalado Web Services Proxy. Compruebe que la dirección sea correcta; esta debe coincidir exactamente con lo que se escribe para acceder a Unified Manager en el explorador. No incluya http:// ni https://. El nombre DNS no puede comenzar con un comodín.
** *Direcciones IP alternativas* -- Si el nombre común es una dirección IP, opcionalmente puede escribir cualquier dirección IP adicional o alias para el sistema host. Si va a introducir varios datos, use un formato delimitado por comas.
** *Nombres DNS alternativos* -- Si el nombre común es un nombre DNS, introduzca cualquier nombre DNS adicional para el sistema host. Si va a introducir varios datos, use un formato delimitado por comas. Si no hay nombres DNS alternativos, pero especificó un nombre DNS en el primer campo, copie ese nombre aquí. El nombre DNS no puede comenzar con un comodín.


. Asegúrese de que la información del host sea correcta. Si no lo es, los certificados que se devuelven de la CA fallarán cuando intente importarlos.
. Haga clic en *Finalizar*.
. Vaya a. <<Paso 2: Enviar archivo CSR>>.




== Paso 2: Enviar archivo CSR

Después de crear un archivo de solicitud de firma de certificación (CSR), se lo envía a una entidad de certificación (CA) para recibir certificados de gestión firmados para el sistema donde se aloja Unified Manager y el proxy de servicios web.


NOTE: Los sistemas E-Series requieren un formato PEM (codificación ASCII Base64) para certificados firmados, que incluye los siguientes tipos de archivo: .Pem, .crt, .cer o .key.

.Pasos
. Busque el archivo CSR descargado.
+
La ubicación de la carpeta de la descarga depende del explorador.

. Envíe el archivo CSR a una CA (por ejemplo, VeriSign o DigiCert) y solicite certificados firmados en formato PEM.
+
[CAUTION]
====
*Después de enviar un archivo CSR a la CA, NO vuelva a generar otro archivo CSR.* cada vez que genere una CSR, el sistema creará un par de claves pública y privada. La clave pública se incluye en la CSR, mientras que la clave privada se conserva en el almacén de claves del sistema. Cuando recibe los certificados firmados e importarlos, el sistema se asegura de que las claves pública y privada sean la pareja original. Si las claves no coinciden, los certificados firmados no funcionarán y debe solicitar certificados nuevos de la CA.

====
. Cuando la CA devuelva los certificados firmados, vaya a. <<Paso 3: Importar certificados de gestión>>.




== Paso 3: Importar certificados de gestión

Después de recibir certificados firmados de la CA, importe los certificados al sistema host donde se instalaron la interfaz de proxy de servicios web y Unified Manager.

.Antes de empezar
* Recibió certificados firmados de la CA. Estos archivos incluyen el certificado raíz, uno o varios certificados intermedios y el certificado de servidor.
* Si la CA proporcionó un archivo de certificado encadenado (por ejemplo, un archivo .p7b), debe desempaquetar el archivo encadenado en archivos individuales: El certificado raíz, el o los certificados intermedios y el certificado de servidor. Puede utilizar Windows `certmgr` Utilidad para desempaquetar los archivos (haga clic con el botón derecho y seleccione MENU:todas las tareas[Exportar]). Se recomienda la codificación base-64. Una vez completadas las exportaciones, se mostrará un archivo CER para cada archivo de certificado de la cadena.
* Copió los archivos de certificado en el sistema host donde se ejecuta el proxy de servicios web.


.Pasos
. Seleccione *Gestión de certificados*.
. En la ficha Administración, seleccione *Importar*.
+
Se abre un cuadro de diálogo para importar los archivos de certificado.

. Haga clic en *examinar* para seleccionar primero los archivos de certificado raíz e intermedio y, a continuación, seleccionar el certificado de servidor. Si generó la CSR desde una herramienta externa, también debe importar el archivo de claves privadas que se creó junto con la CSR.
+
Se muestran los nombres de los archivos en el cuadro de diálogo.

. Haga clic en *Importar*.


.Resultados
Los archivos se cargan y validan. La información del certificado aparece en la página Gestión de certificados.
