---
permalink: um-certificates/view-certificates-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, view certificates 
summary: 'Es posible ver información resumida de un certificado, incluida la organización que utiliza el certificado, la entidad que lo emite, el periodo de validez y las huellas digitales (identificadores únicos).' 
---
= Ver certificados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible ver información resumida de un certificado, incluida la organización que utiliza el certificado, la entidad que lo emite, el periodo de validez y las huellas digitales (identificadores únicos).

.Antes de empezar
Debe iniciar sesión con un perfil de usuario que cuente con permisos de administración de seguridad. De lo contrario, no se mostrarán las funciones de certificación.

.Pasos
. Seleccione *Gestión de certificados*.
. Seleccione una de las siguientes pestañas:
+
** *Administración* -- muestra el certificado para el sistema que aloja el proxy de servicios web. Un certificado de gestión puede estar autofirmado o estar aprobado por una CA. Permite un acceso seguro a Unified Manager.
** *Trusted*: Muestra los certificados a los que Unified Manager puede acceder para matrices de almacenamiento y otros servidores remotos, como un servidor LDAP. Los certificados pueden emitirse mediante una CA o estar autofirmados.


. Para ver más información sobre un certificado, seleccione la fila correspondiente, seleccione las tres puntos al final de la fila y haga clic en *Ver* o *Exportar*.

