---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: Debe configurar Unified Manager de SANtricity con una contraseña de administrador para proteger la instancia del acceso no autorizado. 
---
= Configure la protección con contraseña de administrador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar Unified Manager de SANtricity con una contraseña de administrador para proteger la instancia del acceso no autorizado.



== Contraseña de administrador y perfiles de usuario

Cuando se inicia Unified Manager por primera vez, se le solicita que establezca una contraseña de administrador. Cualquier usuario que tenga la contraseña de administrador puede realizar cambios de configuración en las cabinas de almacenamiento.

Además de la contraseña de administrador, la interfaz de Unified Manager incluye perfiles de usuario preconfigurados con uno o varios roles asignados. Para obtener más información, consulte link:../um-certificates/how-access-management-works-unified.html["Cómo funciona Access Management"].

Los usuarios y las asignaciones no pueden cambiarse. Solo las contraseñas pueden modificarse. Para cambiar las contraseñas, consulte:

* link:change-admin-password-unified.html["Cambie la contraseña de administrador"]
* link:../um-certificates/change-passwords-unified.html["Cambiar contraseñas de perfiles de usuario local"]




== Tiempos de espera de sesión

El software solicita la contraseña una sola vez durante una misma sesión de gestión. De forma predeterminada, una sesión finaliza a los 30 minutos de inactividad; después de ese plazo, deberá introducir la contraseña otra vez. Si otro usuario accede al software desde otro cliente de gestión y cambia la contraseña mientras su sesión está en progreso, se le solicitará a usted una contraseña la próxima vez que intente realizar una operación de configuración o de vista.

Por razones de seguridad, puede intentar introducir una contraseña solo cinco veces antes de que el software quede bloqueado. En este estado, el software rechaza cualquier nuevo intento de introducir una contraseña. Se deben esperar 10 minutos para que el software se restablezca a un estado normal y usted pueda volver a introducir una contraseña.

Es posible ajustar los tiempos de espera de la sesión, o bien directamente pueden deshabilitarse los tiempos de espera de sesión. Para obtener más información, consulte link:manage-session-timeouts-unified.html["Gestionar los tiempos de espera de sesión"].
