---
permalink: um-admin/change-admin-password-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, admin, password 
summary: Es posible cambiar la contraseña de administrador que se utiliza para acceder a SANtricity Unified Manager. 
---
= Cambie la contraseña de administrador
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar la contraseña de administrador que se utiliza para acceder a Unified Manager.

.Antes de empezar
* Inició sesión como administrador local, lo que incluye permisos de administrador raíz.
* Debe conocer la contraseña de administrador actual.


.Acerca de esta tarea
Tenga en cuenta estas directrices al elegir una contraseña:

* Las contraseñas distinguen mayúsculas de minúsculas.
* Los espacios al final de la contraseña no se eliminan si se los utiliza. Procure incluir espacios si se incluyeron en la contraseña.
* Para mayor seguridad, use al menos 15 caracteres alfanuméricos y cambie la contraseña con frecuencia.


.Pasos
. Seleccione MENU:Settings[Access Management].
. Seleccione la ficha *roles de usuario local*.
. Seleccione el usuario *admin* de la tabla.
+
Se habilita el botón Cambiar contraseña.

. Seleccione *Cambiar contraseña*.
+
Se abre el cuadro de diálogo Cambiar contraseña.

. Si no se estableció una longitud mínima para las contraseñas de usuario local, marque la casilla de aprobación para solicitarle al usuario que introduzca una contraseña a fin de acceder al sistema.
. Introduzca la nueva contraseña en los dos campos.
. Introduzca su contraseña de administrador local para confirmar esta operación y, a continuación, haga clic en *Cambiar*.

