---
permalink: um-admin/change-storage-array-passwords.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, storage, array, passwords 
summary: Puede actualizar las contraseñas que se utilizan para ver y acceder a las cabinas de almacenamiento en SANtricity Unified Manager. 
---
= Cambiar contraseñas de las cabinas de almacenamiento
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede actualizar las contraseñas que se utilizan para ver y acceder a las cabinas de almacenamiento en Unified Manager.

.Antes de empezar
* Debe iniciar sesión con un perfil de usuario que cuente con permisos de administración de almacenamiento.
* Debe conocer la contraseña actual de la cabina de almacenamiento que se estableció en System Manager.


.Acerca de esta tarea
En esta tarea, debe introducir la contraseña actual de una cabina de almacenamiento para poder acceder a esta en Unified Manager. Esto puede ser necesario si se modificó la contraseña de la cabina en System Manager y ahora se debe modificar también Unified Manager.

.Pasos
. En la página gestionar, seleccione una o varias cabinas de almacenamiento.
. Seleccione menú:tareas no comunes[proporcionar contraseñas de cabina de almacenamiento].
. Introduzca la contraseña o las contraseñas de cada cabina de almacenamiento y haga clic en *Guardar*.

